{
  "hash": "0616a055820c6db956991059f959d07d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Ex06: Geographical Segmentation with Spatially Constrained Clustering\"\nsubtitle: \"Delineating ICT regions across the townships of Shan State, Myanmar\"\nauthor: \"Meng Tingyu\"\ndate: \"October 2, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show the code\"\n    code-tools: true\n    fig-align: center\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n## What this exercise is about\n\nThis exercise groups the 55 townships of Shan State in Myanmar into regions with similar access to information and communication technology. The grouping uses six household ICT measures from the 2014 census, radio, television, land line phone, mobile phone, computer and internet at home.\n\nPlanners often want regions that are both homogeneous and joined together on the map. Ordinary cluster analysis only looks at the first condition. The second half of the exercise adds the map back in, first with SKATER, which cuts a minimum spanning tree of neighbouring townships, and then with ClustGeo, which lets me choose how much weight geography gets.\n\nThe work is split into six parts. Part 1 explores the variables with charts and choropleth maps, Part 2 checks correlations, and Part 3 runs hierarchical clustering. Part 4 and Part 5 cover the two spatially constrained methods, and Part 6 profiles the clusters.\n\n## Setting up\n\n### The data\n\nTwo datasets come from the Myanmar Information Management Unit (MIMU).\n\nThe first is `myanmar_township_boundaries`, an ESRI shapefile with the polygon boundary of every township in Myanmar. The second is `Shan-ICT.csv`, an extract of the 2014 Myanmar Population and Housing Census at township level. It has the number of households in each township and the number that own each of the six ICT items.\n\nI put the shapefile in `data/geospatial` and the csv in `data/aspatial`, and added an empty `data/rds` folder for the intermediate files. The notes use `chap12/data/...`, and I changed every path to match this folder layout.\n\n### Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(spdep, tmap, sf, ClustGeo, \n               ggpubr, cluster, factoextra, NbClust,\n               heatmaply, corrplot, psych, tidyverse, GGally)\n```\n:::\n\n\nThe packages fall into five groups. **sf** and **spdep** handle the spatial data, and **tidyverse** covers readr, dplyr, tidyr and ggplot2 for the attribute data. **tmap** draws the choropleth maps. **corrplot**, **ggpubr**, **heatmaply**, **psych** and **GGally** are used to visualise the variables, and **cluster**, **factoextra**, **NbClust** and **ClustGeo** run the cluster analysis.\n\n::: {.callout-note}\n## rgdal is no longer needed\n\nThe package list in the notes mentions **rgdal**. It was retired from CRAN in 2023, and sf now does all of its reading and writing work, so I left it out. The `p_load()` call in the notes already does not include it.\n:::\n\n### Importing the township boundaries\n\n`st_read()` reads the whole country. I keep only the three parts of Shan State and the six columns from state name to township code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf <- st_read(dsn = \"data/geospatial\", \n                   layer = \"myanmar_township_boundaries\") %>%\n  filter(ST %in% c(\"Shan (East)\", \"Shan (North)\", \"Shan (South)\")) %>%\n  select(c(2:7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `myanmar_township_boundaries' from data source \n  `D:\\mengtingyu88\\geospatial-coursework\\Hands-on_Ex\\Hands-on_Ex06\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 330 features and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 92.17275 ymin: 9.671252 xmax: 101.1699 ymax: 28.54554\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThe full layer has 330 townships and 15 fields in WGS 84. After filtering there are 55 townships, 24 in Shan (North), 21 in Shan (South) and 10 in Shan (East).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 55 features and 6 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 96.15107 ymin: 19.29932 xmax: 101.1699 ymax: 24.15907\nGeodetic CRS:  WGS 84\nFirst 10 features:\n             ST ST_PCODE       DT   DT_PCODE        TS  TS_PCODE\n1  Shan (North)   MMR015  Mongmit MMR015D008   Mongmit MMR015017\n2  Shan (South)   MMR014 Taunggyi MMR014D001   Pindaya MMR014006\n3  Shan (South)   MMR014 Taunggyi MMR014D001   Ywangan MMR014007\n4  Shan (South)   MMR014 Taunggyi MMR014D001  Pinlaung MMR014009\n5  Shan (North)   MMR015  Mongmit MMR015D008    Mabein MMR015018\n6  Shan (South)   MMR014 Taunggyi MMR014D001     Kalaw MMR014005\n7  Shan (South)   MMR014 Taunggyi MMR014D001     Pekon MMR014010\n8  Shan (South)   MMR014 Taunggyi MMR014D001  Lawksawk MMR014008\n9  Shan (North)   MMR015  Kyaukme MMR015D003 Nawnghkio MMR015013\n10 Shan (North)   MMR015  Kyaukme MMR015D003   Kyaukme MMR015012\n                         geometry\n1  MULTIPOLYGON (((96.96001 23...\n2  MULTIPOLYGON (((96.7731 21....\n3  MULTIPOLYGON (((96.78483 21...\n4  MULTIPOLYGON (((96.49518 20...\n5  MULTIPOLYGON (((96.66306 24...\n6  MULTIPOLYGON (((96.49518 20...\n7  MULTIPOLYGON (((97.14738 19...\n8  MULTIPOLYGON (((96.94981 22...\n9  MULTIPOLYGON (((96.75648 22...\n10 MULTIPOLYGON (((96.95498 22...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(shan_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 55\nColumns: 7\n$ ST       <chr> \"Shan (North)\", \"Shan (South)\", \"Shan (South)\", \"Shan (South)…\n$ ST_PCODE <chr> \"MMR015\", \"MMR014\", \"MMR014\", \"MMR014\", \"MMR015\", \"MMR014\", \"…\n$ DT       <chr> \"Mongmit\", \"Taunggyi\", \"Taunggyi\", \"Taunggyi\", \"Mongmit\", \"Ta…\n$ DT_PCODE <chr> \"MMR015D008\", \"MMR014D001\", \"MMR014D001\", \"MMR014D001\", \"MMR0…\n$ TS       <chr> \"Mongmit\", \"Pindaya\", \"Ywangan\", \"Pinlaung\", \"Mabein\", \"Kalaw…\n$ TS_PCODE <chr> \"MMR015017\", \"MMR014006\", \"MMR014007\", \"MMR014009\", \"MMR01501…\n$ geometry <MULTIPOLYGON [°]> MULTIPOLYGON (((96.96001 23..., MULTIPOLYGON (((…\n```\n\n\n:::\n:::\n\n\n`shan_sf` is an sf data frame, so it works with dplyr verbs and `glimpse()` like any tibble. All six attribute columns are character, and the geometry is MULTIPOLYGON in degrees.\n\n### Importing the census extract\n\n\n::: {.cell}\n\n```{.r .cell-code}\nict <- read_csv(\"data/aspatial/Shan-ICT.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ict)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n District Pcode     District Name      Township Pcode     Township Name     \n Length:55          Length:55          Length:55          Length:55         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n Total households     Radio         Television    Land line phone \n Min.   : 3318    Min.   :  115   Min.   :  728   Min.   :  20.0  \n 1st Qu.: 8711    1st Qu.: 1260   1st Qu.: 3744   1st Qu.: 266.5  \n Median :13685    Median : 2497   Median : 6117   Median : 695.0  \n Mean   :18369    Mean   : 4487   Mean   :10183   Mean   : 929.9  \n 3rd Qu.:23471    3rd Qu.: 6192   3rd Qu.:13906   3rd Qu.:1082.5  \n Max.   :82604    Max.   :30176   Max.   :62388   Max.   :6736.0  \n  Mobile phone      Computer      Internet at home\n Min.   :  150   Min.   :  20.0   Min.   :   8.0  \n 1st Qu.: 2037   1st Qu.: 121.0   1st Qu.:  88.0  \n Median : 3559   Median : 244.0   Median : 316.0  \n Mean   : 6470   Mean   : 575.5   Mean   : 760.2  \n 3rd Qu.: 7177   3rd Qu.: 507.0   3rd Qu.: 630.5  \n Max.   :48461   Max.   :6705.0   Max.   :9746.0  \n```\n\n\n:::\n:::\n\n\nThe table has 11 fields and 55 rows, one per township. Four fields are identifiers and seven are counts of households. Every count is strongly right skewed. Total households range from 3,318 to 82,604, and the mean of 18,369 sits well above the median of 13,685.\n\n### Deriving penetration rates\n\nThe raw counts mostly measure how big a township is. A township with many households will also have many households with a radio, and that says nothing about how common radios are there. I divided each count by the total number of households and multiplied by 1,000 to get the number of owning households per thousand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nict_derived <- ict %>%\n  mutate(`RADIO_PR` = `Radio`/`Total households`*1000) %>%\n  mutate(`TV_PR` = `Television`/`Total households`*1000) %>%\n  mutate(`LLPHONE_PR` = `Land line phone`/`Total households`*1000) %>%\n  mutate(`MPHONE_PR` = `Mobile phone`/`Total households`*1000) %>%\n  mutate(`COMPUTER_PR` = `Computer`/`Total households`*1000) %>%\n  mutate(`INTERNET_PR` = `Internet at home`/`Total households`*1000) %>%\n  rename(`DT_PCODE` =`District Pcode`,`DT`=`District Name`,\n         `TS_PCODE`=`Township Pcode`, `TS`=`Township Name`,\n         `TT_HOUSEHOLDS`=`Total households`,\n         `RADIO`=`Radio`, `TV`=`Television`, \n         `LLPHONE`=`Land line phone`, `MPHONE`=`Mobile phone`,\n         `COMPUTER`=`Computer`, `INTERNET`=`Internet at home`) \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ict_derived)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   DT_PCODE              DT              TS_PCODE              TS           \n Length:55          Length:55          Length:55          Length:55         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n TT_HOUSEHOLDS       RADIO             TV           LLPHONE      \n Min.   : 3318   Min.   :  115   Min.   :  728   Min.   :  20.0  \n 1st Qu.: 8711   1st Qu.: 1260   1st Qu.: 3744   1st Qu.: 266.5  \n Median :13685   Median : 2497   Median : 6117   Median : 695.0  \n Mean   :18369   Mean   : 4487   Mean   :10183   Mean   : 929.9  \n 3rd Qu.:23471   3rd Qu.: 6192   3rd Qu.:13906   3rd Qu.:1082.5  \n Max.   :82604   Max.   :30176   Max.   :62388   Max.   :6736.0  \n     MPHONE         COMPUTER         INTERNET         RADIO_PR     \n Min.   :  150   Min.   :  20.0   Min.   :   8.0   Min.   : 21.05  \n 1st Qu.: 2037   1st Qu.: 121.0   1st Qu.:  88.0   1st Qu.:138.95  \n Median : 3559   Median : 244.0   Median : 316.0   Median :210.95  \n Mean   : 6470   Mean   : 575.5   Mean   : 760.2   Mean   :215.68  \n 3rd Qu.: 7177   3rd Qu.: 507.0   3rd Qu.: 630.5   3rd Qu.:268.07  \n Max.   :48461   Max.   :6705.0   Max.   :9746.0   Max.   :484.52  \n     TV_PR         LLPHONE_PR       MPHONE_PR       COMPUTER_PR    \n Min.   :116.0   Min.   :  2.78   Min.   : 36.42   Min.   : 3.278  \n 1st Qu.:450.2   1st Qu.: 22.84   1st Qu.:190.14   1st Qu.:11.832  \n Median :517.2   Median : 37.59   Median :305.27   Median :18.970  \n Mean   :509.5   Mean   : 51.09   Mean   :314.05   Mean   :24.393  \n 3rd Qu.:606.4   3rd Qu.: 69.72   3rd Qu.:428.43   3rd Qu.:29.897  \n Max.   :842.5   Max.   :181.49   Max.   :735.43   Max.   :92.402  \n  INTERNET_PR     \n Min.   :  1.041  \n 1st Qu.:  8.617  \n Median : 22.829  \n Mean   : 30.644  \n 3rd Qu.: 41.281  \n Max.   :117.985  \n```\n\n\n:::\n:::\n\n\nSix new fields now sit at the end of the table, `RADIO_PR`, `TV_PR`, `LLPHONE_PR`, `MPHONE_PR`, `COMPUTER_PR` and `INTERNET_PR`. Television is the most common item, with a median of 517 households per thousand. Computers and home internet are rare, with medians of 19 and 23 per thousand.\n\n## Part 1, Exploratory data analysis\n\n### Distribution of radio ownership\n\nA histogram shows the overall shape of a variable, and a boxplot picks out outliers. I started with the raw count of households with a radio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=ict_derived, \n       aes(x=`RADIO`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=ict_derived, \n       aes(x=`RADIO`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe count is heavily right skewed, with a skewness of about 2.6. Three quarters of the townships have fewer than 6,200 radio households, and three outliers sit far to the right, Taunggyi with 30,176, Lashio with 15,307 and Nyaungshwe with 13,801. These are also among the four townships with the most households.\n\nNext I plotted the radio penetration rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=ict_derived, \n       aes(x=`RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=ict_derived, \n       aes(x=`RADIO_PR`)) +\n  geom_boxplot(color=\"black\", \n               fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe course asks what the two distributions reveal. Dividing by households removes most of the skew. `RADIO_PR` has a mean of 216 and a median of 211 per thousand, and its skewness drops to 0.48. The boxplot now flags only one outlier, Ywangan, where 485 of every thousand households own a radio. Taunggyi, the largest outlier in the raw counts, has a rate of 365 and sits inside the whiskers, so its earlier position came from size alone.\n\n### Distributions of all six rates\n\nI drew one histogram for each rate and arranged them with `ggarrange()` from **ggpubr**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nradio <- ggplot(data=ict_derived, \n             aes(x= `RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\ntv <- ggplot(data=ict_derived, \n             aes(x= `TV_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nllphone <- ggplot(data=ict_derived, \n             aes(x= `LLPHONE_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nmphone <- ggplot(data=ict_derived, \n             aes(x= `MPHONE_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\ncomputer <- ggplot(data=ict_derived, \n             aes(x= `COMPUTER_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\ninternet <- ggplot(data=ict_derived, \n             aes(x= `INTERNET_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggarrange(radio, tv, llphone, mphone, computer, internet, \n          ncol = 3, \n          nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-14-1.png){width=1056}\n:::\n:::\n\n\nThe six rates fall into two shapes. Radio, television and mobile phone are roughly bell shaped, with television slightly skewed to the left (skewness -0.38). Land line phone, computer and internet are right skewed, with skewness between 1.3 and 1.8, because most townships have very low rates and a handful have much higher ones.\n\n### Joining the census data to the boundaries\n\nThe choropleth maps need the rates attached to the polygons. `left_join()` keeps `shan_sf` as the base, so the result is still an sf object, and adds the columns of `ict_derived` by matching `TS_PCODE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf <- left_join(shan_sf, \n                     ict_derived, by=c(\"TS_PCODE\"=\"TS_PCODE\"))\n  \nwrite_rds(shan_sf, \"data/rds/shan_sf.rds\")\n```\n:::\n\n\nAll 55 township codes match in both directions, so no township is dropped or left without data.\n\n::: {.callout-note}\n## Why TS.x and TS.y appear\n\nThe notes mention a message naming the join field. With `by` written out there is no message. Both tables have `DT`, `DT_PCODE` and `TS` columns besides the key, so dplyr keeps both copies and adds the suffixes `.x` and `.y`. I checked that `TS.x` and `TS.y` hold the same township name in all 55 rows. That is why the later code refers to `TS.x`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf <- read_rds(\"data/rds/shan_sf.rds\")\n```\n:::\n\n\n### Choropleth map of the radio penetration rate\n\n`qtm()` gives a quick map with default settings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqtm(shan_sf, \"RADIO_PR\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nRadio ownership is highest in the west of Shan South and Shan North. Ywangan, Pindaya and Lawksawk near Taunggyi and Mabein in the north west all exceed 380 per thousand. The lowest rates are in the north east along the Chinese border, Konkyan and Laukkaing in the Kokang area at 21 and 53, and Narphan and Pangwaun in the Wa area at about 75.\n\n### Counts versus rates on the map\n\nTo show how much the counts depend on township size, I mapped total households next to the number of radio households. The notes use tmap v3 syntax here, and I translated it to v4, where the classification goes into `tm_scale_intervals()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTT_HOUSEHOLDS.map <- tm_shape(shan_sf) + \n  tm_polygons(fill = \"TT_HOUSEHOLDS\",\n              fill.scale = tm_scale_intervals(\n                style = \"jenks\",\n                n = 5),\n              fill.legend = tm_legend(\n                title = \"Total households\")) + \n  tm_borders(col_alpha = 0.5) \n\nRADIO.map <- tm_shape(shan_sf) + \n  tm_polygons(fill = \"RADIO\",\n              fill.scale = tm_scale_intervals(\n                style = \"jenks\",\n                n = 5),\n              fill.legend = tm_legend(\n                title = \"Number Radio\")) + \n  tm_borders(col_alpha = 0.5) \n\ntmap_arrange(TT_HOUSEHOLDS.map, RADIO.map,\n             asp=NA, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-18-1.png){width=1152}\n:::\n:::\n\n\nThe two maps look almost the same. Taunggyi and Lashio are in the top class on both, and the correlation between total households and radio households across the 55 townships is 0.94.\n\nNext I put total households next to the rate. The notes do this with two variables in one `tm_polygons()` call and `tm_facets(sync = TRUE)`. In v4, a vector of variables in `fill` already produces facets, and `fill.free = TRUE` gives each one its own Jenks classes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(shan_sf) +\n  tm_polygons(fill = c(\"TT_HOUSEHOLDS\", \"RADIO_PR\"),\n              fill.scale = tm_scale_intervals(\n                style = \"jenks\"),\n              fill.free = TRUE,\n              fill.legend = tm_legend(\n                position = tm_pos_in(\"right\", \"bottom\"))) +\n  tm_facets(ncol = 2) +\n  tm_layout(outer.margins = 0, asp = 0)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-19-1.png){width=1152}\n:::\n:::\n\n\n::: {.callout-warning}\n## Translating the tmap v3 code\n\nThree changes were needed for tmap 4.4. `tm_fill(col = ..., n = 5, style = \"jenks\", title = ...)` became `tm_polygons(fill = ..., fill.scale = tm_scale_intervals(style = \"jenks\", n = 5), fill.legend = tm_legend(title = ...))`. `tm_borders(alpha = 0.5)` became `tm_borders(col_alpha = 0.5)`, since a border is a line. `tm_legend(legend.position = ...)` was replaced by a position inside the `fill.legend` argument.\n:::\n\nThe course asks whether I can see the differences. The rate map breaks the link with size. Taunggyi, the largest township, drops to the fourth of five classes for `RADIO_PR`, and Lashio, the second largest, falls to the middle class at 236 per thousand. Small townships such as Mabein (8,632 households) and Monghpyak (6,165) move into the top class. The correlation between total households and `RADIO_PR` is only 0.34, which confirms that the rate measures something different from size.\n\n## Part 2, Correlation analysis\n\nCluster analysis treats each variable as a separate dimension. Two variables that carry almost the same information would count that information twice, so I checked the correlations between the six rates first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncluster_vars.cor = cor(ict_derived[,12:17])\ncorrplot.mixed(cluster_vars.cor,\n         lower = \"ellipse\", \n               upper = \"number\",\n               tl.pos = \"lt\",\n               diag = \"l\",\n               tl.col = \"black\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n`COMPUTER_PR` and `INTERNET_PR` have the strongest correlation, 0.87, so I keep only one of them. Following the notes, I keep `COMPUTER_PR`. The next highest pairs are `MPHONE_PR` with `COMPUTER_PR` at 0.74 and `TV_PR` with `MPHONE_PR` at 0.72. They are high but well below 0.87, and the notes keep all of them.\n\nRadio stands apart from the rest. Its correlation with the other rates ranges from -0.31 with land line phones to 0.24 with television. Radio is common in townships where the more modern items are rare, so it adds information the other variables do not have.\n\n## Part 3, Hierarchical cluster analysis\n\n### Extracting the clustering variables\n\nI dropped the geometry and kept the township name with the five clustering variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncluster_vars <- shan_sf %>%\n  st_set_geometry(NULL) %>%\n  select(\"TS.x\", \"RADIO_PR\", \"TV_PR\", \"LLPHONE_PR\", \"MPHONE_PR\", \"COMPUTER_PR\")\nhead(cluster_vars,10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        TS.x RADIO_PR    TV_PR LLPHONE_PR MPHONE_PR COMPUTER_PR\n1    Mongmit 286.1852 554.1313   35.30618  260.6944    12.15939\n2    Pindaya 417.4647 505.1300   19.83584  162.3917    12.88190\n3    Ywangan 484.5215 260.5734   11.93591  120.2856     4.41465\n4   Pinlaung 231.6499 541.7189   28.54454  249.4903    13.76255\n5     Mabein 449.4903 708.6423   72.75255  392.6089    16.45042\n6      Kalaw 280.7624 611.6204   42.06478  408.7951    29.63160\n7      Pekon 318.6118 535.8494   39.83270  214.8476    18.97032\n8   Lawksawk 387.1017 630.0035   31.51366  320.5686    21.76677\n9  Nawnghkio 349.3359 547.9456   38.44960  323.0201    15.76465\n10   Kyaukme 210.9548 601.1773   39.58267  372.4930    30.94709\n```\n\n\n:::\n:::\n\n\n`INTERNET_PR` is left out because of its correlation with `COMPUTER_PR`.\n\nThe clustering functions use row names as labels, so I replaced the row numbers with township names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrow.names(cluster_vars) <- cluster_vars$\"TS.x\"\nhead(cluster_vars,10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               TS.x RADIO_PR    TV_PR LLPHONE_PR MPHONE_PR COMPUTER_PR\nMongmit     Mongmit 286.1852 554.1313   35.30618  260.6944    12.15939\nPindaya     Pindaya 417.4647 505.1300   19.83584  162.3917    12.88190\nYwangan     Ywangan 484.5215 260.5734   11.93591  120.2856     4.41465\nPinlaung   Pinlaung 231.6499 541.7189   28.54454  249.4903    13.76255\nMabein       Mabein 449.4903 708.6423   72.75255  392.6089    16.45042\nKalaw         Kalaw 280.7624 611.6204   42.06478  408.7951    29.63160\nPekon         Pekon 318.6118 535.8494   39.83270  214.8476    18.97032\nLawksawk   Lawksawk 387.1017 630.0035   31.51366  320.5686    21.76677\nNawnghkio Nawnghkio 349.3359 547.9456   38.44960  323.0201    15.76465\nKyaukme     Kyaukme 210.9548 601.1773   39.58267  372.4930    30.94709\n```\n\n\n:::\n:::\n\n\nThen I dropped the `TS.x` column, since the name is now stored in the row names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict <- select(cluster_vars, c(2:6))\nhead(shan_ict, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          RADIO_PR    TV_PR LLPHONE_PR MPHONE_PR COMPUTER_PR\nMongmit   286.1852 554.1313   35.30618  260.6944    12.15939\nPindaya   417.4647 505.1300   19.83584  162.3917    12.88190\nYwangan   484.5215 260.5734   11.93591  120.2856     4.41465\nPinlaung  231.6499 541.7189   28.54454  249.4903    13.76255\nMabein    449.4903 708.6423   72.75255  392.6089    16.45042\nKalaw     280.7624 611.6204   42.06478  408.7951    29.63160\nPekon     318.6118 535.8494   39.83270  214.8476    18.97032\nLawksawk  387.1017 630.0035   31.51366  320.5686    21.76677\nNawnghkio 349.3359 547.9456   38.44960  323.0201    15.76465\nKyaukme   210.9548 601.1773   39.58267  372.4930    30.94709\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Saving shan_ict before reading it back\n\nThe notes read `shan_ict.rds` at this point but never write it. I added the `write_rds()` so the file exists before `read_rds()` loads it.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(shan_ict, \"data/rds/shan_ict.rds\")\nshan_ict <- read_rds(\"data/rds/shan_ict.rds\")\n```\n:::\n\n\n### Data standardisation\n\nThe five variables have very different ranges. Mobile phones run from 36 to 735 per thousand, and computers from 3 to 92. Without standardisation, a variable with a large range has more pull on the distances between townships. The notes show two ways to standardise.\n\n#### Min-max standardisation\n\n`normalize()` from **heatmaply** rescales each variable to run from 0 to 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict.std <- normalize(shan_ict)\nsummary(shan_ict.std)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    RADIO_PR          TV_PR          LLPHONE_PR       MPHONE_PR     \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.2544   1st Qu.:0.4600   1st Qu.:0.1123   1st Qu.:0.2199  \n Median :0.4097   Median :0.5523   Median :0.1948   Median :0.3846  \n Mean   :0.4199   Mean   :0.5416   Mean   :0.2703   Mean   :0.3972  \n 3rd Qu.:0.5330   3rd Qu.:0.6750   3rd Qu.:0.3746   3rd Qu.:0.5608  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n  COMPUTER_PR     \n Min.   :0.00000  \n 1st Qu.:0.09598  \n Median :0.17607  \n Mean   :0.23692  \n 3rd Qu.:0.29868  \n Max.   :1.00000  \n```\n\n\n:::\n:::\n\n\nEvery variable now has a minimum of 0 and a maximum of 1. The means differ, from 0.24 for `COMPUTER_PR` to 0.54 for `TV_PR`, because the shape of each distribution is kept.\n\n#### Z-score standardisation\n\n`scale()` subtracts the mean and divides by the standard deviation. I used `describe()` from **psych** instead of `summary()` because it reports the standard deviation as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict.z <- scale(shan_ict)\ndescribe(shan_ict.z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            vars  n mean sd median trimmed  mad   min  max range  skew kurtosis\nRADIO_PR       1 55    0  1  -0.04   -0.06 0.94 -1.85 2.55  4.40  0.48    -0.27\nTV_PR          2 55    0  1   0.05    0.04 0.78 -2.47 2.09  4.56 -0.38    -0.23\nLLPHONE_PR     3 55    0  1  -0.33   -0.15 0.68 -1.19 3.20  4.39  1.37     1.49\nMPHONE_PR      4 55    0  1  -0.05   -0.06 1.01 -1.58 2.40  3.98  0.48    -0.34\nCOMPUTER_PR    5 55    0  1  -0.26   -0.18 0.64 -1.03 3.31  4.34  1.80     2.96\n              se\nRADIO_PR    0.13\nTV_PR       0.13\nLLPHONE_PR  0.13\nMPHONE_PR   0.13\nCOMPUTER_PR 0.13\n```\n\n\n:::\n:::\n\n\nAll five variables now have a mean of 0 and a standard deviation of 1. The skewness values are the same as before standardisation, 1.80 for `COMPUTER_PR` and 1.37 for `LLPHONE_PR`.\n\n::: {.callout-tip}\n## When to use z-scores\n\nThe notes warn that z-scores should only be used if the variables can be assumed to come from a normal distribution. `COMPUTER_PR` and `LLPHONE_PR` are clearly skewed, so a z-score of 3 means something different for them than for `TV_PR`. Min-max scaling makes no such assumption, but a single extreme value squeezes everyone else into a narrow part of the 0 to 1 range.\n:::\n\n#### Visualising the standardised variables\n\nI compared the histogram of `RADIO_PR` before standardisation and after each method.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- ggplot(data=ict_derived, \n             aes(x= `RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\") +\n  ggtitle(\"Raw values without standardisation\")\n\nshan_ict_s_df <- as.data.frame(shan_ict.std)\ns <- ggplot(data=shan_ict_s_df, \n       aes(x=`RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\") +\n  ggtitle(\"Min-Max Standardisation\")\n\nshan_ict_z_df <- as.data.frame(shan_ict.z)\nz <- ggplot(data=shan_ict_z_df, \n       aes(x=`RADIO_PR`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\") +\n  ggtitle(\"Z-score Standardisation\")\n\nggarrange(r, s, z,\n          ncol = 3,\n          nrow = 1)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-27-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- ggplot(data=ict_derived, \n             aes(x= `RADIO_PR`)) +\n  geom_density(color=\"black\",\n               fill=\"light blue\") +\n  ggtitle(\"Raw values without standardisation\")\n\nshan_ict_s_df <- as.data.frame(shan_ict.std)\ns <- ggplot(data=shan_ict_s_df, \n       aes(x=`RADIO_PR`)) +\n  geom_density(color=\"black\",\n               fill=\"light blue\") +\n  ggtitle(\"Min-Max Standardisation\")\n\nshan_ict_z_df <- as.data.frame(shan_ict.z)\nz <- ggplot(data=shan_ict_z_df, \n       aes(x=`RADIO_PR`)) +\n  geom_density(color=\"black\",\n               fill=\"light blue\") +\n  ggtitle(\"Z-score Standardisation\")\n\nggarrange(r, s, z,\n          ncol = 3,\n          nrow = 1)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-28-1.png){width=1152}\n:::\n:::\n\n\nThe course asks what statistical conclusion the histograms support. The three panels have the same shape and differ only in the numbers on the x axis. Both methods are linear transformations, so they change the location and scale of a variable but not its skewness or the relative positions of the townships. Standardisation evens out the weight of each variable in the distance calculation, and it does not make a skewed variable normal.\n\n### Computing the proximity matrix\n\n`dist()` supports six distance measures, euclidean, maximum, manhattan, canberra, binary and minkowski, with euclidean as the default. I computed the euclidean distance between every pair of townships.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproxmat <- dist(shan_ict, method = 'euclidean')\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproxmat\n```\n:::\n\n\nThe printed matrix has 1,485 distances, one for each pair of the 55 townships, so I left it out of the rendered page.\n\n::: {.callout-warning}\n## The distances use the unstandardised values\n\nThe notes standardise the variables and then build `proxmat` from `shan_ict`, the raw rates. I followed the notes so that the results stay comparable, but I checked how much each variable contributes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(sapply(shan_ict, var) / sum(sapply(shan_ict, var)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   RADIO_PR       TV_PR  LLPHONE_PR   MPHONE_PR COMPUTER_PR \n      0.160       0.366       0.024       0.444       0.006 \n```\n\n\n:::\n:::\n\n\n`MPHONE_PR` and `TV_PR` together account for 81 percent of the total variance, and `COMPUTER_PR` for less than 1 percent. In the raw scale the clusters are mostly built from mobile phones and television. I come back to this at the end of Part 3.\n:::\n\n### Computing hierarchical clustering\n\n`hclust()` supports eight agglomeration methods, ward.D, ward.D2, single, complete, average (UPGMA), mcquitty (WPGMA), median (WPGMC) and centroid (UPGMC). Following the notes, I used ward.D.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhclust_ward <- hclust(proxmat, method = 'ward.D')\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hclust_ward, cex = 0.6)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-33-1.png){width=1152}\n:::\n:::\n\n\nThe tree has one very tall final merge at a height of about 4,336, which joins a group of 31 townships with a group of 24. Below that, the next merges happen at 1,820 and 1,443.\n\n### Selecting the optimal clustering algorithm\n\n`agnes()` from **cluster** works like `hclust()` but also returns the agglomerative coefficient. It measures how strong the clustering structure is, and values closer to 1 mean a stronger structure. I computed it for four methods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- c( \"average\", \"single\", \"complete\", \"ward\")\nnames(m) <- c( \"average\", \"single\", \"complete\", \"ward\")\n\nac <- function(x) {\n  agnes(shan_ict, method = x)$ac\n}\n\nmap_dbl(m, ac)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  average    single  complete      ward \n0.8131144 0.6628705 0.8950702 0.9427730 \n```\n\n\n:::\n:::\n\n\nWard's method has the highest coefficient at 0.943, ahead of complete linkage at 0.895, average at 0.813 and single linkage at 0.663. Single linkage chains townships one at a time, which gives the weakest structure. I use Ward's method from here on.\n\n### Determining the optimal number of clusters\n\nThe notes list three common methods for choosing the number of clusters, the elbow method, the average silhouette method and the gap statistic, and use the gap statistic.\n\n#### Gap statistic method\n\nThe gap statistic compares the within cluster variation for each k with the value expected from data with no cluster structure. The best k is the one with the largest gap. `clusGap()` from **cluster** computes it, and `hcut()` from **factoextra** does the hierarchical clustering inside each run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\ngap_stat <- clusGap(shan_ict, \n                    FUN = hcut, \n                    nstart = 25, \n                    K.max = 10, \n                    B = 50)\n# Print the result\nprint(gap_stat, method = \"firstmax\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nClustering Gap statistic [\"clusGap\"] from call:\nclusGap(x = shan_ict, FUNcluster = hcut, K.max = 10, B = 50, nstart = 25)\nB=50 simulated reference sets, k = 1..10; spaceH0=\"scaledPCA\"\n --> Number of clusters (method 'firstmax'): 1\n          logW   E.logW       gap     SE.sim\n [1,] 8.407129 8.680794 0.2736651 0.04460994\n [2,] 8.130029 8.350712 0.2206824 0.03880130\n [3,] 7.992265 8.202550 0.2102844 0.03362652\n [4,] 7.862224 8.080655 0.2184311 0.03784781\n [5,] 7.756461 7.978022 0.2215615 0.03897071\n [6,] 7.665594 7.887777 0.2221833 0.03973087\n [7,] 7.590919 7.806333 0.2154145 0.04054939\n [8,] 7.526680 7.731619 0.2049390 0.04198644\n [9,] 7.458024 7.660795 0.2027705 0.04421874\n[10,] 7.377412 7.593858 0.2164465 0.04540947\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfviz_gap_stat(gap_stat)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-36-1.png){width=768}\n:::\n:::\n\n\nThe largest gap is at k = 1 (0.274), so the statistic suggests the townships form one group. That is not useful for segmentation. Among k from 2 to 10, the largest gap is at k = 6 (0.2222), which is why the notes choose six clusters.\n\nThe choice of six is weak. The gap at k = 5 is 0.2216 and at k = 4 is 0.2184, both within 0.004 of k = 6, while the standard error for each is about 0.04. Any k from 4 to 6 fits the data about equally well. I keep six so that the rest of the results can be compared with the notes.\n\nThe notes also mention **NbClust**, which reports 30 indices for the number of clusters and proposes the best scheme across combinations of distance measures and clustering methods. The exercise does not run it.\n\n### Interpreting the dendrogram\n\nEach leaf of the dendrogram is one township. Similar townships are joined into branches lower down, and the height of a fusion shows how different the two groups are. Two townships can only be compared by the height at which their branches first join. Their positions along the horizontal axis say nothing about similarity.\n\n`rect.hclust()` draws boxes around the six clusters. The notes give `border = 2:5`, which has only four colours, so two clusters would reuse colours. I gave it six.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hclust_ward, cex = 0.6)\nrect.hclust(hclust_ward, \n            k = 6, \n            border = 2:7)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-37-1.png){width=1152}\n:::\n:::\n\n\n### Visually driven hierarchical clustering\n\n**heatmaply** combines the dendrogram with a heatmap of the variables, so the reason each township sits in its cluster can be read off the colours.\n\n#### Transforming the data frame into a matrix\n\n`heatmaply()` expects a matrix, so I converted the data frame first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_ict_mat <- data.matrix(shan_ict)\n```\n:::\n\n\n#### Plotting an interactive cluster heatmap\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheatmaply(normalize(shan_ict_mat),\n          Colv=NA,\n          dist_method = \"euclidean\",\n          hclust_method = \"ward.D\",\n          seriate = \"OLO\",\n          colors = Blues,\n          k_row = 6,\n          margins = c(NA,200,60,NA),\n          fontsize_row = 4,\n          fontsize_col = 5,\n          main=\"Geographic Segmentation of Shan State by ICT indicators\",\n          xlab = \"ICT Indicators\",\n          ylab = \"Townships of Shan State\"\n          )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-f547fdd7f7cb17180a7c\" style=\"width:100%;height:650px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f547fdd7f7cb17180a7c\">{\"x\":{\"data\":[{\"x\":[1,2,3,4,5],\"y\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55],\"z\":[[0.11697828280235656,0.12946800291670141,0.22051676674466952,0.3846139992017637,0],[0.1190714713575737,0.34509307535574651,0.14668071862261856,0.6891560112923748,0.030692309450180394],[0.44811294912657396,0.55225992411450087,0.10521568760008111,0.57412901426752871,0.48480739277474305],[0.39472652438726058,0.64647733866993595,0.19477119473094032,0.39801608135750716,0.30703392330347096],[0.40973860994388683,0.66778546258182536,0.20593962805229063,0.48078425480385861,0.3104572004100466],[0.56035905060769442,0.68216005320191508,0.21982898000630299,0.53271772917722882,0.29569694938338714],[0.50978351840105807,0.70584966248141379,0.23527761552998847,0.5657288162191596,0.18421714232785746],[0.44536782610845499,0.64847518658958281,0.4007253744967556,0.52572958435168671,0.32572766162209832],[0.30300632404660205,0.49147219082742094,0.39341363429136933,0.4349886836765729,0.25539117902522024],[0.28546056562312339,0.65316773418946461,0.3511299776298073,0.32190336940009312,0.2746837227301171],[0.18689649559375604,0.47362168694479917,0.17754710976751636,0.21901799211937109,0.21923803903390374],[0.2629488857600436,0.60093442055127599,0.10558868166123289,0.30984472139571101,0.32244406175045998],[0.34838456904687842,0.55041330721869519,0.013213311777657203,0.33060051526022322,0.28050502634682223],[0.37211615170496537,0.37496862114224933,0.12506080462855637,0.36350286192371328,0.20828663725058608],[0.38204908464317522,0.49529324375134881,0.16528121425607512,0.33285202942113173,0.12691106039033156],[0.3980907579303854,0.46773404772860855,0.16525192608338107,0.24827221676312536,0.12566331521633783],[0.46367507181173728,0.48027348971210537,0.049517603601854712,0.27845401411719362,0.10224025627189308],[0.45439139601376666,0.58594353490077877,0.14417252910969927,0.30481757278969496,0.11764114434607099],[0.57205942216261241,0.60302857970223533,0.18200927177224016,0.32084610041574091,0.099653220995087832],[0.64202483918062014,0.57786439014823898,0.20733874544122771,0.2552581189664615,0.17607405769543419],[0.46963701986480177,0.49275331606036005,0.33640390671869069,0.32646328563512589,0.19964300270472207],[0.47243757577103734,0.70830658131680169,0.18152892689938518,0.098196451325406497,0.18683697450666384],[0.48702182505931929,0.53618454590948406,0.16236928492310002,0.15547460469197441,0.074496310341376867],[0.53416314399345055,0.45576055674496141,0.10954853696695577,0.076155538926932026,0.10692577185093441],[0.43759029682306855,0.46420446143708183,0.11087478745786902,0.09844037585740166,0.0985978869506665],[0.45263667579662742,0.37779761401029388,0.11365549681498791,0.087769700588719066,0.064068575228978811],[0.31801152018301909,0.34169331569611694,0.098223180852338707,0.14121340016110578,0.068453570303467604],[0.3039056264611843,0.29573466001141135,0.12216142202890717,0.22079722888776726,0.09335763735596643],[0.12583937793228897,0.27166586954277672,0.14691293402953898,0.11190443691659302,0.040120375229698704],[0.16481813869170034,0.16307059912065375,0,0,0.050562923174397992],[0.29277803105512323,0,0.018020667308862742,0.020514689816836292,0.057341960293267435],[0.37385748377862454,0.099529007645666662,0.029599900644770458,0.026290069687093631,0.0041124401409408148],[0.48130384213362665,0.14229750653679712,0.031665051478322846,0.01257306399846167,0.030854020566575963],[1,0.19895816942596367,0.051234029774627314,0.11997847269980252,0.012754780873524383],[0.8553147780718825,0.53558029529267848,0.09544043782343907,0.18021510896887397,0.107759971325446],[0.78980219430668397,0.70746355636330893,0.16078708461582927,0.40650165146089307,0.20745103892822123],[0.65302227298916715,0.60351827743629827,0.090757204809061548,0.45032057879694432,0.13928686759144926],[0.70831666585604436,0.59451431070864036,0.19959920412341628,0.41000871240744075,0.14010534490572477],[0.82848163458094792,0.53309615033103497,0.22225304485480443,0.49414581896158,0.24532142669874679],[0.92441487443451942,0.81570663014131473,0.39155140729005755,0.50956182689641516,0.14779989677341526],[0.55458208226657446,0.85789929032177503,0.66700796483691616,0.41150185475720735,0.13518667681882074],[0.2176339803587421,0.65209843040106041,1,0.28778828469233325,0.19643775155383097],[0,0.23543567048956013,0.9321013544580421,0.40101556902451291,0.084421792656946576],[0.10937492963625832,0.6239421797955409,0.6220506320938376,0.6188729942182486,0.10736975492138895],[0.21361370528846507,0.54598018129684645,0.46285806565679205,0.55588313631466169,0.089979971244948997],[0.22989746208303394,0.60680342034724111,0.44188018109426463,0.64558140267074604,0.23838778070406411],[0.2458248117567654,0.73986922857984383,0.49811595358599009,0.80123060000032609,0.30165891030396325],[0.069496745754494604,0.91187904567993305,0.73626364575085579,0.97326830696953925,0.3621726080619882],[0.13189010662422904,0.76691504545610334,0.47117405530992845,0.74203095277732434,0.66556801662669474],[0.1648296584979817,0.51521670119868113,0.33457025472725271,0.57855734181793805,0.5290330349458493],[0.53176358126123557,0.71817785309851512,0.33811911213704343,0.64506885812542725,0.49665992351864235],[0.46321400984145478,0.77736794201940895,0.35759948327266128,0.61146312565581429,0.63887304429100666],[0.7427814502261707,0.87988241582281557,0.44075599890374501,0.78717895265256577,0.87397863437784384],[0.73856184642802991,0.88560203867754661,0.31880165558342549,1,1],[0.33405948053815493,1,0.76534529857384681,0.96780866955997513,0.98756611073781364]],\"text\":[[\"row: Narphan<br>column: RADIO_PR<br>value: 0.116978\",\"row: Narphan<br>column: TV_PR<br>value: 0.129468\",\"row: Narphan<br>column: LLPHONE_PR<br>value: 0.220517\",\"row: Narphan<br>column: MPHONE_PR<br>value: 0.384614\",\"row: Narphan<br>column: COMPUTER_PR<br>value: 0.000000\"],[\"row: Pangwaun<br>column: RADIO_PR<br>value: 0.119071\",\"row: Pangwaun<br>column: TV_PR<br>value: 0.345093\",\"row: Pangwaun<br>column: LLPHONE_PR<br>value: 0.146681\",\"row: Pangwaun<br>column: MPHONE_PR<br>value: 0.689156\",\"row: Pangwaun<br>column: COMPUTER_PR<br>value: 0.030692\"],[\"row: Mongpan<br>column: RADIO_PR<br>value: 0.448113\",\"row: Mongpan<br>column: TV_PR<br>value: 0.552260\",\"row: Mongpan<br>column: LLPHONE_PR<br>value: 0.105216\",\"row: Mongpan<br>column: MPHONE_PR<br>value: 0.574129\",\"row: Mongpan<br>column: COMPUTER_PR<br>value: 0.484807\"],[\"row: Nansang<br>column: RADIO_PR<br>value: 0.394727\",\"row: Nansang<br>column: TV_PR<br>value: 0.646477\",\"row: Nansang<br>column: LLPHONE_PR<br>value: 0.194771\",\"row: Nansang<br>column: MPHONE_PR<br>value: 0.398016\",\"row: Nansang<br>column: COMPUTER_PR<br>value: 0.307034\"],[\"row: Kyaukme<br>column: RADIO_PR<br>value: 0.409739\",\"row: Kyaukme<br>column: TV_PR<br>value: 0.667785\",\"row: Kyaukme<br>column: LLPHONE_PR<br>value: 0.205940\",\"row: Kyaukme<br>column: MPHONE_PR<br>value: 0.480784\",\"row: Kyaukme<br>column: COMPUTER_PR<br>value: 0.310457\"],[\"row: Kalaw<br>column: RADIO_PR<br>value: 0.560359\",\"row: Kalaw<br>column: TV_PR<br>value: 0.682160\",\"row: Kalaw<br>column: LLPHONE_PR<br>value: 0.219829\",\"row: Kalaw<br>column: MPHONE_PR<br>value: 0.532718\",\"row: Kalaw<br>column: COMPUTER_PR<br>value: 0.295697\"],[\"row: Hseni<br>column: RADIO_PR<br>value: 0.509784\",\"row: Hseni<br>column: TV_PR<br>value: 0.705850\",\"row: Hseni<br>column: LLPHONE_PR<br>value: 0.235278\",\"row: Hseni<br>column: MPHONE_PR<br>value: 0.565729\",\"row: Hseni<br>column: COMPUTER_PR<br>value: 0.184217\"],[\"row: Langkho<br>column: RADIO_PR<br>value: 0.445368\",\"row: Langkho<br>column: TV_PR<br>value: 0.648475\",\"row: Langkho<br>column: LLPHONE_PR<br>value: 0.400725\",\"row: Langkho<br>column: MPHONE_PR<br>value: 0.525730\",\"row: Langkho<br>column: COMPUTER_PR<br>value: 0.325728\"],[\"row: Kunhing<br>column: RADIO_PR<br>value: 0.303006\",\"row: Kunhing<br>column: TV_PR<br>value: 0.491472\",\"row: Kunhing<br>column: LLPHONE_PR<br>value: 0.393414\",\"row: Kunhing<br>column: MPHONE_PR<br>value: 0.434989\",\"row: Kunhing<br>column: COMPUTER_PR<br>value: 0.255391\"],[\"row: Laihka<br>column: RADIO_PR<br>value: 0.285461\",\"row: Laihka<br>column: TV_PR<br>value: 0.653168\",\"row: Laihka<br>column: LLPHONE_PR<br>value: 0.351130\",\"row: Laihka<br>column: MPHONE_PR<br>value: 0.321903\",\"row: Laihka<br>column: COMPUTER_PR<br>value: 0.274684\"],[\"row: Monghsat<br>column: RADIO_PR<br>value: 0.186896\",\"row: Monghsat<br>column: TV_PR<br>value: 0.473622\",\"row: Monghsat<br>column: LLPHONE_PR<br>value: 0.177547\",\"row: Monghsat<br>column: MPHONE_PR<br>value: 0.219018\",\"row: Monghsat<br>column: COMPUTER_PR<br>value: 0.219238\"],[\"row: Loilen<br>column: RADIO_PR<br>value: 0.262949\",\"row: Loilen<br>column: TV_PR<br>value: 0.600934\",\"row: Loilen<br>column: LLPHONE_PR<br>value: 0.105589\",\"row: Loilen<br>column: MPHONE_PR<br>value: 0.309845\",\"row: Loilen<br>column: COMPUTER_PR<br>value: 0.322444\"],[\"row: Mongnai<br>column: RADIO_PR<br>value: 0.348385\",\"row: Mongnai<br>column: TV_PR<br>value: 0.550413\",\"row: Mongnai<br>column: LLPHONE_PR<br>value: 0.013213\",\"row: Mongnai<br>column: MPHONE_PR<br>value: 0.330601\",\"row: Mongnai<br>column: COMPUTER_PR<br>value: 0.280505\"],[\"row: Mongton<br>column: RADIO_PR<br>value: 0.372116\",\"row: Mongton<br>column: TV_PR<br>value: 0.374969\",\"row: Mongton<br>column: LLPHONE_PR<br>value: 0.125061\",\"row: Mongton<br>column: MPHONE_PR<br>value: 0.363503\",\"row: Mongton<br>column: COMPUTER_PR<br>value: 0.208287\"],[\"row: Hsipaw<br>column: RADIO_PR<br>value: 0.382049\",\"row: Hsipaw<br>column: TV_PR<br>value: 0.495293\",\"row: Hsipaw<br>column: LLPHONE_PR<br>value: 0.165281\",\"row: Hsipaw<br>column: MPHONE_PR<br>value: 0.332852\",\"row: Hsipaw<br>column: COMPUTER_PR<br>value: 0.126911\"],[\"row: Hopong<br>column: RADIO_PR<br>value: 0.398091\",\"row: Hopong<br>column: TV_PR<br>value: 0.467734\",\"row: Hopong<br>column: LLPHONE_PR<br>value: 0.165252\",\"row: Hopong<br>column: MPHONE_PR<br>value: 0.248272\",\"row: Hopong<br>column: COMPUTER_PR<br>value: 0.125663\"],[\"row: Monghsu<br>column: RADIO_PR<br>value: 0.463675\",\"row: Monghsu<br>column: TV_PR<br>value: 0.480273\",\"row: Monghsu<br>column: LLPHONE_PR<br>value: 0.049518\",\"row: Monghsu<br>column: MPHONE_PR<br>value: 0.278454\",\"row: Monghsu<br>column: COMPUTER_PR<br>value: 0.102240\"],[\"row: Pinlaung<br>column: RADIO_PR<br>value: 0.454391\",\"row: Pinlaung<br>column: TV_PR<br>value: 0.585944\",\"row: Pinlaung<br>column: LLPHONE_PR<br>value: 0.144173\",\"row: Pinlaung<br>column: MPHONE_PR<br>value: 0.304818\",\"row: Pinlaung<br>column: COMPUTER_PR<br>value: 0.117641\"],[\"row: Mongmit<br>column: RADIO_PR<br>value: 0.572059\",\"row: Mongmit<br>column: TV_PR<br>value: 0.603029\",\"row: Mongmit<br>column: LLPHONE_PR<br>value: 0.182009\",\"row: Mongmit<br>column: MPHONE_PR<br>value: 0.320846\",\"row: Mongmit<br>column: COMPUTER_PR<br>value: 0.099653\"],[\"row: Pekon<br>column: RADIO_PR<br>value: 0.642025\",\"row: Pekon<br>column: TV_PR<br>value: 0.577864\",\"row: Pekon<br>column: LLPHONE_PR<br>value: 0.207339\",\"row: Pekon<br>column: MPHONE_PR<br>value: 0.255258\",\"row: Pekon<br>column: COMPUTER_PR<br>value: 0.176074\"],[\"row: Kutkai<br>column: RADIO_PR<br>value: 0.469637\",\"row: Kutkai<br>column: TV_PR<br>value: 0.492753\",\"row: Kutkai<br>column: LLPHONE_PR<br>value: 0.336404\",\"row: Kutkai<br>column: MPHONE_PR<br>value: 0.326463\",\"row: Kutkai<br>column: COMPUTER_PR<br>value: 0.199643\"],[\"row: Namtu<br>column: RADIO_PR<br>value: 0.472438\",\"row: Namtu<br>column: TV_PR<br>value: 0.708307\",\"row: Namtu<br>column: LLPHONE_PR<br>value: 0.181529\",\"row: Namtu<br>column: MPHONE_PR<br>value: 0.098196\",\"row: Namtu<br>column: COMPUTER_PR<br>value: 0.186837\"],[\"row: Hsihseng<br>column: RADIO_PR<br>value: 0.487022\",\"row: Hsihseng<br>column: TV_PR<br>value: 0.536185\",\"row: Hsihseng<br>column: LLPHONE_PR<br>value: 0.162369\",\"row: Hsihseng<br>column: MPHONE_PR<br>value: 0.155475\",\"row: Hsihseng<br>column: COMPUTER_PR<br>value: 0.074496\"],[\"row: Kyethi<br>column: RADIO_PR<br>value: 0.534163\",\"row: Kyethi<br>column: TV_PR<br>value: 0.455761\",\"row: Kyethi<br>column: LLPHONE_PR<br>value: 0.109549\",\"row: Kyethi<br>column: MPHONE_PR<br>value: 0.076156\",\"row: Kyethi<br>column: COMPUTER_PR<br>value: 0.106926\"],[\"row: Tangyan<br>column: RADIO_PR<br>value: 0.437590\",\"row: Tangyan<br>column: TV_PR<br>value: 0.464204\",\"row: Tangyan<br>column: LLPHONE_PR<br>value: 0.110875\",\"row: Tangyan<br>column: MPHONE_PR<br>value: 0.098440\",\"row: Tangyan<br>column: COMPUTER_PR<br>value: 0.098598\"],[\"row: Namhsan<br>column: RADIO_PR<br>value: 0.452637\",\"row: Namhsan<br>column: TV_PR<br>value: 0.377798\",\"row: Namhsan<br>column: LLPHONE_PR<br>value: 0.113655\",\"row: Namhsan<br>column: MPHONE_PR<br>value: 0.087770\",\"row: Namhsan<br>column: COMPUTER_PR<br>value: 0.064069\"],[\"row: Mongyai<br>column: RADIO_PR<br>value: 0.318012\",\"row: Mongyai<br>column: TV_PR<br>value: 0.341693\",\"row: Mongyai<br>column: LLPHONE_PR<br>value: 0.098223\",\"row: Mongyai<br>column: MPHONE_PR<br>value: 0.141213\",\"row: Mongyai<br>column: COMPUTER_PR<br>value: 0.068454\"],[\"row: Mongping<br>column: RADIO_PR<br>value: 0.303906\",\"row: Mongping<br>column: TV_PR<br>value: 0.295735\",\"row: Mongping<br>column: LLPHONE_PR<br>value: 0.122161\",\"row: Mongping<br>column: MPHONE_PR<br>value: 0.220797\",\"row: Mongping<br>column: COMPUTER_PR<br>value: 0.093358\"],[\"row: Mongkhet<br>column: RADIO_PR<br>value: 0.125839\",\"row: Mongkhet<br>column: TV_PR<br>value: 0.271666\",\"row: Mongkhet<br>column: LLPHONE_PR<br>value: 0.146913\",\"row: Mongkhet<br>column: MPHONE_PR<br>value: 0.111904\",\"row: Mongkhet<br>column: COMPUTER_PR<br>value: 0.040120\"],[\"row: Mawkmai<br>column: RADIO_PR<br>value: 0.164818\",\"row: Mawkmai<br>column: TV_PR<br>value: 0.163071\",\"row: Mawkmai<br>column: LLPHONE_PR<br>value: 0.000000\",\"row: Mawkmai<br>column: MPHONE_PR<br>value: 0.000000\",\"row: Mawkmai<br>column: COMPUTER_PR<br>value: 0.050563\"],[\"row: Mongkaing<br>column: RADIO_PR<br>value: 0.292778\",\"row: Mongkaing<br>column: TV_PR<br>value: 0.000000\",\"row: Mongkaing<br>column: LLPHONE_PR<br>value: 0.018021\",\"row: Mongkaing<br>column: MPHONE_PR<br>value: 0.020515\",\"row: Mongkaing<br>column: COMPUTER_PR<br>value: 0.057342\"],[\"row: Manton<br>column: RADIO_PR<br>value: 0.373857\",\"row: Manton<br>column: TV_PR<br>value: 0.099529\",\"row: Manton<br>column: LLPHONE_PR<br>value: 0.029600\",\"row: Manton<br>column: MPHONE_PR<br>value: 0.026290\",\"row: Manton<br>column: COMPUTER_PR<br>value: 0.004112\"],[\"row: Matman<br>column: RADIO_PR<br>value: 0.481304\",\"row: Matman<br>column: TV_PR<br>value: 0.142298\",\"row: Matman<br>column: LLPHONE_PR<br>value: 0.031665\",\"row: Matman<br>column: MPHONE_PR<br>value: 0.012573\",\"row: Matman<br>column: COMPUTER_PR<br>value: 0.030854\"],[\"row: Ywangan<br>column: RADIO_PR<br>value: 1.000000\",\"row: Ywangan<br>column: TV_PR<br>value: 0.198958\",\"row: Ywangan<br>column: LLPHONE_PR<br>value: 0.051234\",\"row: Ywangan<br>column: MPHONE_PR<br>value: 0.119978\",\"row: Ywangan<br>column: COMPUTER_PR<br>value: 0.012755\"],[\"row: Pindaya<br>column: RADIO_PR<br>value: 0.855315\",\"row: Pindaya<br>column: TV_PR<br>value: 0.535580\",\"row: Pindaya<br>column: LLPHONE_PR<br>value: 0.095440\",\"row: Pindaya<br>column: MPHONE_PR<br>value: 0.180215\",\"row: Pindaya<br>column: COMPUTER_PR<br>value: 0.107760\"],[\"row: Lawksawk<br>column: RADIO_PR<br>value: 0.789802\",\"row: Lawksawk<br>column: TV_PR<br>value: 0.707464\",\"row: Lawksawk<br>column: LLPHONE_PR<br>value: 0.160787\",\"row: Lawksawk<br>column: MPHONE_PR<br>value: 0.406502\",\"row: Lawksawk<br>column: COMPUTER_PR<br>value: 0.207451\"],[\"row: Nyaungshwe<br>column: RADIO_PR<br>value: 0.653022\",\"row: Nyaungshwe<br>column: TV_PR<br>value: 0.603518\",\"row: Nyaungshwe<br>column: LLPHONE_PR<br>value: 0.090757\",\"row: Nyaungshwe<br>column: MPHONE_PR<br>value: 0.450321\",\"row: Nyaungshwe<br>column: COMPUTER_PR<br>value: 0.139287\"],[\"row: Nawnghkio<br>column: RADIO_PR<br>value: 0.708317\",\"row: Nawnghkio<br>column: TV_PR<br>value: 0.594514\",\"row: Nawnghkio<br>column: LLPHONE_PR<br>value: 0.199599\",\"row: Nawnghkio<br>column: MPHONE_PR<br>value: 0.410009\",\"row: Nawnghkio<br>column: COMPUTER_PR<br>value: 0.140105\"],[\"row: Monghpyak<br>column: RADIO_PR<br>value: 0.828482\",\"row: Monghpyak<br>column: TV_PR<br>value: 0.533096\",\"row: Monghpyak<br>column: LLPHONE_PR<br>value: 0.222253\",\"row: Monghpyak<br>column: MPHONE_PR<br>value: 0.494146\",\"row: Monghpyak<br>column: COMPUTER_PR<br>value: 0.245321\"],[\"row: Mabein<br>column: RADIO_PR<br>value: 0.924415\",\"row: Mabein<br>column: TV_PR<br>value: 0.815707\",\"row: Mabein<br>column: LLPHONE_PR<br>value: 0.391551\",\"row: Mabein<br>column: MPHONE_PR<br>value: 0.509562\",\"row: Mabein<br>column: COMPUTER_PR<br>value: 0.147800\"],[\"row: Mongyawng<br>column: RADIO_PR<br>value: 0.554582\",\"row: Mongyawng<br>column: TV_PR<br>value: 0.857899\",\"row: Mongyawng<br>column: LLPHONE_PR<br>value: 0.667008\",\"row: Mongyawng<br>column: MPHONE_PR<br>value: 0.411502\",\"row: Mongyawng<br>column: COMPUTER_PR<br>value: 0.135187\"],[\"row: Kunlong<br>column: RADIO_PR<br>value: 0.217634\",\"row: Kunlong<br>column: TV_PR<br>value: 0.652098\",\"row: Kunlong<br>column: LLPHONE_PR<br>value: 1.000000\",\"row: Kunlong<br>column: MPHONE_PR<br>value: 0.287788\",\"row: Kunlong<br>column: COMPUTER_PR<br>value: 0.196438\"],[\"row: Konkyan<br>column: RADIO_PR<br>value: 0.000000\",\"row: Konkyan<br>column: TV_PR<br>value: 0.235436\",\"row: Konkyan<br>column: LLPHONE_PR<br>value: 0.932101\",\"row: Konkyan<br>column: MPHONE_PR<br>value: 0.401016\",\"row: Konkyan<br>column: COMPUTER_PR<br>value: 0.084422\"],[\"row: Mongyang<br>column: RADIO_PR<br>value: 0.109375\",\"row: Mongyang<br>column: TV_PR<br>value: 0.623942\",\"row: Mongyang<br>column: LLPHONE_PR<br>value: 0.622051\",\"row: Mongyang<br>column: MPHONE_PR<br>value: 0.618873\",\"row: Mongyang<br>column: COMPUTER_PR<br>value: 0.107370\"],[\"row: Mongmao<br>column: RADIO_PR<br>value: 0.213614\",\"row: Mongmao<br>column: TV_PR<br>value: 0.545980\",\"row: Mongmao<br>column: LLPHONE_PR<br>value: 0.462858\",\"row: Mongmao<br>column: MPHONE_PR<br>value: 0.555883\",\"row: Mongmao<br>column: COMPUTER_PR<br>value: 0.089980\"],[\"row: Hopang<br>column: RADIO_PR<br>value: 0.229897\",\"row: Hopang<br>column: TV_PR<br>value: 0.606803\",\"row: Hopang<br>column: LLPHONE_PR<br>value: 0.441880\",\"row: Hopang<br>column: MPHONE_PR<br>value: 0.645581\",\"row: Hopang<br>column: COMPUTER_PR<br>value: 0.238388\"],[\"row: Namhkan<br>column: RADIO_PR<br>value: 0.245825\",\"row: Namhkan<br>column: TV_PR<br>value: 0.739869\",\"row: Namhkan<br>column: LLPHONE_PR<br>value: 0.498116\",\"row: Namhkan<br>column: MPHONE_PR<br>value: 0.801231\",\"row: Namhkan<br>column: COMPUTER_PR<br>value: 0.301659\"],[\"row: Laukkaing<br>column: RADIO_PR<br>value: 0.069497\",\"row: Laukkaing<br>column: TV_PR<br>value: 0.911879\",\"row: Laukkaing<br>column: LLPHONE_PR<br>value: 0.736264\",\"row: Laukkaing<br>column: MPHONE_PR<br>value: 0.973268\",\"row: Laukkaing<br>column: COMPUTER_PR<br>value: 0.362173\"],[\"row: Mongla<br>column: RADIO_PR<br>value: 0.131890\",\"row: Mongla<br>column: TV_PR<br>value: 0.766915\",\"row: Mongla<br>column: LLPHONE_PR<br>value: 0.471174\",\"row: Mongla<br>column: MPHONE_PR<br>value: 0.742031\",\"row: Mongla<br>column: COMPUTER_PR<br>value: 0.665568\"],[\"row: Pangsang<br>column: RADIO_PR<br>value: 0.164830\",\"row: Pangsang<br>column: TV_PR<br>value: 0.515217\",\"row: Pangsang<br>column: LLPHONE_PR<br>value: 0.334570\",\"row: Pangsang<br>column: MPHONE_PR<br>value: 0.578557\",\"row: Pangsang<br>column: COMPUTER_PR<br>value: 0.529033\"],[\"row: Kengtung<br>column: RADIO_PR<br>value: 0.531764\",\"row: Kengtung<br>column: TV_PR<br>value: 0.718178\",\"row: Kengtung<br>column: LLPHONE_PR<br>value: 0.338119\",\"row: Kengtung<br>column: MPHONE_PR<br>value: 0.645069\",\"row: Kengtung<br>column: COMPUTER_PR<br>value: 0.496660\"],[\"row: Lashio<br>column: RADIO_PR<br>value: 0.463214\",\"row: Lashio<br>column: TV_PR<br>value: 0.777368\",\"row: Lashio<br>column: LLPHONE_PR<br>value: 0.357599\",\"row: Lashio<br>column: MPHONE_PR<br>value: 0.611463\",\"row: Lashio<br>column: COMPUTER_PR<br>value: 0.638873\"],[\"row: Taunggyi<br>column: RADIO_PR<br>value: 0.742781\",\"row: Taunggyi<br>column: TV_PR<br>value: 0.879882\",\"row: Taunggyi<br>column: LLPHONE_PR<br>value: 0.440756\",\"row: Taunggyi<br>column: MPHONE_PR<br>value: 0.787179\",\"row: Taunggyi<br>column: COMPUTER_PR<br>value: 0.873979\"],[\"row: Tachileik<br>column: RADIO_PR<br>value: 0.738562\",\"row: Tachileik<br>column: TV_PR<br>value: 0.885602\",\"row: Tachileik<br>column: LLPHONE_PR<br>value: 0.318802\",\"row: Tachileik<br>column: MPHONE_PR<br>value: 1.000000\",\"row: Tachileik<br>column: COMPUTER_PR<br>value: 1.000000\"],[\"row: Muse<br>column: RADIO_PR<br>value: 0.334059\",\"row: Muse<br>column: TV_PR<br>value: 1.000000\",\"row: Muse<br>column: LLPHONE_PR<br>value: 0.765345\",\"row: Muse<br>column: MPHONE_PR<br>value: 0.967809\",\"row: Muse<br>column: COMPUTER_PR<br>value: 0.987566\"]],\"colorscale\":[[0,\"#F7FBFF\"],[0.0041124401409408148,\"#F6FAFE\"],[0.01257306399846167,\"#F4F9FE\"],[0.012754780873524383,\"#F4F9FE\"],[0.013213311777657203,\"#F4F9FE\"],[0.018020667308862742,\"#F3F8FD\"],[0.020514689816836292,\"#F3F8FD\"],[0.026290069687093631,\"#F1F7FD\"],[0.029599900644770458,\"#F0F6FC\"],[0.030692309450180394,\"#F0F6FC\"],[0.030854020566575963,\"#F0F6FC\"],[0.031665051478322846,\"#F0F6FC\"],[0.040120375229698704,\"#EFF5FC\"],[0.049517603601854712,\"#ECF4FB\"],[0.050562923174397992,\"#ECF4FB\"],[0.051234029774627314,\"#ECF4FB\"],[0.057341960293267435,\"#EBF3FB\"],[0.064068575228978811,\"#EAF2FA\"],[0.068453570303467604,\"#E9F2FA\"],[0.069496745754494604,\"#E8F1FA\"],[0.074496310341376867,\"#E8F1FA\"],[0.076155538926932026,\"#E8F1FA\"],[0.084421792656946576,\"#E5EFF9\"],[0.087769700588719066,\"#E5EFF9\"],[0.089979971244948997,\"#E4EFF9\"],[0.090757204809061548,\"#E4EFF9\"],[0.09335763735596643,\"#E4EEF8\"],[0.09544043782343907,\"#E4EEF8\"],[0.098196451325406497,\"#E3EEF8\"],[0.098223180852338707,\"#E3EEF8\"],[0.09844037585740166,\"#E3EEF8\"],[0.0985978869506665,\"#E3EEF8\"],[0.099529007645666662,\"#E3EEF8\"],[0.099653220995087832,\"#E3EEF8\"],[0.10224025627189308,\"#E2EDF8\"],[0.10521568760008111,\"#E1EDF8\"],[0.10558868166123289,\"#E1EDF8\"],[0.10692577185093441,\"#E1EDF8\"],[0.10736975492138895,\"#E1EDF8\"],[0.107759971325446,\"#E1EDF8\"],[0.10937492963625832,\"#E1ECF7\"],[0.10954853696695577,\"#E1ECF7\"],[0.11087478745786902,\"#E1ECF7\"],[0.11190443691659302,\"#E0ECF7\"],[0.11365549681498791,\"#E0ECF7\"],[0.11697828280235656,\"#DFEBF7\"],[0.11764114434607099,\"#DFEBF7\"],[0.1190714713575737,\"#DFEBF7\"],[0.11997847269980252,\"#DEEBF7\"],[0.12216142202890717,\"#DEEBF7\"],[0.12506080462855637,\"#DDEAF6\"],[0.12566331521633783,\"#DDEAF6\"],[0.12583937793228897,\"#DDEAF6\"],[0.12691106039033156,\"#DDEAF6\"],[0.12946800291670141,\"#DDEAF6\"],[0.13189010662422904,\"#DCE9F6\"],[0.13518667681882074,\"#DCE9F6\"],[0.13928686759144926,\"#DAE8F5\"],[0.14010534490572477,\"#DAE8F5\"],[0.14121340016110578,\"#DAE8F5\"],[0.14229750653679712,\"#DAE8F5\"],[0.14417252910969927,\"#DAE8F5\"],[0.14668071862261856,\"#DAE8F5\"],[0.14691293402953898,\"#DAE8F5\"],[0.14779989677341526,\"#D9E7F5\"],[0.15547460469197441,\"#D7E6F4\"],[0.16078708461582927,\"#D7E6F4\"],[0.16236928492310002,\"#D7E6F4\"],[0.16307059912065375,\"#D6E5F4\"],[0.16481813869170034,\"#D6E5F4\"],[0.1648296584979817,\"#D6E5F4\"],[0.16525192608338107,\"#D6E5F4\"],[0.16528121425607512,\"#D6E5F4\"],[0.17607405769543419,\"#D4E4F3\"],[0.17754710976751636,\"#D4E4F3\"],[0.18021510896887397,\"#D3E3F3\"],[0.18152892689938518,\"#D3E3F3\"],[0.18200927177224016,\"#D3E3F3\"],[0.18421714232785746,\"#D2E3F3\"],[0.18683697450666384,\"#D1E2F2\"],[0.18689649559375604,\"#D1E2F2\"],[0.19477119473094032,\"#D0E1F2\"],[0.19643775155383097,\"#D0E1F2\"],[0.19895816942596367,\"#CFE1F2\"],[0.19959920412341628,\"#CFE1F2\"],[0.19964300270472207,\"#CFE1F2\"],[0.20593962805229063,\"#CEE0F1\"],[0.20733874544122771,\"#CEE0F1\"],[0.20745103892822123,\"#CEE0F1\"],[0.20828663725058608,\"#CEE0F1\"],[0.21361370528846507,\"#CDDFF1\"],[0.2176339803587421,\"#CCDFF1\"],[0.21901799211937109,\"#CBDEF0\"],[0.21923803903390374,\"#CBDEF0\"],[0.21982898000630299,\"#CBDEF0\"],[0.22051676674466952,\"#CBDEF0\"],[0.22079722888776726,\"#CBDEF0\"],[0.22225304485480443,\"#CBDEF0\"],[0.22989746208303394,\"#C9DDF0\"],[0.23527761552998847,\"#C8DCEF\"],[0.23543567048956013,\"#C8DCEF\"],[0.23838778070406411,\"#C8DCEF\"],[0.24532142669874679,\"#C6DBEF\"],[0.2458248117567654,\"#C6DBEF\"],[0.24827221676312536,\"#C6DBEF\"],[0.2552581189664615,\"#C4DAEE\"],[0.25539117902522024,\"#C4DAEE\"],[0.2629488857600436,\"#C1D9ED\"],[0.27166586954277672,\"#BFD8EC\"],[0.2746837227301171,\"#BED7EC\"],[0.27845401411719362,\"#BCD7EB\"],[0.28050502634682223,\"#BBD6EB\"],[0.28546056562312339,\"#BAD6EA\"],[0.28778828469233325,\"#BAD6EA\"],[0.29277803105512323,\"#B8D4EA\"],[0.29569694938338714,\"#B7D4EA\"],[0.29573466001141135,\"#B7D4EA\"],[0.30165891030396325,\"#B5D3E9\"],[0.30300632404660205,\"#B5D3E9\"],[0.3039056264611843,\"#B5D3E9\"],[0.30481757278969496,\"#B4D3E8\"],[0.30703392330347096,\"#B3D3E8\"],[0.30984472139571101,\"#B2D2E8\"],[0.3104572004100466,\"#B2D2E8\"],[0.31801152018301909,\"#B0D1E7\"],[0.31880165558342549,\"#B0D1E7\"],[0.32084610041574091,\"#AFD1E6\"],[0.32190336940009312,\"#AFD1E6\"],[0.32244406175045998,\"#AFD1E6\"],[0.32572766162209832,\"#ADD0E6\"],[0.32646328563512589,\"#ADD0E6\"],[0.33060051526022322,\"#ACD0E6\"],[0.33285202942113173,\"#ABCFE5\"],[0.33405948053815493,\"#ABCFE5\"],[0.33457025472725271,\"#ABCFE5\"],[0.33640390671869069,\"#AACFE5\"],[0.33811911213704343,\"#AACFE5\"],[0.34169331569611694,\"#A8CEE4\"],[0.34509307535574651,\"#A7CEE4\"],[0.34838456904687842,\"#A6CDE3\"],[0.3511299776298073,\"#A5CDE3\"],[0.35759948327266128,\"#A3CCE3\"],[0.3621726080619882,\"#A2CBE2\"],[0.36350286192371328,\"#A1CBE2\"],[0.37211615170496537,\"#9ECAE1\"],[0.37385748377862454,\"#9ECAE1\"],[0.37496862114224933,\"#9DC9E0\"],[0.37779761401029388,\"#9CC9E0\"],[0.38204908464317522,\"#9BC8E0\"],[0.3846139992017637,\"#9AC7E0\"],[0.39155140729005755,\"#97C6DF\"],[0.39341363429136933,\"#96C6DF\"],[0.39472652438726058,\"#96C5DF\"],[0.39801608135750716,\"#94C5DF\"],[0.3980907579303854,\"#94C4DE\"],[0.4007253744967556,\"#93C4DE\"],[0.40101556902451291,\"#93C4DE\"],[0.40650165146089307,\"#91C2DE\"],[0.40973860994388683,\"#90C2DE\"],[0.41000871240744075,\"#8FC1DD\"],[0.41150185475720735,\"#8FC1DD\"],[0.4349886836765729,\"#85BCDB\"],[0.43759029682306855,\"#84BBDB\"],[0.44075599890374501,\"#83BBDB\"],[0.44188018109426463,\"#82BADB\"],[0.44536782610845499,\"#81B9DA\"],[0.44811294912657396,\"#80B9DA\"],[0.45032057879694432,\"#7FB8DA\"],[0.45263667579662742,\"#7EB8DA\"],[0.45439139601376666,\"#7DB8D9\"],[0.45576055674496141,\"#7DB8D9\"],[0.46285806565679205,\"#7AB6D9\"],[0.46321400984145478,\"#7AB6D9\"],[0.46367507181173728,\"#7AB6D9\"],[0.46420446143708183,\"#79B6D9\"],[0.46773404772860855,\"#78B5D8\"],[0.46963701986480177,\"#77B4D8\"],[0.47117405530992845,\"#77B4D8\"],[0.47243757577103734,\"#76B4D8\"],[0.47362168694479917,\"#75B3D8\"],[0.48027348971210537,\"#73B2D7\"],[0.48078425480385861,\"#72B1D7\"],[0.48130384213362665,\"#72B1D7\"],[0.48480739277474305,\"#71B1D7\"],[0.48702182505931929,\"#70B1D7\"],[0.49147219082742094,\"#6EB0D6\"],[0.49275331606036005,\"#6EAFD6\"],[0.49414581896158,\"#6DAFD6\"],[0.49529324375134881,\"#6CAFD6\"],[0.49665992351864235,\"#6CAED6\"],[0.49811595358599009,\"#6BAED6\"],[0.50956182689641516,\"#67ABD4\"],[0.50978351840105807,\"#67ABD4\"],[0.51521670119868113,\"#66AAD4\"],[0.52572958435168671,\"#62A8D2\"],[0.5290330349458493,\"#61A7D2\"],[0.53176358126123557,\"#60A6D1\"],[0.53271772917722882,\"#60A6D1\"],[0.53309615033103497,\"#60A6D1\"],[0.53416314399345055,\"#60A6D1\"],[0.53558029529267848,\"#5FA5D1\"],[0.53618454590948406,\"#5FA5D1\"],[0.54598018129684645,\"#5CA3D0\"],[0.55041330721869519,\"#5AA3CF\"],[0.55225992411450087,\"#59A2CF\"],[0.55458208226657446,\"#59A2CF\"],[0.55588313631466169,\"#58A1CE\"],[0.56035905060769442,\"#57A0CE\"],[0.5657288162191596,\"#559FCD\"],[0.57205942216261241,\"#539DCC\"],[0.57412901426752871,\"#529DCC\"],[0.57786439014823898,\"#519CCC\"],[0.57855734181793805,\"#509BCB\"],[0.58594353490077877,\"#4F9BCB\"],[0.59451431070864036,\"#4B98C9\"],[0.60093442055127599,\"#4A97C9\"],[0.60302857970223533,\"#4896C8\"],[0.60351827743629827,\"#4896C8\"],[0.60680342034724111,\"#4795C8\"],[0.61146312565581429,\"#4694C7\"],[0.6188729942182486,\"#4393C6\"],[0.6220506320938376,\"#4292C6\"],[0.6239421797955409,\"#4292C6\"],[0.63887304429100666,\"#3E8EC4\"],[0.64202483918062014,\"#3D8DC3\"],[0.64506885812542725,\"#3D8DC3\"],[0.64558140267074604,\"#3C8CC3\"],[0.64647733866993595,\"#3C8CC3\"],[0.64847518658958281,\"#3C8CC3\"],[0.65209843040106041,\"#3B8BC2\"],[0.65302227298916715,\"#3A8AC1\"],[0.65316773418946461,\"#3A8AC1\"],[0.66556801662669474,\"#3787C0\"],[0.66700796483691616,\"#3787C0\"],[0.66778546258182536,\"#3686C0\"],[0.68216005320191508,\"#3282BE\"],[0.6891560112923748,\"#3080BD\"],[0.70584966248141379,\"#2C7CBB\"],[0.70746355636330893,\"#2C7CBB\"],[0.70830658131680169,\"#2B7BBA\"],[0.70831666585604436,\"#2B7BBA\"],[0.71817785309851512,\"#2979B9\"],[0.73626364575085579,\"#2474B6\"],[0.73856184642802991,\"#2474B6\"],[0.73986922857984383,\"#2373B6\"],[0.74203095277732434,\"#2373B6\"],[0.7427814502261707,\"#2373B6\"],[0.76534529857384681,\"#1E6DB2\"],[0.76691504545610334,\"#1D6CB1\"],[0.77736794201940895,\"#1B6AAF\"],[0.78717895265256577,\"#1967AD\"],[0.78980219430668397,\"#1967AD\"],[0.80123060000032609,\"#1664AB\"],[0.81570663014131473,\"#1360A7\"],[0.82848163458094792,\"#115DA5\"],[0.8553147780718825,\"#0C56A0\"],[0.85789929032177503,\"#0B559F\"],[0.87397863437784384,\"#08519C\"],[0.87988241582281557,\"#08509A\"],[0.88560203867754661,\"#084E97\"],[0.91187904567993305,\"#08468D\"],[0.92441487443451942,\"#084388\"],[0.9321013544580421,\"#084185\"],[0.96780866955997513,\"#083877\"],[0.97326830696953925,\"#083775\"],[0.98756611073781364,\"#08336F\"],[1,\"#08306B\"]],\"type\":\"heatmap\",\"showscale\":false,\"autocolorscale\":false,\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1],\"y\":[1],\"name\":\"607f1118d01e33e68f1d9c1301f660bd\",\"type\":\"scatter\",\"mode\":\"markers\",\"opacity\":0,\"hoverinfo\":\"skip\",\"showlegend\":false,\"marker\":{\"color\":[0,1],\"colorscale\":[[0,\"#F7FBFF\"],[0.0033444816053511705,\"#F6FAFE\"],[0.006688963210702341,\"#F5F9FE\"],[0.010033444816053512,\"#F4F9FE\"],[0.013377926421404682,\"#F4F9FE\"],[0.016722408026755852,\"#F3F8FD\"],[0.020066889632107024,\"#F3F8FD\"],[0.023411371237458192,\"#F2F7FD\"],[0.026755852842809364,\"#F1F7FD\"],[0.030100334448160536,\"#F0F6FC\"],[0.033444816053511704,\"#EFF6FC\"],[0.036789297658862873,\"#EFF6FC\"],[0.040133779264214048,\"#EFF5FC\"],[0.043478260869565216,\"#EEF5FC\"],[0.046822742474916385,\"#EDF4FB\"],[0.05016722408026756,\"#ECF4FB\"],[0.053511705685618728,\"#ECF3FB\"],[0.056856187290969896,\"#ECF3FB\"],[0.060200668896321072,\"#EBF3FB\"],[0.06354515050167224,\"#EAF2FA\"],[0.066889632107023408,\"#E9F2FA\"],[0.070234113712374577,\"#E8F1FA\"],[0.073578595317725745,\"#E8F1FA\"],[0.076923076923076927,\"#E7F0F9\"],[0.080267558528428096,\"#E7F0F9\"],[0.083612040133779264,\"#E6F0F9\"],[0.086956521739130432,\"#E5EFF9\"],[0.090301003344481601,\"#E4EFF9\"],[0.093645484949832769,\"#E4EEF8\"],[0.096989966555183951,\"#E3EEF8\"],[0.10033444816053512,\"#E2EDF8\"],[0.10367892976588629,\"#E2EDF8\"],[0.10702341137123746,\"#E1EDF8\"],[0.11036789297658862,\"#E1ECF7\"],[0.11371237458193979,\"#E0ECF7\"],[0.11705685618729096,\"#DFEBF7\"],[0.12040133779264214,\"#DEEBF7\"],[0.12374581939799331,\"#DDEAF6\"],[0.12709030100334448,\"#DDEAF6\"],[0.13043478260869565,\"#DDEAF6\"],[0.13377926421404682,\"#DCE9F6\"],[0.13712374581939799,\"#DBE9F6\"],[0.14046822742474915,\"#DAE8F5\"],[0.14381270903010032,\"#DAE8F5\"],[0.14715719063545149,\"#D9E7F5\"],[0.15050167224080269,\"#D9E7F5\"],[0.15384615384615385,\"#D8E7F5\"],[0.15719063545150502,\"#D7E6F4\"],[0.16053511705685619,\"#D7E6F4\"],[0.16387959866220736,\"#D6E5F4\"],[0.16722408026755853,\"#D5E5F4\"],[0.1705685618729097,\"#D5E5F4\"],[0.17391304347826086,\"#D4E4F3\"],[0.17725752508361203,\"#D4E4F3\"],[0.1806020066889632,\"#D3E3F3\"],[0.18394648829431437,\"#D2E3F3\"],[0.18729096989966554,\"#D1E2F2\"],[0.19063545150501671,\"#D1E2F2\"],[0.1939799331103679,\"#D1E2F2\"],[0.19732441471571907,\"#D0E1F2\"],[0.20066889632107024,\"#CFE1F2\"],[0.20401337792642141,\"#CEE0F1\"],[0.20735785953177258,\"#CEE0F1\"],[0.21070234113712374,\"#CDDFF1\"],[0.21404682274247491,\"#CCDFF1\"],[0.21739130434782608,\"#CCDFF1\"],[0.22073578595317725,\"#CBDEF0\"],[0.22408026755852842,\"#CBDEF0\"],[0.22742474916387959,\"#CADDF0\"],[0.23076923076923075,\"#C9DDF0\"],[0.23411371237458192,\"#C8DCEF\"],[0.23745819397993312,\"#C8DCEF\"],[0.24080267558528429,\"#C8DCEF\"],[0.24414715719063546,\"#C7DBEF\"],[0.24749163879598662,\"#C6DBEF\"],[0.25083612040133779,\"#C5DAEE\"],[0.25418060200668896,\"#C4DAEE\"],[0.25752508361204013,\"#C3D9EE\"],[0.2608695652173913,\"#C2D9ED\"],[0.26421404682274247,\"#C1D9ED\"],[0.26755852842809363,\"#C0D8ED\"],[0.2709030100334448,\"#BFD8EC\"],[0.27424749163879597,\"#BED7EC\"],[0.27759197324414714,\"#BCD7EB\"],[0.28093645484949831,\"#BBD6EB\"],[0.28428093645484948,\"#BBD6EB\"],[0.28762541806020064,\"#BAD6EA\"],[0.29096989966555181,\"#B9D5EA\"],[0.29431438127090298,\"#B7D4EA\"],[0.29765886287625415,\"#B6D4E9\"],[0.30100334448160537,\"#B5D3E9\"],[0.30434782608695654,\"#B4D3E8\"],[0.30769230769230771,\"#B3D3E8\"],[0.31103678929765888,\"#B2D2E8\"],[0.31438127090301005,\"#B1D2E7\"],[0.31772575250836121,\"#B0D1E7\"],[0.32107023411371238,\"#AFD1E6\"],[0.32441471571906355,\"#AED0E6\"],[0.32775919732441472,\"#ACD0E6\"],[0.33110367892976589,\"#ACD0E6\"],[0.33444816053511706,\"#ABCFE5\"],[0.33779264214046822,\"#AACFE5\"],[0.34113712374581939,\"#A8CEE4\"],[0.34448160535117056,\"#A7CEE4\"],[0.34782608695652173,\"#A6CDE3\"],[0.3511705685618729,\"#A5CDE3\"],[0.35451505016722407,\"#A4CDE3\"],[0.35785953177257523,\"#A3CCE3\"],[0.3612040133779264,\"#A2CBE2\"],[0.36454849498327757,\"#A1CBE2\"],[0.36789297658862874,\"#A0CAE1\"],[0.37123745819397991,\"#9FCAE1\"],[0.37458193979933108,\"#9DC9E0\"],[0.37792642140468224,\"#9CC9E0\"],[0.38127090301003341,\"#9BC8E0\"],[0.38461538461538458,\"#9AC7E0\"],[0.38795986622073581,\"#98C7DF\"],[0.39130434782608697,\"#97C6DF\"],[0.39464882943143814,\"#96C5DF\"],[0.39799331103678931,\"#94C5DF\"],[0.40133779264214048,\"#93C4DE\"],[0.40468227424749165,\"#92C3DE\"],[0.40802675585284282,\"#90C2DE\"],[0.41137123745819398,\"#8FC1DD\"],[0.41471571906354515,\"#8DC0DD\"],[0.41806020066889632,\"#8CC0DD\"],[0.42140468227424749,\"#8BC0DD\"],[0.42474916387959866,\"#89BFDC\"],[0.42809364548494983,\"#88BEDC\"],[0.43143812709030099,\"#87BDDC\"],[0.43478260869565216,\"#85BCDB\"],[0.43812709030100333,\"#84BBDB\"],[0.4414715719063545,\"#82BADB\"],[0.44481605351170567,\"#81BADB\"],[0.44816053511705684,\"#80B9DA\"],[0.451505016722408,\"#7FB8DA\"],[0.45484949832775917,\"#7DB8D9\"],[0.45819397993311034,\"#7BB7D9\"],[0.46153846153846151,\"#7AB6D9\"],[0.46488294314381268,\"#79B5D8\"],[0.46822742474916385,\"#78B5D8\"],[0.47157190635451507,\"#77B4D8\"],[0.47491638795986624,\"#75B3D8\"],[0.47826086956521741,\"#73B2D7\"],[0.48160535117056857,\"#72B1D7\"],[0.48494983277591974,\"#71B1D7\"],[0.48829431438127091,\"#6FB0D6\"],[0.49163879598662208,\"#6EB0D6\"],[0.49498327759197325,\"#6DAFD6\"],[0.49832775919732442,\"#6BAED6\"],[0.50167224080267558,\"#6AADD5\"],[0.50501672240802675,\"#69ACD5\"],[0.50836120401337792,\"#68ABD4\"],[0.51170568561872909,\"#67ABD4\"],[0.51505016722408026,\"#66AAD4\"],[0.51839464882943143,\"#65AAD3\"],[0.52173913043478259,\"#63A9D3\"],[0.52508361204013376,\"#62A8D2\"],[0.52842809364548493,\"#61A7D2\"],[0.5317725752508361,\"#60A6D1\"],[0.53511705685618727,\"#5FA6D1\"],[0.53846153846153844,\"#5EA5D1\"],[0.5418060200668896,\"#5DA4D0\"],[0.54515050167224077,\"#5CA3D0\"],[0.54849498327759194,\"#5AA3CF\"],[0.55183946488294311,\"#59A2CF\"],[0.55518394648829428,\"#58A1CE\"],[0.55852842809364545,\"#58A1CE\"],[0.56187290969899661,\"#56A0CE\"],[0.56521739130434778,\"#559FCD\"],[0.56856187290969895,\"#549ECD\"],[0.57190635451505012,\"#539DCC\"],[0.57525083612040129,\"#529CCC\"],[0.57859531772575246,\"#509BCB\"],[0.58193979933110362,\"#509BCB\"],[0.58528428093645479,\"#4F9BCB\"],[0.58862876254180596,\"#4E9ACA\"],[0.59197324414715713,\"#4C99CA\"],[0.5953177257525083,\"#4B98C9\"],[0.59866220735785947,\"#4A97C9\"],[0.60200668896321075,\"#4996C8\"],[0.60535117056856191,\"#4896C8\"],[0.60869565217391308,\"#4795C8\"],[0.61204013377926425,\"#4694C7\"],[0.61538461538461542,\"#4594C7\"],[0.61872909698996659,\"#4393C6\"],[0.62207357859531776,\"#4292C6\"],[0.62541806020066892,\"#4292C6\"],[0.62876254180602009,\"#4191C5\"],[0.63210702341137126,\"#4090C5\"],[0.63545150501672243,\"#3F8FC4\"],[0.6387959866220736,\"#3E8EC4\"],[0.64214046822742477,\"#3D8DC3\"],[0.64548494983277593,\"#3C8CC3\"],[0.6488294314381271,\"#3C8CC3\"],[0.65217391304347827,\"#3B8BC2\"],[0.65551839464882944,\"#3A8AC1\"],[0.65886287625418061,\"#3989C1\"],[0.66220735785953178,\"#3888C0\"],[0.66555183946488294,\"#3787C0\"],[0.66889632107023411,\"#3686BF\"],[0.67224080267558528,\"#3585BF\"],[0.67558528428093645,\"#3484BF\"],[0.67892976588628762,\"#3383BE\"],[0.68227424749163879,\"#3282BE\"],[0.68561872909698995,\"#3181BD\"],[0.68896321070234112,\"#3080BD\"],[0.69230769230769229,\"#2F7FBC\"],[0.69565217391304346,\"#2F7FBC\"],[0.69899665551839463,\"#2E7EBC\"],[0.7023411371237458,\"#2D7DBB\"],[0.70568561872909696,\"#2C7CBB\"],[0.70903010033444813,\"#2B7BBA\"],[0.7123745819397993,\"#2A7AB9\"],[0.71571906354515047,\"#2979B9\"],[0.71906354515050164,\"#2979B9\"],[0.72240802675585281,\"#2878B8\"],[0.72575250836120397,\"#2777B8\"],[0.72909698996655514,\"#2676B7\"],[0.73244147157190631,\"#2575B7\"],[0.73578595317725748,\"#2474B6\"],[0.73913043478260865,\"#2474B6\"],[0.74247491638795982,\"#2373B6\"],[0.74581939799331098,\"#2272B5\"],[0.74916387959866215,\"#2171B5\"],[0.75250836120401332,\"#2070B4\"],[0.75585284280936449,\"#1F6FB3\"],[0.75919732441471566,\"#1E6EB2\"],[0.76254180602006683,\"#1E6EB2\"],[0.76588628762541799,\"#1E6DB2\"],[0.76923076923076916,\"#1D6CB1\"],[0.77257525083612044,\"#1C6BB0\"],[0.77591973244147161,\"#1B6AAF\"],[0.77926421404682278,\"#1A69AE\"],[0.78260869565217395,\"#1A68AE\"],[0.78595317725752512,\"#1A68AE\"],[0.78929765886287628,\"#1967AD\"],[0.79264214046822745,\"#1866AC\"],[0.79598662207357862,\"#1765AB\"],[0.79933110367892979,\"#1664AB\"],[0.80267558528428096,\"#1663AA\"],[0.80602006688963213,\"#1562A9\"],[0.80936454849498329,\"#1562A9\"],[0.81270903010033446,\"#1461A8\"],[0.81605351170568563,\"#1360A7\"],[0.8193979933110368,\"#135FA7\"],[0.82274247491638797,\"#125EA6\"],[0.82608695652173914,\"#115DA5\"],[0.8294314381270903,\"#105CA4\"],[0.83277591973244147,\"#105CA4\"],[0.83612040133779264,\"#0F5BA3\"],[0.83946488294314381,\"#0F5AA3\"],[0.84280936454849498,\"#0E59A2\"],[0.84615384615384615,\"#0D58A1\"],[0.84949832775919731,\"#0C57A0\"],[0.85284280936454848,\"#0C57A0\"],[0.85618729096989965,\"#0C56A0\"],[0.85953177257525082,\"#0B559F\"],[0.86287625418060199,\"#0A549E\"],[0.86622073578595316,\"#09539D\"],[0.86956521739130432,\"#08529C\"],[0.87290969899665549,\"#08519C\"],[0.87625418060200666,\"#08519B\"],[0.87959866220735783,\"#08509A\"],[0.882943143812709,\"#084F99\"],[0.88628762541806017,\"#084E97\"],[0.88963210702341133,\"#084C96\"],[0.8929765886287625,\"#084B95\"],[0.89632107023411367,\"#084A93\"],[0.89966555183946484,\"#084A92\"],[0.90301003344481601,\"#084990\"],[0.90635451505016718,\"#08488F\"],[0.90969899665551834,\"#08478E\"],[0.91304347826086951,\"#08468C\"],[0.91638795986622068,\"#08458B\"],[0.91973244147157185,\"#08448A\"],[0.92307692307692302,\"#084489\"],[0.92642140468227419,\"#084388\"],[0.92976588628762535,\"#084286\"],[0.93311036789297652,\"#084185\"],[0.93645484949832769,\"#084083\"],[0.93979933110367886,\"#083F82\"],[0.94314381270903014,\"#083E81\"],[0.94648829431438131,\"#083E7F\"],[0.94983277591973247,\"#083D7E\"],[0.95317725752508364,\"#083C7D\"],[0.95652173913043481,\"#083B7B\"],[0.95986622073578598,\"#083A7A\"],[0.96321070234113715,\"#083979\"],[0.96655518394648832,\"#083978\"],[0.96989966555183948,\"#083876\"],[0.97324414715719065,\"#083775\"],[0.97658862876254182,\"#083674\"],[0.97993311036789299,\"#083572\"],[0.98327759197324416,\"#083471\"],[0.98662207357859533,\"#083370\"],[0.98996655518394649,\"#08336F\"],[0.99331103678929766,\"#08326D\"],[0.99665551839464883,\"#08316C\"],[1,\"#08306B\"]],\"colorbar\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"thickness\":23.039999999999996,\"title\":null,\"titlefont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"tickmode\":\"array\",\"ticktext\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\"],\"tickvals\":[0.0016666666666666668,0.2508333333333333,0.49999999999999994,0.74916666666666665,0.99833333333333329],\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"ticklen\":2,\"len\":0.5}},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[1.0908778897590077,1.0908778897590077,null,1.0908778897590077,0.50094972196331145,null,0.50094972196331145,0.50094972196331145,null,0.50094972196331145,0,null,0.50094972196331145,0.50094972196331145,null,0.50094972196331145,0],\"y\":[45.609375,42.5,null,42.5,42.5,null,42.5,42,null,42,42,null,42.5,43,null,43,43],\"text\":[\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 0.50094972\",\"y: 0.50094972\",null,\"y: 0.50094972\",\"y: 0.50094972\",null,\"y: 0.50094972\",\"y: 0.50094972\",null,\"y: 0.50094972\",\"y: 0.50094972\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.2677165354330708,\"color\":\"rgba(57,190,177,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.0908778897590077,1.0908778897590077,null,1.0908778897590077,0.73180022212606388,null,0.73180022212606388,0.73180022212606388,null,0.73180022212606388,0.69115953326908108,null,0.69115953326908108,0.69115953326908108,null,0.69115953326908108,0.3806270981887479,null,0.3806270981887479,0.3806270981887479,null,0.3806270981887479,0.2552643168918356,null,0.2552643168918356,0.2552643168918356,null,0.2552643168918356,0,null,0.2552643168918356,0.2552643168918356,null,0.2552643168918356,0.185675404080306,null,0.185675404080306,0.185675404080306,null,0.185675404080306,0,null,0.185675404080306,0.185675404080306,null,0.185675404080306,0,null,0.3806270981887479,0.3806270981887479,null,0.3806270981887479,0,null,0.69115953326908108,0.69115953326908108,null,0.69115953326908108,0,null,0.73180022212606388,0.73180022212606388,null,0.73180022212606388,0.4668075826896933,null,0.4668075826896933,0.4668075826896933,null,0.4668075826896933,0.35841748229668219,null,0.35841748229668219,0.35841748229668219,null,0.35841748229668219,0,null,0.35841748229668219,0.35841748229668219,null,0.35841748229668219,0,null,0.4668075826896933,0.4668075826896933,null,0.4668075826896933,0.1730199763105828,null,0.1730199763105828,0.1730199763105828,null,0.1730199763105828,0,null,0.1730199763105828,0.1730199763105828,null,0.1730199763105828,0],\"y\":[45.609375,48.71875,null,48.71875,48.71875,null,48.71875,46.9375,null,46.9375,46.9375,null,46.9375,45.875,null,45.875,45.875,null,45.875,44.75,null,44.75,44.75,null,44.75,44,null,44,44,null,44.75,45.5,null,45.5,45.5,null,45.5,45,null,45,45,null,45.5,46,null,46,46,null,45.875,47,null,47,47,null,46.9375,48,null,48,48,null,48.71875,50.5,null,50.5,50.5,null,50.5,49.5,null,49.5,49.5,null,49.5,49,null,49,49,null,49.5,50,null,50,50,null,50.5,51.5,null,51.5,51.5,null,51.5,51,null,51,51,null,51.5,52,null,52,52],\"text\":[\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 1.09087789\",\"y: 1.09087789\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.25526432\",\"y: 0.25526432\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.18567540\",\"y: 0.18567540\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.38062710\",\"y: 0.38062710\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.69115953\",\"y: 0.69115953\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.73180022\",\"y: 0.73180022\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.35841748\",\"y: 0.35841748\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.46680758\",\"y: 0.46680758\",null,\"y: 0.17301998\",\"y: 0.17301998\",null,\"y: 0.17301998\",\"y: 0.17301998\",null,\"y: 0.17301998\",\"y: 0.17301998\",null,\"y: 0.17301998\",\"y: 0.17301998\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.2677165354330708,\"color\":\"rgba(125,176,221,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.054397227224376,1.054397227224376,null,1.054397227224376,0.47350573521866995,null,0.47350573521866995,0.47350573521866995,null,0.47350573521866995,0,null,0.47350573521866995,0.47350573521866995,null,0.47350573521866995,0],\"y\":[37.859375,40.5,null,40.5,40.5,null,40.5,40,null,40,40,null,40.5,41,null,41,41],\"text\":[\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 0.47350574\",\"y: 0.47350574\",null,\"y: 0.47350574\",\"y: 0.47350574\",null,\"y: 0.47350574\",\"y: 0.47350574\",null,\"y: 0.47350574\",\"y: 0.47350574\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.2677165354330708,\"color\":\"rgba(134,184,117,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.054397227224376,1.054397227224376,null,1.054397227224376,0.65936703189914236,null,0.65936703189914236,0.65936703189914236,null,0.65936703189914236,0,null,0.65936703189914236,0.65936703189914236,null,0.65936703189914236,0.3664468181726131,null,0.3664468181726131,0.3664468181726131,null,0.3664468181726131,0,null,0.3664468181726131,0.3664468181726131,null,0.3664468181726131,0.25729438180055098,null,0.25729438180055098,0.25729438180055098,null,0.25729438180055098,0.20244506563386871,null,0.20244506563386871,0.20244506563386871,null,0.20244506563386871,0,null,0.20244506563386871,0.20244506563386871,null,0.20244506563386871,0.12888304229422309,null,0.12888304229422309,0.12888304229422309,null,0.12888304229422309,0,null,0.12888304229422309,0.12888304229422309,null,0.12888304229422309,0,null,0.25729438180055098,0.25729438180055098,null,0.25729438180055098,0],\"y\":[37.859375,35.21875,null,35.21875,35.21875,null,35.21875,34,null,34,34,null,35.21875,36.4375,null,36.4375,36.4375,null,36.4375,35,null,35,35,null,36.4375,37.875,null,37.875,37.875,null,37.875,36.75,null,36.75,36.75,null,36.75,36,null,36,36,null,36.75,37.5,null,37.5,37.5,null,37.5,37,null,37,37,null,37.5,38,null,38,38,null,37.875,39,null,39,39],\"text\":[\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 1.05439723\",\"y: 1.05439723\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.65936703\",\"y: 0.65936703\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.36644682\",\"y: 0.36644682\",null,\"y: 0.25729438\",\"y: 0.25729438\",null,\"y: 0.25729438\",\"y: 0.25729438\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.20244507\",\"y: 0.20244507\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.12888304\",\"y: 0.12888304\",null,\"y: 0.25729438\",\"y: 0.25729438\",null,\"y: 0.25729438\",\"y: 0.25729438\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.2677165354330708,\"color\":\"rgba(199,167,108,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.5941744666987299,1.5941744666987299,null,1.5941744666987299,0.61424845626023339,null,0.61424845626023339,0.61424845626023339,null,0.61424845626023339,0.27585786880898649,null,0.27585786880898649,0.27585786880898649,null,0.27585786880898649,0,null,0.27585786880898649,0.27585786880898649,null,0.27585786880898649,0,null,0.61424845626023339,0.61424845626023339,null,0.61424845626023339,0],\"y\":[49.9296875,54.25,null,54.25,54.25,null,54.25,53.5,null,53.5,53.5,null,53.5,53,null,53,53,null,53.5,54,null,54,54,null,54.25,55,null,55,55],\"text\":[\"y: 1.59417447\",\"y: 1.59417447\",null,\"y: 1.59417447\",\"y: 1.59417447\",null,\"y: 0.61424846\",\"y: 0.61424846\",null,\"y: 0.61424846\",\"y: 0.61424846\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.27585787\",\"y: 0.27585787\",null,\"y: 0.61424846\",\"y: 0.61424846\",null,\"y: 0.61424846\",\"y: 0.61424846\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.2677165354330708,\"color\":\"rgba(205,153,216,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.2046648341508377,1.2046648341508377,null,1.2046648341508377,0.95788286362070973,null,0.95788286362070973,0.95788286362070973,null,0.95788286362070973,0.79474550028479152,null,0.79474550028479152,0.79474550028479152,null,0.79474550028479152,0.38162569396273166,null,0.38162569396273166,0.38162569396273166,null,0.38162569396273166,0,null,0.38162569396273166,0.38162569396273166,null,0.38162569396273166,0,null,0.79474550028479152,0.79474550028479152,null,0.79474550028479152,0.6664047769347069,null,0.6664047769347069,0.6664047769347069,null,0.6664047769347069,0.36706162143987942,null,0.36706162143987942,0.36706162143987942,null,0.36706162143987942,0,null,0.36706162143987942,0.36706162143987942,null,0.36706162143987942,0.24828582661663648,null,0.24828582661663648,0.24828582661663648,null,0.24828582661663648,0.087558107117793896,null,0.087558107117793896,0.087558107117793896,null,0.087558107117793896,0,null,0.087558107117793896,0.087558107117793896,null,0.087558107117793896,0,null,0.24828582661663648,0.24828582661663648,null,0.24828582661663648,0.23756964971442937,null,0.23756964971442937,0.23756964971442937,null,0.23756964971442937,0.12990466363518882,null,0.12990466363518882,0.12990466363518882,null,0.12990466363518882,0,null,0.12990466363518882,0.12990466363518882,null,0.12990466363518882,0,null,0.23756964971442937,0.23756964971442937,null,0.23756964971442937,0,null,0.6664047769347069,0.6664047769347069,null,0.6664047769347069,0.53487511869044835,null,0.53487511869044835,0.53487511869044835,null,0.53487511869044835,0.43836359937083058,null,0.43836359937083058,0.43836359937083058,null,0.43836359937083058,0.20347407832470954,null,0.20347407832470954,0.20347407832470954,null,0.20347407832470954,0,null,0.20347407832470954,0.20347407832470954,null,0.20347407832470954,0,null,0.43836359937083058,0.43836359937083058,null,0.43836359937083058,0.33205918608658225,null,0.33205918608658225,0.33205918608658225,null,0.33205918608658225,0.27419929098840362,null,0.27419929098840362,0.27419929098840362,null,0.27419929098840362,0,null,0.27419929098840362,0.27419929098840362,null,0.27419929098840362,0.1434382567577874,null,0.1434382567577874,0.1434382567577874,null,0.1434382567577874,0,null,0.1434382567577874,0.1434382567577874,null,0.1434382567577874,0,null,0.33205918608658225,0.33205918608658225,null,0.33205918608658225,0.20894513119211036,null,0.20894513119211036,0.20894513119211036,null,0.20894513119211036,0,null,0.20894513119211036,0.20894513119211036,null,0.20894513119211036,0.15445841184345191,null,0.15445841184345191,0.15445841184345191,null,0.15445841184345191,0.09039992811033179,null,0.09039992811033179,0.09039992811033179,null,0.09039992811033179,0,null,0.09039992811033179,0.09039992811033179,null,0.09039992811033179,0,null,0.15445841184345191,0.15445841184345191,null,0.15445841184345191,0,null,0.53487511869044835,0.53487511869044835,null,0.53487511869044835,0.3721232755076867,null,0.3721232755076867,0.3721232755076867,null,0.3721232755076867,0.35032421362805982,null,0.35032421362805982,0.35032421362805982,null,0.35032421362805982,0.24340283886100486,null,0.24340283886100486,0.24340283886100486,null,0.24340283886100486,0.2124431624834609,null,0.2124431624834609,0.2124431624834609,null,0.2124431624834609,0.12708171116759615,null,0.12708171116759615,0.12708171116759615,null,0.12708171116759615,0,null,0.12708171116759615,0.12708171116759615,null,0.12708171116759615,0,null,0.2124431624834609,0.2124431624834609,null,0.2124431624834609,0,null,0.24340283886100486,0.24340283886100486,null,0.24340283886100486,0,null,0.35032421362805982,0.35032421362805982,null,0.35032421362805982,0,null,0.3721232755076867,0.3721232755076867,null,0.3721232755076867,0.18257733577118407,null,0.18257733577118407,0.18257733577118407,null,0.18257733577118407,0,null,0.18257733577118407,0.18257733577118407,null,0.18257733577118407,0.12129831255664315,null,0.12129831255664315,0.12129831255664315,null,0.12129831255664315,0,null,0.12129831255664315,0.12129831255664315,null,0.12129831255664315,0.094902085465199792,null,0.094902085465199792,0.094902085465199792,null,0.094902085465199792,0,null,0.094902085465199792,0.094902085465199792,null,0.094902085465199792,0,null,0.95788286362070973,0.95788286362070973,null,0.95788286362070973,0.40783062668695391,null,0.40783062668695391,0.40783062668695391,null,0.40783062668695391,0.21815448450140359,null,0.21815448450140359,0.21815448450140359,null,0.21815448450140359,0.099186753204319189,null,0.099186753204319189,0.099186753204319189,null,0.099186753204319189,0,null,0.099186753204319189,0.099186753204319189,null,0.099186753204319189,0,null,0.21815448450140359,0.21815448450140359,null,0.21815448450140359,0,null,0.40783062668695391,0.40783062668695391,null,0.40783062668695391,0.31959962472454068,null,0.31959962472454068,0.31959962472454068,null,0.31959962472454068,0.20918247212427829,null,0.20918247212427829,0.20918247212427829,null,0.20918247212427829,0,null,0.20918247212427829,0.20918247212427829,null,0.20918247212427829,0,null,0.31959962472454068,0.31959962472454068,null,0.31959962472454068,0.11950480173549577,null,0.11950480173549577,0.11950480173549577,null,0.11950480173549577,0,null,0.11950480173549577,0.11950480173549577,null,0.11950480173549577,0],\"y\":[27.923828125,17.98828125,null,17.98828125,17.98828125,null,17.98828125,6.1015625,null,6.1015625,6.1015625,null,6.1015625,1.5,null,1.5,1.5,null,1.5,1,null,1,1,null,1.5,2,null,2,2,null,6.1015625,10.703125,null,10.703125,10.703125,null,10.703125,4.4375,null,4.4375,4.4375,null,4.4375,3,null,3,3,null,4.4375,5.875,null,5.875,5.875,null,5.875,4.5,null,4.5,4.5,null,4.5,4,null,4,4,null,4.5,5,null,5,5,null,5.875,7.25,null,7.25,7.25,null,7.25,6.5,null,6.5,6.5,null,6.5,6,null,6,6,null,6.5,7,null,7,7,null,7.25,8,null,8,8,null,10.703125,16.96875,null,16.96875,16.96875,null,16.96875,11.46875,null,11.46875,11.46875,null,11.46875,9.5,null,9.5,9.5,null,9.5,9,null,9,9,null,9.5,10,null,10,10,null,11.46875,13.4375,null,13.4375,13.4375,null,13.4375,11.75,null,11.75,11.75,null,11.75,11,null,11,11,null,11.75,12.5,null,12.5,12.5,null,12.5,12,null,12,12,null,12.5,13,null,13,13,null,13.4375,15.125,null,15.125,15.125,null,15.125,14,null,14,14,null,15.125,16.25,null,16.25,16.25,null,16.25,15.5,null,15.5,15.5,null,15.5,15,null,15,15,null,15.5,16,null,16,16,null,16.25,17,null,17,17,null,16.96875,22.46875,null,22.46875,22.46875,null,22.46875,21.0625,null,21.0625,21.0625,null,21.0625,20.125,null,20.125,20.125,null,20.125,19.25,null,19.25,19.25,null,19.25,18.5,null,18.5,18.5,null,18.5,18,null,18,18,null,18.5,19,null,19,19,null,19.25,20,null,20,20,null,20.125,21,null,21,21,null,21.0625,22,null,22,22,null,22.46875,23.875,null,23.875,23.875,null,23.875,23,null,23,23,null,23.875,24.75,null,24.75,24.75,null,24.75,24,null,24,24,null,24.75,25.5,null,25.5,25.5,null,25.5,25,null,25,25,null,25.5,26,null,26,26,null,17.98828125,29.875,null,29.875,29.875,null,29.875,28.25,null,28.25,28.25,null,28.25,27.5,null,27.5,27.5,null,27.5,27,null,27,27,null,27.5,28,null,28,28,null,28.25,29,null,29,29,null,29.875,31.5,null,31.5,31.5,null,31.5,30.5,null,30.5,30.5,null,30.5,30,null,30,30,null,30.5,31,null,31,31,null,31.5,32.5,null,32.5,32.5,null,32.5,32,null,32,32,null,32.5,33,null,33,33],\"text\":[\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.38162569\",\"y: 0.38162569\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.79474550\",\"y: 0.79474550\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.36706162\",\"y: 0.36706162\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.08755811\",\"y: 0.08755811\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.24828583\",\"y: 0.24828583\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.12990466\",\"y: 0.12990466\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.23756965\",\"y: 0.23756965\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.66640478\",\"y: 0.66640478\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.20347408\",\"y: 0.20347408\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.43836360\",\"y: 0.43836360\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.27419929\",\"y: 0.27419929\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.14343826\",\"y: 0.14343826\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.33205919\",\"y: 0.33205919\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.20894513\",\"y: 0.20894513\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.09039993\",\"y: 0.09039993\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.15445841\",\"y: 0.15445841\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.53487512\",\"y: 0.53487512\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.12708171\",\"y: 0.12708171\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.21244316\",\"y: 0.21244316\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.24340284\",\"y: 0.24340284\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.35032421\",\"y: 0.35032421\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.37212328\",\"y: 0.37212328\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.18257734\",\"y: 0.18257734\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.12129831\",\"y: 0.12129831\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.09490209\",\"y: 0.09490209\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.95788286\",\"y: 0.95788286\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.09918675\",\"y: 0.09918675\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.21815448\",\"y: 0.21815448\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.40783063\",\"y: 0.40783063\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.20918247\",\"y: 0.20918247\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.31959962\",\"y: 0.31959962\",null,\"y: 0.11950480\",\"y: 0.11950480\",null,\"y: 0.11950480\",\"y: 0.11950480\",null,\"y: 0.11950480\",\"y: 0.11950480\",null,\"y: 0.11950480\",\"y: 0.11950480\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.2677165354330708,\"color\":\"rgba(228,149,165,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.8228771534841937,1.8228771534841937,null,1.8228771534841937,1.2046648341508377,null,1.2046648341508377,1.2046648341508377,null,1.2046648341508377,1.054397227224376,null,1.8228771534841937,1.8228771534841937,null,1.8228771534841937,1.5941744666987299,null,1.5941744666987299,1.5941744666987299,null,1.5941744666987299,1.0908778897590077],\"y\":[38.9267578125,27.923828125,null,27.923828125,27.923828125,null,27.923828125,37.859375,null,37.859375,37.859375,null,38.9267578125,49.9296875,null,49.9296875,49.9296875,null,49.9296875,45.609375,null,45.609375,45.609375],\"text\":[\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 1.20466483\",\"y: 1.20466483\",null,\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.82287715\",\"y: 1.82287715\",null,\"y: 1.59417447\",\"y: 1.59417447\",null,\"y: 1.59417447\",\"y: 1.59417447\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":2.2677165354330708,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1.8228771534841937,1.2046648341508377,0.95788286362070973,0.79474550028479152,0.38162569396273166,0,0,0.6664047769347069,0.36706162143987942,0,0.24828582661663648,0.087558107117793896,0,0,0.23756964971442937,0.12990466363518882,0,0,0,0.53487511869044835,0.43836359937083058,0.20347407832470954,0,0,0.33205918608658225,0.27419929098840362,0,0.1434382567577874,0,0,0.20894513119211036,0,0.15445841184345191,0.09039992811033179,0,0,0,0.3721232755076867,0.35032421362805982,0.24340283886100486,0.2124431624834609,0.12708171116759615,0,0,0,0,0,0.18257733577118407,0,0.12129831255664315,0,0.094902085465199792,0,0,0.40783062668695391,0.21815448450140359,0.099186753204319189,0,0,0,0.31959962472454068,0.20918247212427829,0,0,0.11950480173549577,0,0,1.054397227224376,0.65936703189914236,0,0.3664468181726131,0,0.25729438180055098,0.20244506563386871,0,0.12888304229422309,0,0,0,0.47350573521866995,0,0,1.5941744666987299,1.0908778897590077,0.50094972196331145,0,0,0.73180022212606388,0.69115953326908108,0.3806270981887479,0.2552643168918356,0,0.185675404080306,0,0,0,0,0.4668075826896933,0.35841748229668219,0,0,0.1730199763105828,0,0,0.61424845626023339,0.27585786880898649,0,0,0],\"y\":[38.9267578125,27.923828125,17.98828125,6.1015625,1.5,1,2,10.703125,4.4375,3,5.875,4.5,4,5,7.25,6.5,6,7,8,16.96875,11.46875,9.5,9,10,13.4375,11.75,11,12.5,12,13,15.125,14,16.25,15.5,15,16,17,22.46875,21.0625,20.125,19.25,18.5,18,19,20,21,22,23.875,23,24.75,24,25.5,25,26,29.875,28.25,27.5,27,28,29,31.5,30.5,30,31,32.5,32,33,37.859375,35.21875,34,36.4375,35,37.875,36.75,36,37.5,37,38,39,40.5,40,41,49.9296875,45.609375,42.5,42,43,48.71875,46.9375,45.875,44.75,44,45.5,45,46,47,48,50.5,49.5,49,50,51.5,51,52,54.25,53.5,53,54,55],\"text\":[\"y: 1.82287715\",\"y: 1.20466483\",\"y: 0.95788286\",\"y: 0.79474550\",\"y: 0.38162569\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.66640478\",\"y: 0.36706162\",\"y: 0.00000000\",\"y: 0.24828583\",\"y: 0.08755811\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.23756965\",\"y: 0.12990466\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.53487512\",\"y: 0.43836360\",\"y: 0.20347408\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.33205919\",\"y: 0.27419929\",\"y: 0.00000000\",\"y: 0.14343826\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.20894513\",\"y: 0.00000000\",\"y: 0.15445841\",\"y: 0.09039993\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.37212328\",\"y: 0.35032421\",\"y: 0.24340284\",\"y: 0.21244316\",\"y: 0.12708171\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.18257734\",\"y: 0.00000000\",\"y: 0.12129831\",\"y: 0.00000000\",\"y: 0.09490209\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.40783063\",\"y: 0.21815448\",\"y: 0.09918675\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.31959962\",\"y: 0.20918247\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.11950480\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 1.05439723\",\"y: 0.65936703\",\"y: 0.00000000\",\"y: 0.36644682\",\"y: 0.00000000\",\"y: 0.25729438\",\"y: 0.20244507\",\"y: 0.00000000\",\"y: 0.12888304\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.47350574\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 1.59417447\",\"y: 1.09087789\",\"y: 0.50094972\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.73180022\",\"y: 0.69115953\",\"y: 0.38062710\",\"y: 0.25526432\",\"y: 0.00000000\",\"y: 0.18567540\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.46680758\",\"y: 0.35841748\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.17301998\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.61424846\",\"y: 0.27585787\",\"y: 0.00000000\",\"y: 0.00000000\",\"y: 0.00000000\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"transparent\",\"opacity\":1,\"size\":null,\"symbol\":null,\"line\":{\"width\":1.8897637795275593,\"color\":\"transparent\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"xaxis\":{\"domain\":[0,0.80000000000000004],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.5,5.5],\"tickmode\":\"array\",\"ticktext\":[\"RADIO_PR\",\"TV_PR\",\"LLPHONE_PR\",\"MPHONE_PR\",\"COMPUTER_PR\"],\"tickvals\":[1,2,3,4,5],\"categoryorder\":\"array\",\"categoryarray\":[\"RADIO_PR\",\"TV_PR\",\"LLPHONE_PR\",\"MPHONE_PR\",\"COMPUTER_PR\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":6.6417600664175991},\"tickangle\":-45,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176002,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":\"ICT Indicators\",\"hoverformat\":\".2f\"},\"xaxis2\":{\"domain\":[0.80000000000000004,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0,1.8228771534841937],\"tickmode\":\"array\",\"ticktext\":[\"0.0\",\"0.5\",\"1.0\",\"1.5\"],\"tickvals\":[0,0.5,1,1.5],\"categoryorder\":\"array\",\"categoryarray\":[\"0.0\",\"0.5\",\"1.0\",\"1.5\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":false,\"tickfont\":{\"color\":null,\"family\":null,\"size\":0},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"\",\"font\":{\"color\":null,\"family\":null,\"size\":0}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.5,55.5],\"tickmode\":\"array\",\"ticktext\":[\"Narphan\",\"Pangwaun\",\"Mongpan\",\"Nansang\",\"Kyaukme\",\"Kalaw\",\"Hseni\",\"Langkho\",\"Kunhing\",\"Laihka\",\"Monghsat\",\"Loilen\",\"Mongnai\",\"Mongton\",\"Hsipaw\",\"Hopong\",\"Monghsu\",\"Pinlaung\",\"Mongmit\",\"Pekon\",\"Kutkai\",\"Namtu\",\"Hsihseng\",\"Kyethi\",\"Tangyan\",\"Namhsan\",\"Mongyai\",\"Mongping\",\"Mongkhet\",\"Mawkmai\",\"Mongkaing\",\"Manton\",\"Matman\",\"Ywangan\",\"Pindaya\",\"Lawksawk\",\"Nyaungshwe\",\"Nawnghkio\",\"Monghpyak\",\"Mabein\",\"Mongyawng\",\"Kunlong\",\"Konkyan\",\"Mongyang\",\"Mongmao\",\"Hopang\",\"Namhkan\",\"Laukkaing\",\"Mongla\",\"Pangsang\",\"Kengtung\",\"Lashio\",\"Taunggyi\",\"Tachileik\",\"Muse\"],\"tickvals\":[1,2,3,3.9999999999999996,5,6,7,7.9999999999999991,9,10,11,12,13,14,14.999999999999998,15.999999999999998,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55],\"categoryorder\":\"array\",\"categoryarray\":[\"Narphan\",\"Pangwaun\",\"Mongpan\",\"Nansang\",\"Kyaukme\",\"Kalaw\",\"Hseni\",\"Langkho\",\"Kunhing\",\"Laihka\",\"Monghsat\",\"Loilen\",\"Mongnai\",\"Mongton\",\"Hsipaw\",\"Hopong\",\"Monghsu\",\"Pinlaung\",\"Mongmit\",\"Pekon\",\"Kutkai\",\"Namtu\",\"Hsihseng\",\"Kyethi\",\"Tangyan\",\"Namhsan\",\"Mongyai\",\"Mongping\",\"Mongkhet\",\"Mawkmai\",\"Mongkaing\",\"Manton\",\"Matman\",\"Ywangan\",\"Pindaya\",\"Lawksawk\",\"Nyaungshwe\",\"Nawnghkio\",\"Monghpyak\",\"Mabein\",\"Mongyawng\",\"Kunlong\",\"Konkyan\",\"Mongyang\",\"Mongmao\",\"Hopang\",\"Namhkan\",\"Laukkaing\",\"Mongla\",\"Pangsang\",\"Kengtung\",\"Lashio\",\"Taunggyi\",\"Tachileik\",\"Muse\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":5.3134080531340802},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176002,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"Townships of Shan State\",\"hoverformat\":\".2f\"},\"annotations\":[],\"shapes\":[],\"images\":[],\"margin\":{\"t\":60,\"r\":null,\"b\":35.06849315068493,\"l\":200},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"y\":1,\"yanchor\":\"top\"},\"hovermode\":\"closest\",\"barmode\":\"relative\",\"title\":\"Geographic Segmentation of Shan State by ICT indicators\"},\"attrs\":{\"c8f86c2e7e94\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"heatmap\"},\"c8f8416f13fa\":{\"x\":{},\"y\":{},\"xend\":{},\"yend\":{},\"colour\":{},\"linetype\":{},\"size\":{},\"type\":\"scatter\"},\"c8f871f522a0\":{\"x\":{},\"y\":{},\"colour\":{},\"shape\":{},\"size\":{}}},\"source\":\"A\",\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displaylogo\":false,\"modeBarButtonsToRemove\":[\"sendDataToCloud\",\"select2d\",\"lasso2d\",\"autoScale2d\",\"hoverClosestCartesian\",\"hoverCompareCartesian\",\"sendDataToCloud\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"subplot\":true,\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nHovering over a cell shows the township, the variable and its min-max value. This heatmap clusters the normalised values, so its six groups are not exactly the same as the ones from `hclust_ward`, which used the raw values. The darkest block, high on television, mobile phones and computers at once, holds the border trade towns Muse, Tachileik, Laukkaing and Mongla together with Taunggyi, Lashio, Kengtung and Pangsang.\n\n### Mapping the clusters\n\nI cut the tree into six clusters with `cutree()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups <- as.factor(cutree(hclust_ward, k=6))\n```\n:::\n\n\n`groups` is a factor with one label per township. To map it, I converted it to a matrix, attached it to `shan_sf` with `cbind()` and renamed the new column to `CLUSTER`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf_cluster <- cbind(shan_sf, as.matrix(groups)) %>%\n  rename(`CLUSTER`=`as.matrix.groups.`)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqtm(shan_sf_cluster, \"CLUSTER\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(shan_sf_cluster$CLUSTER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 1  2  3  4  5  6 \n20  4 13  6  7  5 \n```\n\n\n:::\n:::\n\n\nThe clusters are very fragmented. I counted the number of separate pieces each cluster forms on the map, using the contiguity neighbour list from Part 4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_check <- poly2nb(shan_sf)\n\ncount_pieces <- function(cl) {\n  sapply(sort(unique(cl)), function(g) {\n    suppressWarnings(n.comp.nb(subset(nb_check, cl == g)))$nc\n  })\n}\n\ncount_pieces(shan_sf_cluster$CLUSTER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 2 3 4 5 6 \n4 4 5 5 5 1 \n```\n\n\n:::\n:::\n\n\nFive of the six clusters are split into four or five separate pieces. Only cluster 6 is one connected block, Mongmao, Pangsang, Hopang, Pangwaun and Mongyang in the Wa area along the Chinese border. This is the main limitation of a non-spatial method. Townships end up together because their ICT profiles match, whether or not they are anywhere near each other.\n\n### A check, clustering the standardised variables\n\nSince the raw scale gives `MPHONE_PR` and `TV_PR` most of the weight, I reran the same Ward clustering on the min-max values to see how much the grouping depends on that choice.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups_std <- cutree(hclust(dist(shan_ict.std), method = \"ward.D\"), k = 6)\n\ntable(raw = groups, standardised = groups_std)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   standardised\nraw  1  2  3  4  5  6\n  1 14  1  4  0  0  1\n  2  0  1  0  0  3  0\n  3  0  6  5  2  0  0\n  4  0  0  0  5  0  1\n  5  1  0  0  0  4  2\n  6  0  0  0  1  0  4\n```\n\n\n:::\n:::\n\n\nThe two solutions agree only in part. Cluster 1 from the raw values mostly stays together, but cluster 3 splits three ways and townships from cluster 5 spread across three groups. With the variables on equal terms, radio and land line phones get more say, and several townships change neighbours in the tree. The rest of this page follows the notes and uses the raw values.\n\n::: {.callout-important}\n## My takeaway\n\nWard's method gave the strongest structure, and the gap statistic pointed to six clusters only by a very small margin over four or five. The six clusters make sense in ICT terms, with a border town group high on almost everything and a Wa group with very little radio. On the map they are scattered across Shan State. I also learned that leaving the variables unscaled hands most of the decision to mobile phones and television.\n:::\n\n## Part 4, Spatially constrained clustering with SKATER\n\nSKATER (Spatial 'K'luster Analysis by Tree Edge Removal) only allows neighbouring townships to join the same cluster. It links all townships in a minimum spanning tree, where each link is between two neighbours, and then cuts the tree into pieces. Each piece is one cluster and is contiguous by construction.\n\n### Converting to SpatialPolygonsDataFrame\n\nThe notes convert `shan_sf` into an sp object because older versions of the SKATER functions only accepted sp.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sp <- as_Spatial(shan_sf)\n```\n:::\n\n\n::: {.callout-note}\n## sf works directly now\n\nCurrent versions of spdep accept sf objects in `poly2nb()`. I ran `poly2nb()` on both `shan_sf` and `shan_sp` and got identical neighbour lists, so the conversion is no longer needed. I kept it to follow the notes.\n:::\n\n### Computing the neighbour list\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan.nb <- poly2nb(shan_sp)\nsummary(shan.nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 55 \nNumber of nonzero links: 264 \nPercentage nonzero weights: 8.727273 \nAverage number of links: 4.8 \nLink number distribution:\n\n 2  3  4  5  6  7  8  9 \n 5  9  7 21  4  3  5  1 \n5 least connected regions:\n3 5 7 9 47 with 2 links\n1 most connected region:\n8 with 9 links\n```\n\n\n:::\n:::\n\n\nThe 55 townships have 264 neighbour links, an average of 4.8 each. Five townships have only two neighbours, regions 3, 5, 7, 9 and 47, which are Ywangan, Mabein, Pekon, Nawnghkio and Pangwaun. Region 8, Lawksawk, has the most with nine.\n\nI plotted the network on top of the township boundaries. The boundaries go first, since the first plot sets the extent and the network would otherwise clip parts of the map. The centroids of the polygons serve as the nodes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(\n  st_centroid(st_geometry(shan_sf)))\n\nplot(st_geometry(shan_sf), \n     border=grey(.5))\nplot(shan.nb,\n     coords, \n     col=\"blue\", \n     add=TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-48-1.png){width=768}\n:::\n:::\n\n\n### Computing the minimum spanning tree\n\n#### Calculating edge costs\n\n`nbcosts()` gives each neighbour link a cost, the euclidean distance between the two townships in the five ICT variables. A low cost means two neighbours have similar profiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlcosts <- nbcosts(shan.nb, shan_ict)\n```\n:::\n\n\nI then turned the neighbour list into a weights object with these costs as the weights. Style `\"B\"` keeps the costs as they are, without row standardisation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan.w <- nb2listw(shan.nb, \n                   lcosts, \n                   style=\"B\")\nsummary(shan.w)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 55 \nNumber of nonzero links: 264 \nPercentage nonzero weights: 8.727273 \nAverage number of links: 4.8 \nLink number distribution:\n\n 2  3  4  5  6  7  8  9 \n 5  9  7 21  4  3  5  1 \n5 least connected regions:\n3 5 7 9 47 with 2 links\n1 most connected region:\n8 with 9 links\n\nWeights style: B \nWeights constants summary:\n   n   nn       S0       S1        S2\nB 55 3025 76267.65 58260785 522016004\n```\n\n\n:::\n:::\n\n\n`S0`, the sum of all weights, is 76,268. Each link appears twice in the list, once in each direction, so this is twice the total cost of the 132 links.\n\n#### Building the minimum spanning tree\n\n`mstree()` finds the set of 54 links that connects all 55 townships with the lowest total cost.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nshan.mst <- mstree(shan.w)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(shan.mst)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"mst\"    \"matrix\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(shan.mst)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 54  3\n```\n\n\n:::\n:::\n\n\nThe tree has 54 rows, one fewer than the number of townships, since a spanning tree on n nodes always has n minus 1 edges. Each row holds the two townships at the ends of an edge and its cost.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(shan.mst)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1] [,2]      [,3]\n[1,]   28   12  78.78999\n[2,]   12   49  59.69478\n[3,]   28   13  92.79567\n[4,]   13   52 110.55197\n[5,]   49   35 124.74445\n[6,]   35   37  91.65458\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## The first rows differ from the notes\n\nMy first rows do not match the notes, which start with townships 54 and 48. `mstree()` picks a random starting township when `ini` is not given, and the order of the rows follows the order in which the tree grows. I built the tree from two different seeds and got exactly the same 54 edges with the same total cost of 9,686.6 both times. Only the order changes, and SKATER gives the same clusters as the notes. I added `set.seed()` so the output above stays the same on every render.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(shan_sf), \n                 border=gray(.5))\nplot.mst(shan.mst, \n         coords, \n         col=\"blue\", \n         cex.lab=0.7, \n         cex.circles=0.005, \n         add=TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-55-1.png){width=768}\n:::\n:::\n\n\nCompared with the neighbour network, each township now has only the links needed to keep the tree connected, and there are no loops.\n\n### Computing spatially constrained clusters\n\n`skater()` takes the two node columns of the tree, the data used to update the costs as groups form, and the number of cuts. Six clusters need five cuts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclust6 <- spdep::skater(edges = shan.mst[,1:2], \n                 data = shan_ict, \n                 method = \"euclidean\", \n                 ncuts = 5)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(clust6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 8\n $ groups      : num [1:55] 3 3 6 3 3 3 3 3 3 3 ...\n $ edges.groups:List of 6\n  ..$ :List of 3\n  .. ..$ node: num [1:22] 13 48 45 55 52 37 34 16 25 54 ...\n  .. ..$ edge: num [1:21, 1:3] 48 55 45 37 34 16 52 25 13 28 ...\n  .. ..$ ssw : num 3423\n  ..$ :List of 3\n  .. ..$ node: num [1:18] 47 27 53 38 42 15 41 51 43 32 ...\n  .. ..$ edge: num [1:17, 1:3] 53 15 42 38 41 51 15 27 15 43 ...\n  .. ..$ ssw : num 3759\n  ..$ :List of 3\n  .. ..$ node: num [1:11] 2 6 8 1 36 4 10 9 46 5 ...\n  .. ..$ edge: num [1:10, 1:3] 6 1 8 36 4 6 8 10 10 9 ...\n  .. ..$ ssw : num 1458\n  ..$ :List of 3\n  .. ..$ node: num [1:2] 44 20\n  .. ..$ edge: num [1, 1:3] 44 20 95\n  .. ..$ ssw : num 95\n  ..$ :List of 3\n  .. ..$ node: num 23\n  .. ..$ edge: num[0 , 1:3] \n  .. ..$ ssw : num 0\n  ..$ :List of 3\n  .. ..$ node: num 3\n  .. ..$ edge: num[0 , 1:3] \n  .. ..$ ssw : num 0\n $ not.prune   : NULL\n $ candidates  : int [1:6] 1 2 3 4 5 6\n $ ssto        : num 12613\n $ ssw         : num [1:6] 12613 10977 9962 9540 9123 ...\n $ crit        : num [1:2] 1 Inf\n $ vec.crit    : num [1:55] 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"class\")= chr \"skater\"\n```\n\n\n:::\n:::\n\n\n`groups` holds the cluster label of each township. `edges.groups` describes each cluster with its nodes, edges and within cluster sum of squares (`ssw`). `ssto` is the total sum of squares, and `ssw` at the top level records the criterion after each cut.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nccs6 <- clust6$groups\nccs6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 3 3 6 3 3 3 3 3 3 3 2 1 1 1 2 1 1 1 2 4 1 2 5 1 1 1 2 1 2 2 1 2 2 1 1 3 1 2\n[39] 2 2 2 2 2 4 1 3 2 1 1 1 2 1 2 1 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ccs6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nccs6\n 1  2  3  4  5  6 \n22 18 11  2  1  1 \n```\n\n\n:::\n:::\n\n\nThe six clusters have 22, 18, 11, 2, 1 and 1 townships. The notes say the first cluster has 12 nodes, but the `node` vector of the first element of `edges.groups` has length 22, matching the table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(clust6$ssw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12613 10977  9962  9540  9123  8735\n```\n\n\n:::\n:::\n\n\nThe first cut does most of the work. It lowers the criterion from 12,613 to 10,977, and each later cut takes off only between about 390 and 1,020. The last three cuts remove small branches, which is why cluster 4 has two townships and clusters 5 and 6 one each.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf %>%\n  st_drop_geometry() %>%\n  mutate(SP_CLUSTER = ccs6) %>%\n  filter(SP_CLUSTER %in% 4:6) %>%\n  select(SP_CLUSTER, TS.x, RADIO_PR, TV_PR, LLPHONE_PR, MPHONE_PR, COMPUTER_PR) %>%\n  arrange(SP_CLUSTER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  SP_CLUSTER    TS.x  RADIO_PR    TV_PR LLPHONE_PR MPHONE_PR COMPUTER_PR\n1          4 Mongpan 228.74008 517.2477   21.58273  437.7421   46.485888\n2          4 Langkho 227.46781 587.1483   74.39199  403.9103   32.308059\n3          5 Narphan  75.27012 210.0886   42.18769  305.2689    3.277892\n4          6 Ywangan 484.52147 260.5734   11.93591  120.2856    4.414650\n```\n\n\n:::\n:::\n\n\nThe singletons are extreme townships. Ywangan has the highest radio rate in the state and the sixth lowest television rate. Narphan has the lowest computer rate in the state and the third lowest television rate. The tree can only isolate them by cutting them off, since every possible region around them would contain townships unlike them.\n\nI plotted the pruned tree on the map. The notes give five colours for six groups, so I added a sixth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(st_geometry(shan_sf), \n     border=gray(.5))\nplot(clust6, \n     coords, \n     cex.lab=.7,\n     groups.colors=c(\"red\",\"green\",\"blue\", \"brown\", \"pink\", \"orange\"),\n     cex.circles=0.005, \n     add=TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-62-1.png){width=768}\n:::\n:::\n\n\n### Visualising the SKATER clusters\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups_mat <- as.matrix(clust6$groups)\nshan_sf_spatialcluster <- cbind(shan_sf_cluster, as.factor(groups_mat)) %>%\n  rename(`SP_CLUSTER`=`as.factor.groups_mat.`)\nqtm(shan_sf_spatialcluster, \"SP_CLUSTER\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\nFor comparison I put the hierarchical clusters and the SKATER clusters side by side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhclust.map <- qtm(shan_sf_cluster,\n                  \"CLUSTER\") + \n  tm_borders(col_alpha = 0.5) \n\nshclust.map <- qtm(shan_sf_spatialcluster,\n                   \"SP_CLUSTER\") + \n  tm_borders(col_alpha = 0.5) \n\ntmap_arrange(hclust.map, shclust.map,\n             asp=NA, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-64-1.png){width=1152}\n:::\n:::\n\n\nEvery SKATER cluster is one connected region. Cluster 1 covers the central and southern belt from Hsipaw down through Loilen to Monghsat. Cluster 2 runs along the whole eastern border from Muse and Lashio to Tachileik and Kengtung. Cluster 3 is the western edge from Mongmit down to Pinlaung, including Taunggyi.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf_spatialcluster %>%\n  st_drop_geometry() %>%\n  group_by(SP_CLUSTER) %>%\n  summarise(n = n(),\n            mean_RADIO_PR = mean(RADIO_PR),\n            mean_TV_PR = mean(TV_PR),\n            mean_LLPHONE_PR = mean(LLPHONE_PR),\n            mean_MPHONE_PR = mean(MPHONE_PR),\n            mean_COMPUTER_PR = mean(COMPUTER_PR))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  SP_CLUSTER     n mean_RADIO_PR mean_TV_PR mean_LLPHONE_PR mean_MPHONE_PR\n  <fct>      <int>         <dbl>      <dbl>           <dbl>          <dbl>\n1 1             22         186.        416.            26.1           173.\n2 2             18         174.        597.            91.0           476.\n3 3             11         329.        595.            40.8           331.\n4 4              2         228.        552.            48.0           421.\n5 5              1          75.3       210.            42.2           305.\n6 6              1         485.        261.            11.9           120.\n# ℹ 1 more variable: mean_COMPUTER_PR <dbl>\n```\n\n\n:::\n:::\n\n\nThe three large regions have clear profiles. Among them, the eastern border region (cluster 2) has the highest land line, mobile phone and computer rates but the lowest radio rate, 174 per thousand. The western region (cluster 3) has the highest radio rate at 329 and fairly high television. The central belt (cluster 1) is lowest of the three on television, mobile phones and computers.\n\nThe price of contiguity shows in the spread within clusters. Cluster 2 joins the border towns of Muse and Tachileik with the Wa townships of Pangsang and Mongmao because they lie on the same border, even though hierarchical clustering put them in different groups. I measured the share of total variance explained by each solution with a small helper.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_squared <- function(cl) {\n  x <- as.matrix(shan_ict)\n  tss <- sum(sweep(x, 2, colMeans(x))^2)\n  wss <- sum(sapply(unique(cl), function(g) {\n    xg <- x[cl == g, , drop = FALSE]\n    sum(sweep(xg, 2, colMeans(xg))^2)\n  }))\n  1 - wss / tss\n}\n\nc(hclust = r_squared(shan_sf_cluster$CLUSTER),\n  skater = r_squared(ccs6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   hclust    skater \n0.7610272 0.4998530 \n```\n\n\n:::\n:::\n\n\nThe hierarchical clusters explain 76 percent of the variance in the five variables, and the SKATER clusters only 50 percent.\n\n::: {.callout-important}\n## My takeaway\n\nSKATER turned the scattered pieces into three large connected regions, west, centre and eastern border, plus three tiny clusters for townships too unusual to fit anywhere. That contiguity cost a lot of homogeneity, with the explained variance falling from 76 to 50 percent. Asking for six clusters did not give six useful regions here, because three of the five cuts went into trimming outliers.\n:::\n\n## Part 5, Spatially constrained clustering with ClustGeo\n\n**ClustGeo** offers a softer constraint. Its `hclustgeo()` function runs a Ward-like hierarchical clustering on two dissimilarity matrices at once. D0 holds the differences in the clustering variables and D1 holds the differences in space. A mixing parameter alpha between 0 and 1 sets the balance. At alpha = 0 only D0 counts, and at alpha = 1 only geography counts. The aim is to find an alpha that makes the clusters more compact on the map without losing too much homogeneity in the variables, and `choicealpha()` helps with that.\n\n### Ward-like hierarchical clustering with ClustGeo\n\nWith only D0, `hclustgeo()` is an ordinary Ward clustering. D0 has to be a `dist` object, so I reused `proxmat`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnongeo_cluster <- hclustgeo(proxmat)\nplot(nongeo_cluster, cex = 0.5)\nrect.hclust(nongeo_cluster, \n            k = 6, \n            border = 2:7)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-67-1.png){width=1152}\n:::\n:::\n\n\n#### Mapping the clusters\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups <- as.factor(cutree(nongeo_cluster, k=6))\n\nshan_sf_ngeo_cluster <- cbind(shan_sf, as.matrix(groups)) %>%\n  rename(`CLUSTER` = `as.matrix.groups.`)\n\nqtm(shan_sf_ngeo_cluster, \"CLUSTER\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-68-1.png){width=672}\n:::\n:::\n\n\nThis map is close to the `hclust()` map from Part 3 but not the same.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(hclustgeo = shan_sf_ngeo_cluster$CLUSTER, \n      hclust_ward.D = shan_sf_cluster$CLUSTER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         hclust_ward.D\nhclustgeo  1  2  3  4  5  6\n        1 16  0  0  0  0  0\n        2  4  1  0  0  3  0\n        3  0  0 13  0  0  0\n        4  0  0  0  6  0  0\n        5  0  3  0  0  4  0\n        6  0  0  0  0  0  5\n```\n\n\n:::\n:::\n\n\nClusters 3, 4 and 6 are identical, and eight townships move between clusters 1, 2 and 5.\n\n::: {.callout-note}\n## hclustgeo() matches ward.D2\n\n`hclustgeo()` applies Ward's criterion to squared distances, which is what `hclust()` calls ward.D2. I ran `hclust(proxmat, method = \"ward.D2\")` and got exactly the same six clusters as `hclustgeo(proxmat)`. The difference above comes from Part 3 using ward.D. The `agnes()` coefficient of 0.943 also belongs to ward.D2, since `agnes(method = \"ward\")` gives the same tree as ward.D2.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_pieces(shan_sf_ngeo_cluster$CLUSTER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 2 3 4 5 6 \n6 5 5 5 6 1 \n```\n\n\n:::\n:::\n\n\nWithout the spatial term these clusters are just as fragmented as before, with only cluster 6 in one piece.\n\n### Spatially constrained hierarchical clustering\n\nD1 is the distance between townships. `st_distance()` returns a matrix of distances between polygons, and `as.dist()` turns it into a `dist` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist <- st_distance(shan_sf, shan_sf)\ndistmat <- as.dist(dist)\n```\n:::\n\n\n`st_distance()` measures from boundary to boundary, so the 132 pairs of townships that share a border all have a distance of 0. The longest distance is about 444 km.\n\n`choicealpha()` runs the clustering for alpha from 0 to 1 in steps of 0.1 and reports how homogeneous the six clusters are in each space.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncr <- choicealpha(proxmat, distmat, range.alpha = seq(0, 1, 0.1), K=6, graph = TRUE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-72-1.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-72-2.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(cbind(cr$Q, cr$Qnorm), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Q0    Q1 Q0norm Q1norm\nalpha=0   0.757 0.131  1.000  0.139\nalpha=0.1 0.740 0.284  0.978  0.301\nalpha=0.2 0.647 0.626  0.855  0.665\nalpha=0.3 0.624 0.692  0.825  0.735\nalpha=0.4 0.527 0.831  0.697  0.882\nalpha=0.5 0.493 0.874  0.652  0.928\nalpha=0.6 0.493 0.874  0.652  0.928\nalpha=0.7 0.480 0.879  0.635  0.934\nalpha=0.8 0.411 0.940  0.543  0.999\nalpha=0.9 0.375 0.918  0.496  0.975\nalpha=1   0.191 0.941  0.252  1.000\n```\n\n\n:::\n:::\n\n\nQ0 measures homogeneity in the ICT variables and Q1 in space, and the normalised versions are scaled to 1 at their best. At alpha = 0, Q0 is 0.757 and Q1 only 0.131. Moving to alpha = 0.2 raises Q1 to 0.626 while Q0 falls to 0.647, or 85 percent of its maximum. Beyond 0.2 the trade gets worse. Alpha = 0.4 gains another 0.2 in normalised Q1 but loses 0.16 in normalised Q0. Following the notes, I use alpha = 0.2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclustG <- hclustgeo(proxmat, distmat, alpha = 0.2)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups <- as.factor(cutree(clustG, k=6))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf_Gcluster <- cbind(shan_sf, as.matrix(groups)) %>%\n  rename(`CLUSTER` = `as.matrix.groups.`)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqtm(shan_sf_Gcluster, \"CLUSTER\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-77-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(shan_sf_Gcluster$CLUSTER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 1  2  3  4  5  6 \n10  9  7  9 12  8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncount_pieces(shan_sf_Gcluster$CLUSTER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1 2 3 4 5 6 \n2 1 5 7 1 2 \n```\n\n\n:::\n:::\n\n\nThe six clusters are more balanced in size than SKATER's, from 7 to 12 townships, and more compact than the non-spatial ones. Clusters 2 and 5 are fully connected, and clusters 1 and 6 form two pieces each. ClustGeo does not force contiguity, though. Cluster 3 still has five pieces and cluster 4 is spread over seven.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf_Gcluster %>%\n  st_drop_geometry() %>%\n  filter(CLUSTER == \"4\") %>%\n  pull(TS.x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Mabein\"    \"Kyaukme\"   \"Muse\"      \"Lashio\"    \"Tachileik\" \"Laukkaing\"\n[7] \"Hseni\"     \"Namhkan\"   \"Taunggyi\" \n```\n\n\n:::\n:::\n\n\nCluster 4 holds the main towns of the state, Taunggyi, Lashio, Kyaukme, Muse, Namhkan, Laukkaing, Tachileik, Hseni and Mabein. Their ICT profiles are so close to each other, and so far from the townships around them, that a spatial weight of 0.2 is not enough to split the group by location. For a planning map this group reads as an urban type, and it would need a separate treatment from the regions around it.\n\nI put the four solutions side by side and compared how much variance each explains.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(qtm(shan_sf_cluster, \"CLUSTER\") + tm_title(\"hclust, ward.D\"),\n             qtm(shan_sf_ngeo_cluster, \"CLUSTER\") + tm_title(\"ClustGeo, alpha = 0\"),\n             qtm(shan_sf_spatialcluster, \"SP_CLUSTER\") + tm_title(\"SKATER\"),\n             qtm(shan_sf_Gcluster, \"CLUSTER\") + tm_title(\"ClustGeo, alpha = 0.2\"),\n             ncol = 2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-80-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(method = c(\"hclust ward.D\", \"ClustGeo alpha = 0\", \"ClustGeo alpha = 0.2\", \"SKATER\"),\n       r_squared = c(r_squared(shan_sf_cluster$CLUSTER),\n                     r_squared(shan_sf_ngeo_cluster$CLUSTER),\n                     r_squared(shan_sf_Gcluster$CLUSTER),\n                     r_squared(shan_sf_spatialcluster$SP_CLUSTER)),\n       pieces_on_map = c(sum(count_pieces(shan_sf_cluster$CLUSTER)),\n                         sum(count_pieces(shan_sf_ngeo_cluster$CLUSTER)),\n                         sum(count_pieces(shan_sf_Gcluster$CLUSTER)),\n                         sum(count_pieces(shan_sf_spatialcluster$SP_CLUSTER)))) %>%\n  mutate(r_squared = round(r_squared, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  method               r_squared pieces_on_map\n  <chr>                    <dbl>         <dbl>\n1 hclust ward.D            0.761            24\n2 ClustGeo alpha = 0       0.757            28\n3 ClustGeo alpha = 0.2     0.647            18\n4 SKATER                   0.5               6\n```\n\n\n:::\n:::\n\n\nThe two non-spatial solutions explain about 76 percent of the variance and break into 24 and 28 pieces on the map. ClustGeo with alpha = 0.2 explains 65 percent with 18 pieces, and SKATER explains 50 percent with exactly 6. ClustGeo sits between the two extremes, which is what the mixing parameter is for.\n\n::: {.callout-important}\n## My takeaway\n\nClustGeo gave me a dial between homogeneity and compactness, and `choicealpha()` made the trade visible. At alpha = 0.2 most regions became compact while keeping 85 percent of the homogeneity. It also showed something SKATER hides, a group of main towns spread across the state that are more like each other than like their neighbours.\n:::\n\n## Part 6, Visual interpretation of clusters\n\nThe notes profile the clusters from `shan_sf_ngeo_cluster`, the ClustGeo solution with alpha = 0, so I used the same object.\n\n### Visualising one clustering variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = shan_sf_ngeo_cluster,\n       aes(x = CLUSTER, y = RADIO_PR)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-82-1.png){width=768}\n:::\n:::\n\n\nCluster 3 has the highest radio ownership, with a median of 278 households per thousand. Cluster 2 follows at 227 and cluster 1 at 205. Cluster 4 is lower at 155, and clusters 5 and 6 are lowest, both with a median of 97.\n\n::: {.callout-warning}\n## The ranking in the notes\n\nThe notes rank the clusters 3, 2, 1, 4, 6 and 5 by mean radio ownership. The means in the summary table at the end of the notes, which I reproduce below, give 3, 2, 1, 4, 5 and 6, with cluster 5 at 124 and cluster 6 at 98.6. The boxplot shows medians, and on medians clusters 5 and 6 are tied.\n:::\n\n### Multivariate visualisation\n\nA parallel coordinate plot shows all five variables at once, with one line per township. `ggparcoord()` from **GGally** draws it, and `facet_grid()` gives each cluster its own panel. Columns 17 to 21 of `shan_sf_ngeo_cluster` are the five clustering variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggparcoord(data = shan_sf_ngeo_cluster, \n           columns = c(17:21), \n           scale = \"globalminmax\",\n           alphaLines = 0.2,\n           boxplot = TRUE, \n           title = \"Multiple Parallel Coordinates Plots of ICT Variables by Cluster\") +\n  facet_grid(~ CLUSTER) + \n  theme(axis.text.x = element_text(angle = 30))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-83-1.png){width=1344}\n:::\n:::\n\n\nCluster 4 stands out with the highest television and mobile phone ownership, and it also leads on land lines and computers. These are the six border and trade towns, Muse, Tachileik, Laukkaing, Mongla, Namhkan and Taunggyi.\n\nCluster 5 has the lowest television, mobile phone and computer rates of all six clusters. The notes say it is lowest on all five items, but cluster 6 has less radio and cluster 2 has fewer land lines.\n\n`scale = \"globalminmax\"` draws the raw values on one shared axis. `ggparcoord()` offers five other options. `std` subtracts the mean and divides by the standard deviation, and `robust` subtracts the median and divides by the median absolute deviation. `uniminmax` rescales each variable to run from 0 to 1. `center` applies uniminmax and then centres each variable on a summary value set by `scaleSummary`, and `centerObs` does the same around one chosen observation set by `centerObsID`.\n\nWith `globalminmax`, television and mobile phones fill most of the height and computers are squashed along the bottom. I also drew the same plot with `uniminmax`, which puts every variable on the same 0 to 1 range.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggparcoord(data = shan_sf_ngeo_cluster, \n           columns = c(17:21), \n           scale = \"uniminmax\",\n           alphaLines = 0.2,\n           boxplot = TRUE, \n           title = \"Parallel Coordinates Plots of ICT Variables by Cluster, uniminmax scale\") +\n  facet_grid(~ CLUSTER) + \n  theme(axis.text.x = element_text(angle = 30))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex06_files/figure-html/unnamed-chunk-84-1.png){width=1344}\n:::\n:::\n\n\nOn this scale the computer rate of cluster 4 becomes visible, and so does the land line profile of cluster 6, which sits fairly high even though its radio rate is the lowest. No scale is best for every purpose, and switching between them helped me read the clusters.\n\n### Summary statistics\n\nI computed the mean of each clustering variable by cluster to back up the plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshan_sf_ngeo_cluster %>% \n  st_set_geometry(NULL) %>%\n  group_by(CLUSTER) %>%\n  summarise(mean_RADIO_PR = mean(RADIO_PR),\n            mean_TV_PR = mean(TV_PR),\n            mean_LLPHONE_PR = mean(LLPHONE_PR),\n            mean_MPHONE_PR = mean(MPHONE_PR),\n            mean_COMPUTER_PR = mean(COMPUTER_PR))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  CLUSTER mean_RADIO_PR mean_TV_PR mean_LLPHONE_PR mean_MPHONE_PR\n  <chr>           <dbl>      <dbl>           <dbl>          <dbl>\n1 1               221.        521.            44.2           246.\n2 2               237.        402.            23.9           134.\n3 3               300.        611.            52.2           392.\n4 4               196.        744.            99.0           651.\n5 5               124.        224.            38.0           132.\n6 6                98.6       499.            74.5           468.\n# ℹ 1 more variable: mean_COMPUTER_PR <dbl>\n```\n\n\n:::\n:::\n\n\nThe six clusters can be read as six ICT profiles. Cluster 4 is the connected urban group, with 744 televisions and 651 mobile phones per thousand households and a computer rate of 65.5. Cluster 3 has the most radios (300) and fairly high television (611). Cluster 6, the Wa townships, has the fewest radios (98.6) but relatively high land line and mobile phone ownership. Cluster 5 is the least connected group, with 224 televisions, 132 mobile phones and 6.7 computers per thousand. Clusters 1 and 2 sit in between, with cluster 2 especially low on land lines (23.9).\n\n## Wrapping up\n\nThe five ICT rates group Shan State's 55 townships into six profiles that range from a connected urban group to a group with very low ownership of every item. Without a spatial constraint these profiles are scattered across the state in 24 to 28 separate pieces. SKATER produced three connected regions, west, centre and eastern border, plus three outlier clusters, at the cost of explaining only 50 percent of the variance. ClustGeo with alpha = 0.2 kept 65 percent, made most clusters compact, and left the main towns together as one scattered urban group.\n",
    "supporting": [
      "Hands-on_Ex06_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}