{
  "hash": "4ca6adfd04084c9043bbc3608a4071a6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Ex03: Spatio-Temporal Point Patterns Analysis\"\nsubtitle: \"Forest fires in Kepulauan Bangka Belitung, 2023\"\nauthor: \"Meng Tingyu\"\ndate: \"September 10, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show the code\"\n    code-tools: true\n    fig-align: center\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  message: false\n  freeze: true\n---\n\n## What this exercise is about\n\nThe previous exercise treated every event as if it had no date attached to it. That is fine when the process is stable over the study period, but it is clearly wrong for something like forest fires, where the whole story is that fires happen in a particular season. A spatio-temporal point process keeps both coordinates, so each event carries a location and a time, and the intensity we estimate becomes a surface that changes as we move through the year.\n\nThe case study is forest fire detections in Kepulauan Bangka Belitung, Indonesia, for the whole of 2023. The two questions I am trying to answer are the ones set out in the chapter.\n\n1. Are the locations of forest fire in Kepulauan Bangka Belitung spatially and spatio-temporally independent?\n2. If they are not, where and when do the observed fire locations tend to cluster?\n\nI work through three things in order. First a spatio-temporal kernel density estimate with month as the time mark, then the same estimate with day of year as the time mark, and finally the space-time inhomogeneous K function from the **stpp** package, which is the part that actually tests independence rather than just describing intensity.\n\n## Setting up\n\n### Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spatstat, sparr, tmap, stpp, tidyverse)\n```\n:::\n\n\nSix packages, each doing one job. **sf** handles import and coordinate reference systems, **spatstat** provides the `ppp` and `owin` classes that everything else is built on, **sparr** does the spatio-temporal kernel smoothing, **stpp** does the K function analysis, **tmap** draws the maps and **tidyverse** does the data wrangling.\n\n::: {.callout-note}\n## The package list in the chapter text and the package list in the code do not match\n\nThe chapter names **raster** among the six packages, but the solution chunk loads **stpp** instead and **raster** is never called anywhere in the workflow. I went with the code rather than the prose. **stpp** is genuinely needed later, **raster** is not, since nothing here touches gridded data directly.\n:::\n\n### The data\n\nTwo files, both sitting under `data/`.\n\n| File | What it is | Source |\n|------|-----------|--------|\n| `forestfires.csv` | MODIS fire detections for 2023, one row per detection, with longitude, latitude and acquisition date, clipped to the province | Fire Information for Resource Management System |\n| `Kepulauan_Bangka_Belitung.gpkg` | Village and sub-district (desa and kelurahan) boundaries of the province, cut out of the national BIG 10K layer | Indonesia Geospatial portal |\n\nI kept the same folder convention as the first two exercises, so the boundary lives in `data/geospatial/` and the csv lives in `data/aspatial/`. Copying the files into this exercise folder rather than pointing at Ex02 means the exercise still renders if I ever reorganise the earlier directories.\n\n::: {.callout-note}\n## The fire csv is also a subset I made myself\n\nFIRMS serves archive requests by bounding box, and the smallest box that contains this province still takes in a slice of southern Sumatra, which burns heavily and would have dominated everything. The raw request for 2023 came back with over fifty thousand detections. I clipped them to the dissolved provincial boundary before saving, using the same geometry that becomes the analysis window later, so the events in `data/` and the window they are analysed in are guaranteed to agree with each other.\n\n```r\nkeep <- raw %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326, remove = FALSE) %>%\n  st_filter(kbb_union) %>%\n  st_drop_geometry()\n```\n\n`remove = FALSE` is the part that is easy to get wrong. Without it `st_as_sf()` consumes the two coordinate columns into the geometry, `st_drop_geometry()` then throws the geometry away, and what gets written out is a csv with no coordinates in it at all.\n:::\n\n::: {.callout-note}\n## Getting the boundary out of a national file\n\nThe portal does not publish this layer province by province. What is on offer is one national shapefile of every desa and kelurahan in Indonesia at 1 to 10000, which unpacks to well over a gigabyte and whose `.shp` alone is far past what GitHub will accept in a single file. So the boundary in `data/` is not the download, it is a subset I cut out of it.\n\nThe cut was done once, outside the repository, by filtering on the province name field with a SQL query at read time rather than reading the whole layer into memory and filtering afterwards.\n\n```r\nshp <- \"D:/BATAS WILAYAH KELURAHAN-DESA 10K/Batas_Wilayah_KelurahanDesa_10K_AR.shp\"\nlyr <- \"Batas_Wilayah_KelurahanDesa_10K_AR\"\n\nkbb <- st_read(shp, query = paste0(\n  'SELECT * FROM \"', lyr, '\" WHERE WADMPR = ', \"'Kepulauan Bangka Belitung'\"))\n\nst_write(kbb, \"data/geospatial/Kepulauan_Bangka_Belitung.gpkg\", delete_dsn = TRUE)\n```\n\nHanding the filter to GDAL matters here. The query is answered against the attribute table on disk and only the matching geometries are ever constructed, which is the difference between a few seconds and running out of memory. I wrote the result as a GeoPackage rather than a shapefile because it is one file instead of four, it has no ten character limit on field names, and there is no way to break it by renaming half of a set.\n:::\n\n## Preparing the study area\n\n### Reading the boundary\n\nThe first version of the import in the chapter is deliberately incomplete.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb <- st_read(\"data/geospatial/Kepulauan_Bangka_Belitung.gpkg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kepulauan_Bangka_Belitung' from data source \n  `D:\\mengtingyu88\\geospatial-coursework\\Hands-on_Ex\\Hands-on_Ex03\\data\\geospatial\\Kepulauan_Bangka_Belitung.gpkg' \n  using driver `GPKG'\nSimple feature collection with 393 features and 26 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 105.1085 ymin: -3.80161 xmax: 108.8718 ymax: -1.493399\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nRunning that and then trying to use the result as a window does not work, and the reason is in the message it prints. The collection has 393 separate features, one per desa or kelurahan, and the CRS is WGS 84, so the coordinates are degrees. Neither of those is what an observation window needs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_sf <- st_read(\"data/geospatial/Kepulauan_Bangka_Belitung.gpkg\") %>%\n  st_union() %>%\n  st_zm(drop = TRUE, what = \"ZM\") %>%\n  st_transform(crs = 32748)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kepulauan_Bangka_Belitung' from data source \n  `D:\\mengtingyu88\\geospatial-coursework\\Hands-on_Ex\\Hands-on_Ex03\\data\\geospatial\\Kepulauan_Bangka_Belitung.gpkg' \n  using driver `GPKG'\nSimple feature collection with 393 features and 26 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 105.1085 ymin: -3.80161 xmax: 108.8718 ymax: -1.493399\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n`st_union()` dissolves the 393 administrative units into one geometry, because a window is a region and not a collection of parcels, and because the internal boundaries between villages have nothing to do with where fires can occur. `st_transform()` moves the data to EPSG 32748, which is UTM zone 48 South and covers this part of Indonesia. That is the step that turns the units into metres, and without it every bandwidth and every distance in the rest of the exercise would be expressed in degrees, which for kernel smoothing is meaningless.\n\n`st_zm()` is the interesting one, because on this particular file it does nothing at all.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry_type(kbb)[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] MULTIPOLYGON\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n\n```{.r .cell-code}\nst_dimension(kbb)[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## The step that fixes a problem my copy of the data does not have\n\nThe chapter's version of this boundary comes back as POLYGON with dimension XYZ, and every Z value in it is zero. `as.owin()` will not take a three dimensional geometry, so `st_zm()` is there to strip a coordinate that carries no information but blocks the conversion. The copy I cut out of the 2024 BIG layer is plain XY MULTIPOLYGON, so the call passes straight through and changes nothing.\n\nI kept it in the pipeline anyway. It costs nothing on two dimensional input, and the same layer redownloaded or re-exported from a different tool could easily come back with the Z restored. Leaving it in means the code does not depend on a property of the file that nobody guaranteed.\n\nThe wider point is about which failures announce themselves. The Z dimension is the loud one, since `as.owin()` stops with an error. The projection is the quiet one, because leaving it out produces a perfectly valid window in degrees and no warning whatsoever, which is the same shape of trap as the CRS mismatch in Ex01. Order matters for the same reason, since unioning after projecting and unioning before projecting both return an answer and only one of them is the one I meant.\n:::\n\n### Converting to an owin object\n\n`spatstat` will not accept an sf object as an observation window, so the geometry has to be converted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_owin <- as.owin(kbb_sf)\nkbb_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow: polygonal boundary\nenclosing rectangle: [512066.8, 930756.9] x [9579205, 9834915] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(kbb_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"owin\"\n```\n\n\n:::\n:::\n\n\nThe enclosing rectangle is now reported in projected units, in the hundreds of thousands, which is the sanity check that the transform actually took effect. If the numbers had come back as small decimals in the range 105 to 109 I would know the CRS step had been skipped.\n\n::: {.callout-note}\n## My window is larger than the chapter's\n\nWorth recording, because it affects every count that follows. The chapter's copy of this boundary reports a bounding box running east only as far as about 106.85 degrees, which covers Bangka and the small islands around it but stops short of Belitung. The subset I cut from the 2024 national layer runs out to about 108.87 degrees and so takes in the whole province, Belitung included.\n\nNeither file is wrong, they are just different extracts sharing a name. The consequence is that my study region is roughly twice the area of the chapter's, so my event count, my average intensity and my bandwidths will not match the numbers printed in the course material, and there is no point in trying to make them match. I went with the full province because that is what the province is, and because clipping the fire data to a window that silently drops half of it would be the worse error.\n:::\n\n## Preparing the fire events\n\n### Reading and projecting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- read_csv(\"data/aspatial/forestfires.csv\") %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"),\n           crs = 4326) %>%\n  st_transform(crs = 32748)\n```\n:::\n\n\nThe csv arrives as plain coordinates with no spatial class, so `st_as_sf()` has to be told which columns hold the coordinates and which CRS those coordinates are in. MODIS output is longitude and latitude in WGS 84, hence 4326, and then the same transform to 32748 puts the events into the same projected space as the window.\n\n### Deriving the temporal marks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf <- fire_sf %>%\n  mutate(DayofYear = yday(acq_date)) %>%\n  mutate(Month_num = month(acq_date)) %>%\n  mutate(Month_fac = factor(month.name[Month_num],\n                            levels = month.name))\n```\n:::\n\n\nThree time fields out of one date. `Month_num` is the numeric month used as the mark for the first density estimate, `DayofYear` is the finer time scale used for the second, and `Month_fac` is a factor used only for panel labels and axis text.\n\n::: {.callout-warning}\n## Month names are localised, and mine are not English\n\nThe obvious way to build the label column is `month(acq_date, label = TRUE, abbr = FALSE)`, which is what the chapter uses. On my machine that returns Chinese month names, because my Windows locale is Chinese, and the facet titles and the bar chart axis came out in a language the rest of the document is not written in.\n\n`month.name` is a built in character constant and is always English regardless of locale, so indexing it by the numeric month sidesteps the problem entirely. This is the same trap as `weekdays()` in the time series exercise last term, and the lesson is the same, which is that any function returning a name rather than a number is a candidate for silent localisation.\n:::\n\n::: {.callout-warning}\n## A ppp mark cannot be a Date\n\nThis is the reason the chapter converts the date at all. `as.ppp()` accepts marks that are numeric, character or factor, and a `Date` column is none of those as far as it is concerned, so passing `acq_date` straight through gives an error. Turning the date into an integer is not just convenience, it is a requirement of the class.\n\nThe second thing to check is that `acq_date` was actually parsed as a date in the first place. `read_csv()` normally recognises the ISO format that MODIS uses, but if the file has been opened and re-saved in Excel the column can come back as character, and then `yday()` fails. `class(fire_sf$acq_date)` before the mutate takes two seconds and saves a confusing error.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(fire_sf %>% select(acq_date, DayofYear, Month_num, Month_fac))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 905\nColumns: 5\n$ acq_date  <date> 2023-01-10, 2023-01-10, 2023-01-10, 2023-01-10, 2023-01-10,…\n$ DayofYear <dbl> 10, 10, 10, 10, 10, 10, 10, 10, 12, 12, 12, 40, 40, 49, 50, …\n$ Month_num <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, …\n$ Month_fac <fct> January, January, January, January, January, January, Januar…\n$ geometry  <POINT [m]> POINT (634310.2 9719333), POINT (661410.6 9683536), PO…\n```\n\n\n:::\n:::\n\n\n## Looking at the points first\n\nBefore smoothing anything I want to see the raw events, because a density surface will always look like something and it is easy to read structure into a plot that the underlying points do not support.\n\n### All fires in 2023\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf) +\n  tm_polygons(fill = \"grey96\",\n              col = \"grey45\",\n              lwd = 0.4) +\n  tm_shape(fire_sf) +\n  tm_dots(size = 0.12,\n          fill = \"#B5563F\",\n          fill_alpha = 0.55) +\n  tm_title(\"Forest fire detections, Kepulauan Bangka Belitung, 2023\") +\n  tm_layout(frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-10-1.png){width=768}\n:::\n:::\n\n\nThe province is an archipelago, with Bangka to the west and Belitung to the east, and the detections are not spread evenly across either island. There is an obvious concentration on Bangka, particularly through the middle and the south, while Belitung carries far fewer points.\n\n### Month by month\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kbb_sf) +\n  tm_polygons(fill = \"grey96\",\n              col = \"grey45\",\n              lwd = 0.3) +\n  tm_shape(fire_sf) +\n  tm_dots(size = 0.1,\n          fill = \"#B5563F\",\n          fill_alpha = 0.6) +\n  tm_facets(by = \"Month_fac\",\n            free.coords = FALSE)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-11-1.png){width=1056}\n:::\n:::\n\n\n::: {.callout-note}\n## tmap v4 and the facet arguments in the course code\n\nThe course code passes `free.coords = FALSE` and `drop.units = TRUE` to `tm_facets()`. On my machine, running tmap 4.4, `free.coords` behaves as expected but `drop.units` is no longer needed here, since there is only one polygon in the window after the union and there are no units to drop. This is the same v3 to v4 translation problem I ran into in the first two exercises, and the fix is usually to strip the argument rather than to look for a renamed version of it.\n:::\n\nThe panels make the seasonality obvious. The first half of the year is nearly empty, the pattern builds from July, and August through October carry the bulk of the year's events. The counts in the next section put numbers on that.\n\n### Counting the events\n\nThe maps show where, but they are hard to read for how many, so a simple count makes the temporal shape explicit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf %>%\n  st_drop_geometry() %>%\n  count(Month_fac) %>%\n  ggplot(aes(x = Month_fac, y = n)) +\n  geom_col(fill = \"#B5563F\", width = 0.7) +\n  geom_text(aes(label = n), vjust = -0.4, size = 3.2, colour = \"grey30\") +\n  labs(title = \"Forest fire detections by month, 2023\",\n       x = NULL, y = \"Detections\") +\n  theme_minimal(base_size = 11) +\n  theme(panel.grid.major.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-12-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_sf %>%\n  st_drop_geometry() %>%\n  summarise(n = n(),\n            first_day = min(DayofYear),\n            median_day = median(DayofYear),\n            last_day = max(DayofYear))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n first_day median_day last_day\n  <int>     <dbl>      <dbl>    <dbl>\n1   905        10        258      360\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n905 detections in total, with a median day of year of 258, which falls in September. The first quartile sits at day 220 and the third at day 288, so half of the year's fires happen inside a window of about 10 weeks running from 08 August to 15 October. That is the dry season, and it means any density estimate that ignores time is averaging a very busy quarter against eight quiet months.\n\n::: {.callout-tip}\n## My takeaway\n\nDoing the counts before the smoothing changed how I read everything afterwards. A spatial-only KDE of these 905 points would have produced a perfectly reasonable looking hotspot map, and I would have had no way of knowing from the map itself that almost the entire surface is being driven by three months of the year. The temporal margin is cheap to compute and it sets the expectation for what the spatio-temporal estimate should show.\n:::\n\n## Spatio-temporal KDE by month\n\n### Building the marked ppp\n\n`as.ppp()` only wants the mark column and the geometry, so everything else has to go first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month <- fire_sf %>%\n  select(Month_num)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_ppp <- as.ppp(fire_month)\nfire_month_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 905 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [521564.1, 862416.4] x [9642001, 9828767] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fire_month_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  905 points\nAverage intensity 1.421623e-08 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   8.000   9.000   8.644  10.000  12.000 \n\nWindow: rectangle = [521564.1, 862416.4] x [9642001, 9828767] units\n                    (340900 x 186800 units)\nWindow area = 63659700000 square units\n```\n\n\n:::\n:::\n\n\nThe summary confirms the marks are numeric and run from 1 to 12, with a median of 9 and a mean of 8.64, which is the same seasonal peak seen in the bar chart, expressed differently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(fire_month_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\nNo duplicates, so unlike the childcare centre data in Ex02 there is no need to jitter anything. That makes sense given MODIS detections are pixel centroids recorded at particular acquisition times, and two fires being flagged at exactly the same pixel on exactly the same date would be unusual.\n\n### Clipping to the window\n\nAt this point the ppp still sits inside a rectangle. Attaching the real window is what makes the intensity estimate meaningful, because intensity is events per unit area and the rectangle contains a great deal of sea.\n\nI print the pattern itself rather than calling `summary()` on it. The chapter uses `summary()`, and on a single island that is fine, but this window is an archipelago and `summary.owin` lists every component polygon with its vertex count and area, which here means hundreds of lines of table in the middle of the document. The two numbers I actually want are cheaper to compute directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_month_owin <- fire_month_ppp[kbb_owin]\nfire_month_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 905 points\nmarks are numeric, of storage type  'double'\nwindow: polygonal boundary\nenclosing rectangle: [512066.8, 930756.9] x [9579205, 9834915] units\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_poly <- length(kbb_owin$bdry)\nn_vert <- sum(sapply(kbb_owin$bdry, function(b) length(b$x)))\nc(polygons = n_poly,\n  vertices = n_vert,\n  frame_over_window = round(area(Frame(fire_month_ppp)) / area(kbb_owin), 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         polygons          vertices frame_over_window \n           536.00         147452.00              3.81 \n```\n\n\n:::\n:::\n\n\nAll 905 points survive the clip, so nothing in the file falls outside the province, which confirms that my own filtering step did what it was supposed to. What does change is the denominator. The window resolves into 536 separate polygons carrying 147,452 vertices between them, which is what a province made of two large islands and a great many small ones looks like once the administrative lines are dissolved away. Its total area is about 3.8 times smaller than the bounding rectangle, so average intensity rises by that factor. Nothing about the pattern changed, only the area we are dividing by.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_month_owin, main = \"Fire events within the study window\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n### Estimating the density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_kde <- spattemp.density(fire_month_owin)\nsummary(st_kde)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 19110 (spatial)\n  lambda = 0.0264 (temporal)\n\nNo. of observations\n  905 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 930756.9] x [9579205, 9834915]\n\nTemporal bound\n  [1, 12]\n\nEvaluation\n  128 x 128 x 12 trivariate lattice\n  Density range: [2.515909e-36, 6.317034e-10]\n```\n\n\n:::\n:::\n\n\nTwo bandwidths come back, a spatial one and a temporal one. The spatial bandwidth is about 19.1 kilometres, which against a province spanning over four hundred kilometres from end to end is a fairly local scale. The temporal bandwidth is 0.0264, and since the time unit here is a month, that works out at roughly 0.8 days.\n\n::: {.callout-important}\n## The temporal bandwidth here is effectively no smoothing at all\n\nThis surprised me and it is worth being explicit about. Because the marks are integers, all the events in August sit at exactly t equals 8, and a kernel this narrow does not reach anywhere near t equals 7 or t equals 9. The result is that each monthly slice is essentially a plain spatial KDE of that month's events, with almost no borrowing of information from neighbouring months.\n\nThat is not a bug in `spattemp.density()`, it is a consequence of feeding it a coarsely discretised time variable. The bandwidth rule sees twelve tied values and concludes that very little smoothing is required. It also means the twelve month version is not really a spatio-temporal estimate in any interesting sense, and the day of year version in the next section is the one that actually smooths across time.\n:::\n\n### Plotting July to December\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntims <- c(7, 8, 9, 10, 11, 12)\npar(mfcol = c(2, 3))\nfor (i in tims) {\n  plot(st_kde, i,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"KDE at month\", i))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-23-1.png){width=1152}\n:::\n:::\n\n\n`fix.range = TRUE` is doing important work in that loop. It holds the colour scale constant across all six panels, so a warm colour in one panel means the same density as a warm colour in another. Without it each panel is scaled to its own maximum and November would look as active as September, which would be badly misleading. `override.par = FALSE` stops the plot method from resetting the panel layout on each call, which is what allows `par(mfcol = c(2, 3))` to hold for all six.\n\nReading the six panels, July is already showing raised intensity in central and southern Bangka. August and September are the peak, with the strongest values concentrated in the southern half of Bangka and a secondary area appearing on Belitung. October is still elevated but the surface is flatter and the focus has shifted slightly. November is not as quiet as the earlier panels led me to expect, with 103 detections, so there is a secondary period of activity after the main season closes, and only December really empties out at 13.\n\n## Spatio-temporal KDE by day of year\n\n### The ppp and the window\n\nSame procedure, finer time mark.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_ppp <- fire_sf %>%\n  select(DayofYear) %>%\n  as.ppp()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_yday_owin <- fire_yday_ppp[kbb_owin]\nfire_yday_owin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 905 points\nmarks are numeric, of storage type  'double'\nwindow: polygonal boundary\nenclosing rectangle: [512066.8, 930756.9] x [9579205, 9834915] units\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(marks(fire_yday_owin))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   10.0   220.0   258.0   247.8   288.0   360.0 \n```\n\n\n:::\n:::\n\n\nThe marks now range from day 10 to day 360 with a mean of 247.8, and the window is identical to before because only the mark changed.\n\n### Estimating the density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday <- spattemp.density(fire_yday_owin)\nsummary(kde_yday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 19110 (spatial)\n  lambda = 6.4541 (temporal)\n\nNo. of observations\n  905 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 930756.9] x [9579205, 9834915]\n\nTemporal bound\n  [10, 360]\n\nEvaluation\n  128 x 128 x 351 trivariate lattice\n  Density range: [2.75665e-27, 1.874119e-12]\n```\n\n\n:::\n:::\n\n\nThe spatial bandwidth is unchanged at 19.1 kilometres, which it should be, since the spatial configuration of the points is exactly the same. The temporal bandwidth is now 6.45 days, so the estimate is pooling roughly a fortnight of activity around each evaluation time. That is a real amount of temporal smoothing and it is already far more useful than the near-zero bandwidth the monthly version produced, although the next section shows that it is still narrower than it should be.\n\nThe evaluation lattice is also very different, with one slice per day instead of one per month, and the maximum density drops by more than two orders of magnitude against the monthly estimate. The two numbers are not comparable, because a spatio-temporal density integrates to one over space and time, and spreading that over the days of the year instead of twelve months necessarily makes the values smaller. Comparing raw density values across the two estimates would be a mistake.\n\n::: {.callout-warning}\n## Do not call plot() on this object without a time argument\n\nThe chapter shows `plot(kde_yday)` with nothing else. In an interactive session that runs an animation through one time slice per day of the study period, pausing between frames, which is a reasonable thing to look at once. Inside a Quarto render it is not, because every frame becomes a separate figure in the output and the document balloons.\n\nI hit this the first time I rendered and killed the process partway through. The fix is to name the days I actually want, exactly as the monthly section does, and let the animation stay in the console.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndays <- yday(seq(as.Date(\"2023-07-15\"), by = \"month\", length.out = 6))\npar(mfcol = c(2, 3))\nfor (d in days) {\n  plot(kde_yday, d,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"KDE at day\", d))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-27-1.png){width=1152}\n:::\n:::\n\n\nI took the middle of each month from July to December and converted those dates to day of year, which lines up with the monthly panels above and makes the two sets comparable. The picture is consistent with the monthly version but smoother, and the transition between the active period and the quiet one is now visible as a gradual decay rather than as a step between panels. The middle panel, day 258, carries the highest values, and by day 319 the surface has almost flattened out.\n\n## Improving the day of year estimate with bootstrap bandwidths\n\nEverything above used the bandwidths `spattemp.density()` chose on its own, which are rule of thumb values. **sparr** also provides `BOOT.spattemp()`, which selects both bandwidths by bootstrap estimation of the mean integrated squared error, returning one isotropic scalar bandwidth for space and one scalar bandwidth for time. On a strongly seasonal process a rule of thumb is a starting point rather than an answer, so this is worth doing properly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbt <- BOOT.spattemp(fire_yday_owin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInitialising...Done.\nOptimising...\nh = 19110 \b; lambda = 14.87514 \nh = 21021 \b; lambda = 14.87514 \nh = 19110 \b; lambda = 1925.875 \nh = 19587.75 \b; lambda = 970.375 \nh = 19826.62 \b; lambda = 492.625 \nh = 19946.06 \b; lambda = 253.7501 \nh = 20005.78 \b; lambda = 134.3126 \nh = 20035.64 \b; lambda = 74.59388 \nh = 20050.57 \b; lambda = 44.73451 \nh = 20058.03 \b; lambda = 29.80482 \nh = 20061.76 \b; lambda = 22.33998 \nh = 21972.76 \b; lambda = 22.33998 \nh = 23404.15 \b; lambda = 26.0724 \nh = 22444.91 \b; lambda = 33.53725 \nh = 21376.98 \b; lambda = 19.54067 \nh = 24719.36 \b; lambda = 23.27309 \nh = 27048.16 \b; lambda = 23.73964 \nh = 29075.33 \b; lambda = 30.27138 \nh = 27150.74 \b; lambda = 27.5887 \nh = 32719.34 \b; lambda = 27.93861 \nh = 37376.93 \b; lambda = 28.87172 \nh = 35349.76 \b; lambda = 22.33998 \nh = 38486.98 \b; lambda = 18.37428 \nh = 48815.75 \b; lambda = 23.50636 \nh = 43373.85 \b; lambda = 23.56468 \nh = 44483.9 \b; lambda = 13.06725 \nh = 42707.16 \b; lambda = 17.01837 \nh = 47594.03 \b; lambda = 22.20876 \nh = 45317.27 \b; lambda = 21.25014 \nh = 44650.57 \b; lambda = 14.70383 \nh = 43693.03 \b; lambda = 21.34947 \nh = 46303.15 \b; lambda = 25.58125 \nh = 43606.15 \b; lambda = 19.15909 \nh = 45230.39 \b; lambda = 19.05976 \nh = 45999.07 \b; lambda = 17.91491 \nh = 43519.28 \b; lambda = 16.9687 \nh = 44867.77 \b; lambda = 20.17978 \nDone.\n```\n\n\n:::\n\n```{.r .cell-code}\nbt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          h      lambda \n45230.39047    19.05976 \n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Set the seed, and expect this chunk to take a while\n\nTwo practical points. The routine is stochastic, so without `set.seed()` the optimiser lands on slightly different values every run and the numbers quoted in the prose stop matching the numbers in the output. Seeding it is not optional in a document that is meant to be reproducible.\n\nThe second point is runtime. This is a bootstrap over 905 events on a lattice with one slice per day and it took several minutes on my machine, with the optimiser printing every candidate pair as it goes. Because the site renders with `freeze` enabled it only pays that cost once, but it is worth knowing before assuming the render has hung.\n:::\n\nThe optimiser starts from the rule of thumb pair, throws lambda out to an enormous value on an early probe, and then works its way back down, wandering through both coordinates before settling. What it lands on is h of about 45.2 kilometres and lambda of about 19.1 days. Both are larger than the rule of thumb pair, by factors of about 2.4 in space and 3 in time.\n\nI had expected the two to disagree in direction, and they do not. The bootstrap says the rule of thumb undersmoothed in both dimensions at once, and the spatial correction is the larger surprise, since a bandwidth of 45.2 kilometres is a substantial fraction of the width of Bangka itself. What that amounts to is a judgement about how much structure 905 events spread across a province this size can actually support. The rule of thumb was resolving features that, on a bootstrap estimate of the mean integrated squared error, are more likely to be noise than signal.\n\n### Recomputing the density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_yday2 <- spattemp.density(fire_yday_owin,\n                              h = round(bt[[\"h\"]], -2),\n                              lambda = round(bt[[\"lambda\"]]))\nsummary(kde_yday2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatiotemporal Kernel Density Estimate\n\nBandwidths\n  h = 45200 (spatial)\n  lambda = 19 (temporal)\n\nNo. of observations\n  905 \n\nSpatial bound\n  Type: polygonal\n  2D enclosure: [512066.8, 930756.9] x [9579205, 9834915]\n\nTemporal bound\n  [10, 360]\n\nEvaluation\n  128 x 128 x 351 trivariate lattice\n  Density range: [5.296593e-16, 9.925739e-13]\n```\n\n\n:::\n:::\n\n\nThe values are rounded off, to the nearest hundred metres and the nearest day, which is what the chapter does and which is reasonable given the optimiser is only accurate to within its own tolerance anyway. Carrying five significant figures on a bootstrapped bandwidth would suggest a precision that is not there.\n\n::: {.callout-note}\n## The chapter overwrites kde_yday, I did not\n\nThe course code reassigns the result to `kde_yday`, which replaces the rule of thumb estimate computed in the previous section. I kept the two under separate names so that both remain in memory and the comparison below actually works. If you follow the chapter literally and then scroll back up, the earlier summary and the object no longer agree with each other, which is the kind of thing that makes a rendered document quietly inconsistent with itself.\n:::\n\nComparing the two summaries, the maximum density roughly halves, which is what spreading the same total mass over a wider kernel does, and the minimum rises by more than ten orders of magnitude. That second number is the more telling one. Under the narrow bandwidths the quiet parts of the year and the far corners of the province were being assigned effectively zero density, because nothing was close enough in either space or time to contribute anything at all. With the wider pair every point now borrows something from its surroundings, so the surface never collapses to nothing.\n\n### Plotting the improved estimate\n\nThe same warning about `plot()` applies here, since this object has the same one slice per day lattice, so I name the days again rather than letting it animate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfcol = c(2, 3))\nfor (d in days) {\n  plot(kde_yday2, d,\n       override.par = FALSE,\n       fix.range = TRUE,\n       main = paste(\"Bootstrap KDE at day\", d))\n}\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-30-1.png){width=1152}\n:::\n:::\n\n\nSet against the six panels from the previous section, the surfaces are broader and the separate cores have merged into larger regions, which is the wider spatial bandwidth doing its work, and the change from panel to panel is gentler, which is the wider temporal one. The peak sits in the same place and the same part of the year, so the substantive answer has not moved. What has changed is how much detail I am willing to believe in it, and the answer is a good deal less.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(kde_yday, days[3], override.par = FALSE, fix.range = TRUE,\n     main = paste(\"Day\", days[3], \"rule of thumb\"))\nplot(kde_yday2, days[3], override.par = FALSE, fix.range = TRUE,\n     main = paste(\"Day\", days[3], \"bootstrap\"))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-31-1.png){width=1056}\n:::\n:::\n\n\nSide by side at the same day the difference is clear enough. The left panel resolves several distinct cores with cooler ground between them, while the right panel merges them into one broad region and the outlying islands are no longer separated from the main mass. One caveat on reading this pair, `fix.range` holds the colour scale constant within each object across its own time slices, and it does not harmonise the scale between two different objects, so the two panels should be compared on shape and not on colour.\n\n::: {.callout-tip}\n## My takeaway\n\nTwo separate lessons landed in this section of the exercise, and they point in different directions.\n\nThe first is that the gap between the monthly and the daily estimates was entirely about how I encoded time, not about the fires. Same 905 events, same locations, same spatial bandwidth, and two very different temporal resolutions purely because one version rounded every date to a month first. Aggregating a continuous variable before handing it to a smoother throws away exactly the information the smoother exists to use, and the bandwidth selector then quietly agrees that there is nothing left to smooth.\n\nThe second is that even with the time variable encoded properly, the default bandwidths were too narrow in both dimensions, and by a wide margin in space. I would not have caught that by eye, because the rule of thumb surface looked entirely plausible on its own, and if anything it looked more informative, since more structure reads as more insight. It only became visible once there was a second surface to hold it against. That is an argument for running the bootstrap as a matter of course rather than treating it as an optional refinement, and a caution against trusting a hotspot map because it has a lot of hotspots on it.\n:::\n\n## Spatio-temporal point pattern analysis with stpp\n\nEverything so far describes intensity. None of it answers the first research question, which is about independence, and for that I need a second order summary. The **stpp** package provides the space-time inhomogeneous K function, which compares the observed number of events within a spatial distance u and a temporal lag v against what would be expected if space and time were independent of one another.\n\n### Building the stpp object\n\n**stpp** does not read sf objects, so the coordinates have to be pulled out into a plain data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(fire_sf)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_df <- data.frame(\n  x = coords[, 1],\n  y = coords[, 2],\n  t = fire_sf$`DayofYear`)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfire_stpp <- as.3dpoints(fire_df)\nclass(fire_stpp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"stpp\"\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## The function is as.3dpoints, with an s\n\nThe chapter text refers to `as.3dpoint()` in the sentence above the code chunk while the code chunk itself calls `as.3dpoints()`. The plural form is the one that exists. Small thing, but it cost me a minute of wondering whether the package had failed to load properly.\n\nThe other detail in that step is that `t` has to be an integer. This is why `DayofYear` is used rather than the date, and it is the same constraint that applied to the ppp marks earlier.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fire_stpp)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex03_files/figure-html/unnamed-chunk-35-1.png){width=960}\n:::\n:::\n\n\nThe default plot gives the spatial configuration alongside the temporal one, with the time dimension shown as a cumulative count. The cumulative curve is the clearest single picture of the seasonality in this whole exercise, flat until around day 180, steep from day 200 to day 300, and flat again after that.\n\n### The space-time inhomogeneous K function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbb_stik <- STIKhat(fire_stpp)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotK(kbb_stik)\n```\n:::\n\n\nThe contour plot shows the estimated K function over a grid of spatial distances u on one axis and temporal lags v on the other. The version below plots the departure from the theoretical value under independence, which I find easier to read because the reference level is zero rather than a curved surface.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotK(kbb_stik, L = TRUE)\n```\n:::\n\n\n### Reading the plot\n\nThe guide gives the rule for interpreting this, and the two cases are straightforward. High values at small u and small v mean events are occurring close together in both space and time, which is clustering. Contours that are flat or low indicate something closer to a random arrangement at those distances.\n\nWhat I see here is that the values are highest in the bottom left corner of the plot, at the shortest spatial distances and the shortest temporal lags, and that they fall away as either axis increases. The contour lines are packed tightly near the origin and spread out further along, which says the clustering is concentrated at short range and decays fairly quickly rather than persisting across the whole study region and the whole year. Reading along the u axis at a fixed small v, the excess is substantial for the first part of the range and then thins out. Reading along the v axis at a fixed small u, the same shape appears, so fires that are near each other in space also tend to be near each other in time.\n\nThat is the answer to both research questions, and it is consistent with the density surfaces. The events are neither spatially nor spatio-temporally independent, and the clustering sits in southern and central Bangka during the August to October window.\n\n::: {.callout-important}\n## The default study region is a box, not the archipelago\n\nThis is the limitation I would flag if I were handing this analysis to anyone. When `s.region` is not supplied, `STIKhat()` falls back on a rectangle derived from the coordinates, and for an archipelago that rectangle contains a large amount of sea where a fire can never occur. Any K function estimate compares the observed pattern against what would be expected under independence within the region it thinks it is working in, so an inflated region inflates the apparent clustering.\n\nPassing the real boundary is possible in principle, since `STIKhat()` accepts a two column matrix of polygon vertices, but the dissolved boundary here is 536 disconnected polygons carrying 147,452 vertices, and the function expects a single simple polygon. Simplifying it heavily with `st_simplify()` would be the practical route. I have not done that here because it changes the region enough that the result would no longer be comparable to the chapter's, but the direction of the bias is clear, and I would expect the true departure from independence to be smaller than what this plot shows.\n\nThe same criticism does not apply to the **sparr** estimates earlier, since those were clipped to `kbb_owin` properly.\n:::\n\n::: {.callout-tip}\n## My takeaway\n\nThe KDE surfaces and the K function are answering different questions and I had been treating them as interchangeable. A density map tells me where the events are concentrated, and it will produce a hotspot even if the process is completely random, because random patterns have lumps in them. The K function is the part that asks whether the lumps are more pronounced than randomness would produce. Ex02 made that point for the purely spatial case, and this chapter extends it to time, where the intuition is less obvious because a seasonal peak feels like it must be clustering when in fact it could just be a non-constant background rate.\n:::\n\n## Where this leaves the two questions\n\nOn the first question, the fire locations are not independent, either spatially or spatio-temporally. The K function sits above the independence reference across short distances and short lags, and the departure is largest where both are small.\n\nOn the second question, the clustering is concentrated on Bangka rather than Belitung, with the strongest and most persistent intensity in the central and southern parts of the island, and it is concentrated in time between roughly day 200 and day 300, which runs from the middle of July to the end of October. All three density estimates put the single most active point in the same part of September and the same part of Bangka. The bootstrap version smooths the cores together rather than relocating them, which is the reassuring outcome, since the answer would be much weaker if the position of the peak depended on the bandwidth.\n\nThe caveat attached to all of this is the region problem described above. The location and timing of the clustering are robust, since they come from the density surfaces, which were clipped to the correct window. The strength of the departure from independence is the part I would not want to quote without redoing the K function on a properly specified region.\n\n## What I would change on a second pass\n\nTwo things. I would encode time as day of year from the beginning and run `BOOT.spattemp()` before drawing anything, since the monthly estimate turned out to be an artefact of aggregation and the rule of thumb estimate turned out to be undersmoothed in both dimensions, and keeping all three in the document is only worthwhile because the contrast is instructive. And I would spend the time simplifying the boundary polygon down to something `STIKhat()` will accept, because a second order statistic computed on the wrong region is not really a second order statistic.\n\n## About this document\n\nWritten in Quarto and executed in R. Every figure and table is generated at render time from the files in `data/`, and no numbers are typed by hand into the prose.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.3 (2026-03-11 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=Chinese (Simplified)_China.utf8 \n[2] LC_CTYPE=Chinese (Simplified)_China.utf8   \n[3] LC_MONETARY=Chinese (Simplified)_China.utf8\n[4] LC_NUMERIC=C                               \n[5] LC_TIME=Chinese (Simplified)_China.utf8    \n\ntime zone: Asia/Shanghai\ntzcode source: internal\n\nattached base packages:\n[1] tcltk     stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] lubridate_1.9.5        forcats_1.0.1          stringr_1.6.0         \n [4] dplyr_1.2.1            purrr_1.2.2            readr_2.2.0           \n [7] tidyr_1.3.2            tibble_3.3.1           ggplot2_4.0.2         \n[10] tidyverse_2.0.0        stpp_2.0-8             splancs_2.01-45       \n[13] sp_2.2-1               rpanel_1.1-6.3         tmap_4.4              \n[16] sparr_2.3-16           spatstat_3.6-2         spatstat.linnet_3.5-3 \n[19] spatstat.model_3.7-2   rpart_4.1.24           spatstat.explore_3.8-2\n[22] nlme_3.1-168           spatstat.random_3.5-1  spatstat.geom_3.8-2   \n[25] spatstat.univar_3.2-0  spatstat.data_3.1-9    sf_1.1-1              \n\nloaded via a namespace (and not attached):\n [1] DBI_1.3.0             deldir_2.0-4          gridExtra_2.3        \n [4] tmaptools_3.3         s2_1.1.11             logger_0.4.2         \n [7] rlang_1.2.0           magrittr_2.0.5        otel_0.2.0           \n[10] e1071_1.7-17          compiler_4.5.3        mgcv_1.9-4           \n[13] png_0.1-9             vctrs_0.7.3           crayon_1.5.3         \n[16] pkgconfig_2.0.3       wk_0.9.5              fastmap_1.2.0        \n[19] labeling_0.4.3        lwgeom_0.2-16         leafem_0.2.5         \n[22] rmarkdown_2.31        tzdb_0.5.0            spacesXYZ_1.6-0      \n[25] bit_4.6.0             xfun_0.57             jsonlite_2.0.0       \n[28] goftest_1.2-3         spatstat.utils_3.2-4  terra_1.9-27         \n[31] parallel_4.5.3        R6_2.6.1              stringi_1.8.7        \n[34] RColorBrewer_1.1-3    stars_0.7-2           Rcpp_1.1.1-1.1       \n[37] iterators_1.0.14      knitr_1.51            tensor_1.5.1         \n[40] base64enc_0.1-6       pacman_0.5.1          timechange_0.4.0     \n[43] Matrix_1.7-4          splines_4.5.3         tidyselect_1.2.1     \n[46] rstudioapi_0.18.0     abind_1.4-8           yaml_2.3.12          \n[49] maptiles_0.11.0       doParallel_1.0.17     codetools_0.2-20     \n[52] misc3d_0.9-2          lattice_0.22-9        leafsync_0.1.0       \n[55] withr_3.0.2           S7_0.2.1-1            evaluate_1.0.5       \n[58] units_1.0-1           proxy_0.4-29          polyclip_1.10-7      \n[61] pillar_1.11.1         KernSmooth_2.23-26    foreach_1.5.2        \n[64] generics_0.1.4        vroom_1.7.1           hms_1.1.4            \n[67] scales_1.4.0          class_7.3-23          glue_1.8.1           \n[70] tools_4.5.3           leaflegend_1.2.8      data.table_1.18.2.1  \n[73] rgl_1.3.36            XML_3.99-0.23         grid_4.5.3           \n[76] crosstalk_1.2.2       colorspace_2.1-2      cols4all_0.10        \n[79] raster_3.6-32         cli_3.6.6             spatstat.sparse_3.2-0\n[82] plot3D_1.4.2          gtable_0.3.6          digest_0.6.39        \n[85] classInt_0.4-11       htmlwidgets_1.6.4     farver_2.1.2         \n[88] htmltools_0.5.9       lifecycle_1.0.5       leaflet_2.2.3        \n[91] bit64_4.6.0-1         microbenchmark_1.5.0 \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Hands-on_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}