{
  "hash": "caefeeebd446819399e7003902b899e7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Spatial and Spatio-temporal Patterns of Road Traffic Fatalities in the Bangkok Metropolitan Region, 2024\"\nauthor: \"Meng Tingyu\"\ndate: \"26 September 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    code-tools: true\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  message: false\n---\n\n# Introduction\n\nRoad crashes kill thousands of people in Thailand every year, and the Bangkok Metropolitan Region (BMR) is where traffic, population and road infrastructure are most concentrated. In this exercise I use the Thailand Road Accident Fatalities 2024 dataset to study where and when fatal crashes happened in the BMR between January and September 2024, and whether crash locations show any interaction with each other. Crashes happen on roads, so I analyse them on the road network itself, using network kernel density estimation and network K- and G-functions.\n\n\n## Research questions\n\n1. How does the intensity of fatal crashes vary across the BMR and across the months of the observation period?\n2. Do fatal crash locations cluster, repel or behave randomly along the road network, and at what network distances?\n3. Do fatal crashes that occur close together in space also occur close together in time?\n4. What do these patterns mean for road-safety planning in the BMR, and where does the evidence stop?\n\n# Data and Study Design\n\n## Getting started\n\nI load all packages with `pacman::p_load()`, which installs anything missing before loading it. `sf` (Pebesma, 2018) handles vector data, `tidyverse` (Wickham et al., 2019) and `lubridate` (Grolemund & Wickham, 2011) handle tables and dates, `spNetwork` (Gelb, 2021) provides the network point-pattern methods, `tmap` (Tennekes, 2018) draws the maps and `knitr` renders the tables. I also call `igraph` (Csardi & Nepusz, 2006) and `sfheaders` through their namespaces for a few network-building steps. Both are installed with `spNetwork`.\n\nThe network K-function simulations and the Knox permutations use random numbers. Each of them runs after a `set.seed(2024)` call, so the results can be reproduced exactly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tidyverse, lubridate, spNetwork, tmap, knitr)\n```\n:::\n\n\n## Data sources\n\n| Dataset | Source | Accessed | Coverage | Format | Key characteristics |\n|---|---|---|---|---|---|\n| Thailand Road Accident Fatalities 2024 | Kaggle, <https://www.kaggle.com/datasets/pornsakkamchan/thailand-road-accident-fatalities-2024>, compiled by Thailand's Department of Disease Control from three data sources | 20 September 2026 | Thailand, deaths confirmed 1 Jan to 30 Sep 2024 | CSV, UTF-8, Thai-language values | One row per fatality, 13 variables, crash coordinates for about a quarter of records |\n| geoBoundaries Thailand ADM1 (gbOpen) | <https://www.geoboundaries.org> (Runfola et al., 2020) | 26 September 2026 | Thailand, 77 provinces | GeoJSON, WGS 84 | Province polygons used to build the study window |\n| OpenStreetMap roads | Geofabrik, <https://download.geofabrik.de/asia/thailand.html> (OpenStreetMap contributors, 2026) | 26 September 2026 | Thailand | Shapefile, WGS 84, layer `gis_osm_roads_free_1` | One line per OSM way, road type in `fclass`, ODbL licence |\n\n: Core datasets {#tbl-sources}\n\nThe raw OSM shapefile is larger than 1 GB, so it is excluded from the GitHub repository. The code in the road network section rebuilds the clipped road layer from it when the layer is missing.\n\n## Importing the fatality data\n\nI read the CSV with `read_csv()` and check its structure with `glimpse()`. Several columns hold Thai text, so the file has to be read as UTF-8.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_raw <- read_csv(\"data/raw/thailand_road_accident_fatalities_2024.csv\",\n                    show_col_types = FALSE)\nglimpse(acc_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 12,762\nColumns: 13\n$ age                  <dbl> 49, 59, 15, 19, 44, 61, 14, 9, 46, 56, 31, 37, 42…\n$ sex                  <chr> \"ชาย\", \"หญิง\", \"ชาย\", \"ชาย\", \"ชาย\", \"ชาย\", \"หญิง\", …\n$ nationality          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ person_district      <chr> \"ขนอม\", \"พล\", \"บัวเชด\", \"แม่สอด\", \"ชานุมาน\", \"วิเศษชัย…\n$ person_province      <chr> \"นครศรีธรรมราช\", \"ขอนแก่น\", \"สุรินทร์\", \"ตาก\", \"อำนาจเจ…\n$ confirmed_death_date <chr> \"11/01/2567\", \"13/03/2567\", \"30/06/2567\", \"02/07/…\n$ acc_sub_district     <chr> \"ขนอม\", \"เมืองพล\", \"ละลม\", \"หางน้ำสาคร\", \"ป่าก่อ\", \"ม่ว…\n$ acc_district         <chr> \"ขนอม\", \"พล\", \"ภูสิงห์\", \"เมืองชัยนาท\", \"ชานุมาน\", \"เมือ…\n$ province_of_death    <chr> \"นครศรีธรรมราช\", \"ขอนแก่น\", \"ศรีสะเกษ\", \"ชัยนาท\", \"อำน…\n$ acc_lat              <dbl> 99.85735, NA, 104.01363, 100.18037, NA, 100.33543…\n$ acc_long             <dbl> 9.182572, NA, 14.567701, 15.295001, NA, 14.627385…\n$ cause_code           <chr> \"V899\", \"V031\", \"V892\", \"V244\", \"Y349\", \"V892\", \"…\n$ vehicle_type         <chr> \"รถจักรยานยนต์\", \"คนเดินเท้า\", \"รถจักรยานยนต์\", \"รถจักรย…\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Pitfall: Thai text and file encoding\n\nThe Thai values only match my lookup tables if both the CSV and this `.qmd` file are read as UTF-8. R 4.2 and later use UTF-8 on Windows by default. If every translated value comes back as `NA`, the first thing I check is the encoding of the `.qmd` file.\n:::\n\n## Data quality assessment\n\n### Missing values\n\nI count missing values in every column before cleaning anything, so each later decision can be traced back to a documented problem.\n\n\n::: {#tbl-missing .cell tbl-cap='Missing values by variable (raw data)'}\n\n```{.r .cell-code}\nmissing_tbl <- acc_raw %>%\n  summarise(across(everything(), ~ sum(is.na(.x)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_missing\") %>%\n  mutate(pct_missing = round(100 * n_missing / nrow(acc_raw), 1)) %>%\n  arrange(desc(n_missing))\nkable(missing_tbl)\n```\n\n::: {.cell-output-display}\n\n\n|variable             | n_missing| pct_missing|\n|:--------------------|---------:|-----------:|\n|acc_lat              |      9516|        74.6|\n|acc_long             |      9516|        74.6|\n|nationality          |      8410|        65.9|\n|person_district      |      7478|        58.6|\n|person_province      |      7469|        58.5|\n|acc_sub_district     |      6757|        52.9|\n|cause_code           |      1509|        11.8|\n|age                  |        93|         0.7|\n|sex                  |         0|         0.0|\n|confirmed_death_date |         0|         0.0|\n|acc_district         |         0|         0.0|\n|province_of_death    |         0|         0.0|\n|vehicle_type         |         0|         0.0|\n\n\n:::\n:::\n\n\nAbout three quarters of the records have no crash coordinates. This is the largest data-quality problem in the study, and the missingness turns out to be selective, which I show further below.\n\n### Coordinate validity\n\nThailand lies roughly between 5°N and 21°N and between 97°E and 106°E, so I compare the range of each coordinate column with these bounds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_raw %>%\n  filter(!is.na(acc_lat)) %>%\n  summarise(across(c(acc_lat, acc_long), list(min = min, max = max)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  acc_lat_min acc_lat_max acc_long_min acc_long_max\n        <dbl>       <dbl>        <dbl>        <dbl>\n1        97.9        106.         5.94         20.4\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Pitfall: latitude and longitude are swapped\n\nEvery value in `acc_lat` falls between 97 and 106, which in Thailand can only be a longitude, and every value in `acc_long` falls between 5 and 21. Used as labelled, every point would land far outside the country. I swap the two columns only where `acc_lat > 90`, a value no latitude can take, so the code would still work on a corrected version of the file.\n:::\n\n### Dates in the Buddhist Era\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  pattern_ok      = sum(str_detect(acc_raw$confirmed_death_date, \"^\\\\d{2}/\\\\d{2}/\\\\d{4}$\")),\n  year_values     = paste(unique(str_sub(acc_raw$confirmed_death_date, 7, 10)), collapse = \", \"),\n  naive_parse_NAs = sum(is.na(dmy(acc_raw$confirmed_death_date, quiet = TRUE)))\n) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n| pattern_ok|year_values | naive_parse_NAs|\n|----------:|:-----------|---------------:|\n|      12762|2567        |              35|\n\n\n:::\n:::\n\n\n::: {.callout-warning}\n## Pitfall: Buddhist Era years and 29 February\n\nAll dates carry the Thai Buddhist Era year 2567, which is 2024 CE. Parsing the strings directly with `dmy()` fails for the 35 records dated 29/02/2567, because 2567 CE is not a leap year while 2024 CE is. Converting the year before parsing recovers all 35 records.\n:::\n\n### Duplicate records\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_exact_dup <- sum(duplicated(acc_raw))\nn_exact_dup\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24\n```\n\n\n:::\n:::\n\n\nThese rows match in every column, including age, sex, dates and location. Since each row is one death, an identical pair most likely records the same death twice, so I remove them. Records that share a location but differ elsewhere are handled later under the point-event definition.\n\n## Cleaning and deriving variables\n\nThis pipeline removes the exact duplicates, converts the dates, translates the Thai categories I need and corrects the coordinates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvehicle_lookup <- c(\n  \"รถจักรยานยนต์\"          = \"Motorcycle\",\n  \"ไม่ระบุพาหนะ\"           = \"Unspecified\",\n  \"รถยนต์\"                = \"Car\",\n  \"คนเดินเท้า\"             = \"Pedestrian\",\n  \"รถบรรทุกขนาดเล็ก/รถตู้\" = \"Pickup / van\",\n  \"รถจักรยาน\"             = \"Bicycle\",\n  \"รถบรรทุกหนัก\"           = \"Heavy truck\",\n  \"รถเพื่อการเกษตร\"         = \"Agricultural vehicle\",\n  \"สามล้อ\"                = \"Three-wheeler\",\n  \"รถโดยสาร\"              = \"Bus\"\n)\n\nbmr_lookup <- c(\n  \"กรุงเทพมหานคร\" = \"Bangkok\",\n  \"นนทบุรี\"       = \"Nonthaburi\",\n  \"ปทุมธานี\"      = \"Pathum Thani\",\n  \"สมุทรปราการ\"   = \"Samut Prakan\",\n  \"สมุทรสาคร\"     = \"Samut Sakhon\",\n  \"นครปฐม\"       = \"Nakhon Pathom\"\n)\n\nacc <- acc_raw %>%\n  distinct() %>%\n  mutate(\n    ce_year       = as.integer(str_sub(confirmed_death_date, 7, 10)) - 543,\n    death_date    = dmy(paste0(str_sub(confirmed_death_date, 1, 6), ce_year)),\n    month         = month(death_date, label = TRUE, abbr = TRUE, locale = \"C\"),\n    sex           = recode(sex, \"ชาย\" = \"Male\", \"หญิง\" = \"Female\"),\n    vehicle       = unname(vehicle_lookup[vehicle_type]),\n    death_prov_en = unname(bmr_lookup[province_of_death]),\n    swapped       = !is.na(acc_lat) & acc_lat > 90,\n    lon           = if_else(swapped, acc_lat, acc_long),\n    lat           = if_else(swapped, acc_long, acc_lat),\n    has_xy        = !is.na(lon) & !is.na(lat)\n  )\n\ntibble(\n  records_after_dedup = nrow(acc),\n  unparsed_dates      = sum(is.na(acc$death_date)),\n  first_date          = min(acc$death_date),\n  last_date           = max(acc$death_date),\n  coords_swapped      = sum(acc$swapped),\n  untranslated_vehicle = sum(is.na(acc$vehicle)),\n  coords_outside_thailand = sum(acc$has_xy & !(between(acc$lon, 97, 106) & between(acc$lat, 5, 21)))\n) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n| records_after_dedup| unparsed_dates|first_date |last_date  | coords_swapped| untranslated_vehicle| coords_outside_thailand|\n|-------------------:|--------------:|:----------|:----------|--------------:|--------------------:|-----------------------:|\n|               12738|              0|2024-01-01 |2024-09-30 |           3240|                    0|                       0|\n\n\n:::\n:::\n\n\nAll dates now parse, every vehicle category is translated and every corrected coordinate falls inside Thailand. The observation period runs from 1 January to 30 September 2024, so the data cover nine months of the year.\n\n### Checking whether missing locations are random\n\nA pattern built from geocoded records represents all fatalities only if geocoding is unrelated to the crash itself. I check this for deaths recorded in the six BMR provinces, starting with vehicle type.\n\n\n::: {#tbl-geocode-vehicle .cell tbl-cap='Vehicle composition of all BMR fatalities versus geocoded BMR fatalities'}\n\n```{.r .cell-code}\nbmr_deaths <- acc %>%\n  filter(!is.na(death_prov_en)) %>%\n  mutate(vehicle_known = vehicle != \"Unspecified\")\n\nbmr_deaths %>%\n  count(vehicle, has_xy) %>%\n  pivot_wider(names_from = has_xy, values_from = n, values_fill = 0,\n              names_prefix = \"xy_\") %>%\n  mutate(total           = xy_TRUE + xy_FALSE,\n         pct_of_all      = round(100 * total / sum(total), 1),\n         pct_of_geocoded = round(100 * xy_TRUE / sum(xy_TRUE), 1)) %>%\n  select(vehicle, total, geocoded = xy_TRUE, pct_of_all, pct_of_geocoded) %>%\n  arrange(desc(total)) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|vehicle       | total| geocoded| pct_of_all| pct_of_geocoded|\n|:-------------|-----:|--------:|----------:|---------------:|\n|Motorcycle    |   836|      499|       56.3|            94.2|\n|Unspecified   |   586|       16|       39.4|             3.0|\n|Car           |    37|       13|        2.5|             2.5|\n|Pickup / van  |    11|        0|        0.7|             0.0|\n|Pedestrian    |     8|        1|        0.5|             0.2|\n|Bicycle       |     3|        1|        0.2|             0.2|\n|Bus           |     3|        0|        0.2|             0.0|\n|Heavy truck   |     1|        0|        0.1|             0.0|\n|Three-wheeler |     1|        0|        0.1|             0.0|\n\n\n:::\n:::\n\n\nDeaths with no recorded vehicle stand out, since only 16 of 586 have coordinates. To see whether this comes from the crashes or from the records, I compare how complete the other fields are for these deaths and for deaths with a recorded vehicle.\n\n\n::: {#tbl-record-source .cell tbl-cap='Completeness of other fields for BMR deaths with and without a recorded vehicle (%)'}\n\n```{.r .cell-code}\nsrc_tbl <- bmr_deaths %>%\n  group_by(record = if_else(vehicle_known, \"Vehicle recorded\", \"No vehicle recorded\")) %>%\n  summarise(deaths               = n(),\n            geocoded             = round(100 * mean(has_xy), 1),\n            no_sub_district      = round(100 * mean(is.na(acc_sub_district)), 1),\n            no_home_province     = round(100 * mean(is.na(person_province)), 1),\n            no_nationality       = round(100 * mean(is.na(nationality)), 1),\n            cause_code_V892      = round(100 * mean(cause_code %in% \"V892\"), 1))\nkable(src_tbl)\n```\n\n::: {.cell-output-display}\n\n\n|record              | deaths| geocoded| no_sub_district| no_home_province| no_nationality| cause_code_V892|\n|:-------------------|------:|--------:|---------------:|----------------:|--------------:|---------------:|\n|No vehicle recorded |    586|      2.7|            92.7|             95.1|           93.7|            91.1|\n|Vehicle recorded    |    900|     57.1|            10.9|             21.6|           20.9|            36.0|\n\n\n:::\n\n```{.r .cell-code}\nunspec_v892 <- src_tbl$cause_code_V892[src_tbl$record == \"No vehicle recorded\"]\n```\n:::\n\n\nDeaths with no recorded vehicle are almost never geocoded, and most of them also lack the sub-district, the person's home province and the nationality. 91.1% of them carry the ICD-10 cause code V89.2 (World Health Organization, 2019), a person injured in an unspecified motor-vehicle traffic accident, which is the code a death certificate uses when the crash details are unknown. The Kaggle page (pornsakkamchan, 2025) states that the dataset combines three sources compiled by the Department of Disease Control, so these records most likely come from a source that does not collect crash details.\n\n\n::: {#tbl-geocode-province .cell tbl-cap='Geocoding by province of death, for all deaths and for deaths with a recorded vehicle (%)'}\n\n```{.r .cell-code}\nprov_src <- bmr_deaths %>%\n  group_by(province = death_prov_en) %>%\n  summarise(deaths                 = n(),\n            geocoded_all           = round(100 * mean(has_xy), 1),\n            no_vehicle_recorded    = round(100 * mean(!vehicle_known), 1),\n            geocoded_vehicle_known = round(100 * mean(has_xy[vehicle_known]), 1)) %>%\n  arrange(desc(deaths))\nkable(prov_src)\n```\n\n::: {.cell-output-display}\n\n\n|province      | deaths| geocoded_all| no_vehicle_recorded| geocoded_vehicle_known|\n|:-------------|------:|------------:|-------------------:|----------------------:|\n|Bangkok       |    512|         45.5|                28.7|                   63.0|\n|Pathum Thani  |    278|         29.1|                44.6|                   51.9|\n|Samut Prakan  |    203|         35.0|                24.6|                   45.1|\n|Nakhon Pathom |    202|         25.7|                52.5|                   51.0|\n|Nonthaburi    |    148|         35.8|                58.1|                   82.3|\n|Samut Sakhon  |    143|         28.0|                51.0|                   50.0|\n\n\n:::\n\n```{.r .cell-code}\nknown_geo_pct <- round(100 * mean(bmr_deaths$has_xy[bmr_deaths$vehicle_known]), 1)\nmoto_known    <- round(100 * mean(bmr_deaths$vehicle[bmr_deaths$vehicle_known] == \"Motorcycle\"), 1)\nmoto_geo      <- round(100 * mean(bmr_deaths$vehicle[bmr_deaths$vehicle_known & bmr_deaths$has_xy] == \"Motorcycle\"), 1)\nunspec_share  <- round(100 * mean(!bmr_deaths$vehicle_known), 1)\n```\n:::\n\n\n::: {.callout-important}\n## Geocoding follows the record source\n\nAmong deaths with a recorded vehicle, 57.1% are geocoded. Motorcyclists make up 92.9% of these deaths and 97.1% of the geocoded ones, so the geocoded pattern has a vehicle mix close to that of all deaths with a known vehicle, and in practice it describes fatal motorcycle crashes.\n\nThe share of deaths from the source without crash details ranges from 24.6% to 58.1% across provinces, and this explains much of the gap in raw geocoding rates, though not all of it, since Samut Prakan has the lowest share of these records and still a lower raw rate than Bangkok. Among deaths with a recorded vehicle, Nonthaburi is geocoded most often and Bangkok second. Bangkok has a lower share of these records than four of the five surrounding provinces, so more of its deaths carry coordinates, which inflates its intensity relative to the fringe. I carry this into the interpretations below.\n:::\n\n## Spatial study window\n\n### Defining the Bangkok Metropolitan Region\n\nThe assignment names the \"Bangkok Greater Metropolitan Area\" without fixing a boundary. I use the Bangkok Metropolitan Region, the six-province area of Bangkok, Nonthaburi, Pathum Thani, Samut Prakan, Samut Sakhon and Nakhon Pathom that Thai government agencies use for metropolitan planning and statistics (Wikipedia contributors, 2026). It follows official boundaries, can be rebuilt from a public dataset and covers the continuous built-up and commuter area around the capital.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadm1 <- st_read(\"data/raw/geoBoundaries-THA-ADM1.geojson\", quiet = TRUE)\ntable(valid = st_is_valid(adm1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvalid\nTRUE \n  77 \n```\n\n\n:::\n\n```{.r .cell-code}\nbmr <- adm1 %>%\n  filter(str_detect(shapeName, regex(\n    \"Bangkok|Krung Thep|Nonthaburi|Pathum ?Thani|Samut Prak|Samut Sakhon|Nakhon Pathom\",\n    ignore_case = TRUE))) %>%\n  st_make_valid() %>%\n  st_transform(32647) %>%\n  mutate(province = case_when(\n    str_detect(shapeName, regex(\"Bangkok|Krung Thep\", ignore_case = TRUE)) ~ \"Bangkok\",\n    str_detect(shapeName, regex(\"Nonthaburi\",        ignore_case = TRUE)) ~ \"Nonthaburi\",\n    str_detect(shapeName, regex(\"Pathum ?Thani\",     ignore_case = TRUE)) ~ \"Pathum Thani\",\n    str_detect(shapeName, regex(\"Samut Prak\",        ignore_case = TRUE)) ~ \"Samut Prakan\",\n    str_detect(shapeName, regex(\"Samut Sakhon\",      ignore_case = TRUE)) ~ \"Samut Sakhon\",\n    str_detect(shapeName, regex(\"Nakhon Pathom\",     ignore_case = TRUE)) ~ \"Nakhon Pathom\"\n  )) %>%\n  select(province)\n\nstopifnot(nrow(bmr) == 6, !anyNA(bmr$province))\n\nbmr_union <- bmr %>% st_union() %>% st_make_valid()\nbmr_area_km2 <- round(as.numeric(st_area(bmr_union)) / 1e6)\nbmr_area_km2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7604\n```\n\n\n:::\n:::\n\n\nThe dissolved boundary covers 7,604 km², close to the 7,681 km² usually reported for the region, which confirms that the filter picked up the right six provinces.\n\n::: {.callout-warning}\n## Pitfall: province names in geoBoundaries\n\nIn this geoBoundaries release Bangkok is stored as \"Bangkok\" while the other provinces carry a suffix, as in \"Nonthaburi Province\", and other sources use spellings such as \"Bangkok Metropolis\" or \"Samut Prakarn\". I match the names with flexible regular expressions and then standardise them. The `stopifnot()` line stops the render if the filter returns anything other than six provinces.\n:::\n\n### Coordinate reference system\n\nI project every layer to WGS 84 / UTM zone 47N (EPSG:32647). The BMR sits between about 99.9°E and 101.0°E, inside zone 47 (96°E to 102°E), so distortion is small. Kernel density, nearest-neighbour distances and K-functions all depend on distance, and they need coordinates in metres.\n\n## Converting to spatial objects and filtering to the study window\n\nI turn the geocoded records into an `sf` point layer, project it and keep the points that fall inside the BMR polygon. The filter uses the point geometry, since `province_of_death` records where the person died, and that can be a different province from the crash.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_sf <- acc %>%\n  filter(has_xy) %>%\n  st_as_sf(coords = c(\"lon\", \"lat\"), crs = 4326, remove = FALSE) %>%\n  st_transform(32647)\n\nacc_bmr <- acc_sf %>%\n  st_filter(bmr_union) %>%\n  st_join(bmr, join = st_nearest_feature)\n\nnrow(acc_bmr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 530\n```\n\n\n:::\n:::\n\n\n`st_filter()` keeps the points that intersect the BMR. `st_join()` with `st_nearest_feature` attaches exactly one province to each point, so a point lying on a shared provincial border does not get duplicated.\n\n\n::: {#tbl-province-consistency .cell tbl-cap='Consistency between the recorded province of death and the province in which the crash point falls'}\n\n```{.r .cell-code}\nacc_sf %>%\n  st_join(bmr, join = st_intersects) %>%\n  st_drop_geometry() %>%\n  filter(!is.na(death_prov_en) | !is.na(province)) %>%\n  mutate(status = case_when(\n    !is.na(death_prov_en) & is.na(province)  ~ \"Died in BMR, crash point outside BMR\",\n    is.na(death_prov_en)  & !is.na(province) ~ \"Crash point in BMR, died outside BMR\",\n    death_prov_en == province                ~ \"Same province\",\n    TRUE                                     ~ \"Different BMR province\"\n  )) %>%\n  count(status) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|status                               |   n|\n|:------------------------------------|---:|\n|Crash point in BMR, died outside BMR |   2|\n|Died in BMR, crash point outside BMR |   2|\n|Different BMR province               |   4|\n|Same province                        | 524|\n\n\n:::\n:::\n\n\nMost crash points fall in the same province as the recorded death. The handful of cross-boundary cases fits the idea of injured people being taken to hospitals in a neighbouring province, and it supports filtering by geometry.\n\n## Point event definition\n\nEach row in the data is a death. A crash that kills two people produces two rows at identical coordinates, and treating them as two events would place a pair of points at zero distance. Second-order summaries such as the K-function would read that as clustering at the smallest scales.\n\nI define the point event as a fatal crash location. I approximate it by merging deaths that share both the exact coordinates and the date of death, and I keep the number of deaths as a mark (`n_deaths`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxy <- st_coordinates(acc_bmr)\n\nevents <- acc_bmr %>%\n  st_drop_geometry() %>%\n  mutate(x = xy[, 1], y = xy[, 2]) %>%\n  group_by(x, y, death_date) %>%\n  summarise(n_deaths = n(),\n            vehicle  = paste(sort(unique(vehicle)), collapse = \" + \"),\n            province = first(province),\n            month    = first(month),\n            .groups  = \"drop\") %>%\n  st_as_sf(coords = c(\"x\", \"y\"), crs = 32647, remove = FALSE)\n\ntibble(n_events                     = nrow(events),\n       n_multi_fatality_events      = sum(events$n_deaths > 1),\n       n_colocated_events_remaining = sum(duplicated(st_coordinates(events)))) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| n_events| n_multi_fatality_events| n_colocated_events_remaining|\n|--------:|-----------------------:|----------------------------:|\n|      515|                      15|                           12|\n\n\n:::\n\n```{.r .cell-code}\nev_dist <- as.matrix(dist(st_coordinates(events)))\nev_days <- abs(outer(as.numeric(events$death_date), as.numeric(events$death_date), \"-\"))\nsame_spot_gaps <- sort(ev_days[upper.tri(ev_days)][ev_dist[upper.tri(ev_dist)] == 0])\nsame_spot_gaps\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  18  39  40  41  48  70  83  86  89  98 123 123 169 170\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Assumptions behind this event definition\n\nTwo deaths at the same point on the same date are treated as one crash. This could merge two separate crashes at one blackspot on the same day, which I expect to be rare. If one victim died several days after the others, the same crash stays as two events at one location. The remaining co-located events (same coordinates, different dates) could be repeat crashes at a blackspot or coordinates snapped to a default point during geocoding. The data give no way to tell these apart, so I keep them as separate events.\n\nThe co-located events also give a check on the second risk. If split crashes were common, co-located events would sit only a few days apart. Of the 14 pairs of events at identical coordinates, 0 are within 7 days of each other and 1 within 30 days, with gaps from 18 to 170 days. At most 1 crash can have been split this way.\n:::\n\n## Temporal study window\n\nThe temporal window is 1 January to 30 September 2024, the full period in the data. The only date available is the date of confirmed death, which I use as a proxy for the crash date. For deaths at the scene the two are the same. For deaths after a hospital stay the crash happened earlier, which matters for daily analysis and much less for monthly totals, so the month is the finest unit I interpret with confidence.\n\n## Road network\n\n### Choosing the road classes\n\nThe OSM layer holds about 590,000 lines inside the BMR, and most of them are residential lanes and service roads. I first measured how far each crash event lies from two candidate networks. Within 50 m of the major roads (motorway, trunk, primary, secondary and tertiary, with their link roads) lie 72.6% of events, with a median distance of 4.9 m. Within 50 m of all roads open to motor vehicles lie 96.9%, with a median of 2.8 m. I ran this comparison once on the full OSM file before clipping, so these two figures can differ slightly from the share computed below on the clipped network. The code below keeps only the step that builds the major road layer.\n\nI use the major road network. Adding residential and service roads would multiply the network about fifteen times, and the network K-function simulations would no longer finish in reasonable time. The cost is that about a quarter of the events sit on smaller roads and fall outside the analysis, which I report below and carry into the limitations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmajor_classes <- c(\"motorway\", \"motorway_link\", \"trunk\", \"trunk_link\",\n                   \"primary\", \"primary_link\", \"secondary\", \"secondary_link\",\n                   \"tertiary\", \"tertiary_link\")\nroads_gpkg <- \"data/raw/bmr_roads_major.gpkg\"\n\nif (!file.exists(roads_gpkg)) {\n  bmr_wkt <- bmr_union %>% st_transform(4326) %>% st_bbox() %>%\n    st_as_sfc() %>% st_as_text()\n  st_read(\"data/raw/osm/gis_osm_roads_free_1.shp\",\n          wkt_filter = bmr_wkt, quiet = TRUE) %>%\n    st_transform(32647) %>%\n    st_filter(bmr_union) %>%\n    filter(fclass %in% major_classes) %>%\n    select(osm_id, fclass, name, oneway) %>%\n    st_write(roads_gpkg, quiet = TRUE)\n}\n\nroads <- st_read(roads_gpkg, quiet = TRUE)\nroads %>% st_drop_geometry() %>% count(fclass, sort = TRUE) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|fclass         |    n|\n|:--------------|----:|\n|secondary      | 7339|\n|primary        | 6272|\n|tertiary       | 5723|\n|primary_link   | 2455|\n|secondary_link | 2074|\n|motorway_link  | 1720|\n|trunk          | 1464|\n|motorway       | 1267|\n|trunk_link     |  668|\n|tertiary_link  |  425|\n\n\n:::\n:::\n\n\n### Clipping the network and repairing its topology\n\nI clip the major roads to the BMR boundary. `spNetwork` builds its graph from the two end points of each line, while OSM roads usually cross at a junction vertex in the middle of both lines. Left as they are, most crossing roads would count as unconnected, and network distances would be far too long. I split every line at each vertex it shares with another line, so that every junction becomes a line end.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroads_bmr <- roads %>%\n  st_intersection(bmr_union) %>%\n  st_cast(\"MULTILINESTRING\") %>%\n  st_cast(\"LINESTRING\")\nroads_bmr <- roads_bmr[as.numeric(st_length(roads_bmr)) > 0, ]\n\nsplit_at_junctions <- function(lines) {\n  vx <- as_tibble(st_coordinates(lines)) %>%\n    rename(line = L1) %>%\n    mutate(key = paste(round(X, 2), round(Y, 2))) %>%\n    group_by(line) %>%\n    mutate(pos = row_number(), last = pos == n()) %>%\n    ungroup() %>%\n    add_count(key, name = \"uses\") %>%\n    mutate(junction = pos == 1 | last | uses > 1) %>%\n    group_by(line) %>%\n    mutate(seg = cumsum(junction)) %>%\n    ungroup()\n  pieces <- bind_rows(vx %>% filter(!last),\n                      vx %>% filter(junction, pos > 1) %>% mutate(seg = seg - 1)) %>%\n    arrange(line, seg, pos) %>%\n    mutate(piece = paste(line, seg, sep = \"_\"))\n  out <- sfheaders::sf_linestring(pieces, x = \"X\", y = \"Y\", linestring_id = \"piece\")\n  st_crs(out) <- st_crs(lines)\n  idx <- as.integer(sub(\"_.*\", \"\", out$piece))\n  out$fclass <- lines$fclass[idx]\n  out$oneway <- lines$oneway[idx]\n  out\n}\n\nnetwork_all <- split_at_junctions(roads_bmr)\n```\n:::\n\n\n::: {.callout-warning}\n## Pitfall: slow topology repair\n\n`spNetwork` has `simple_lines()` and `simplify_network()` for this job, but on this network the second step was still running after ten minutes. My `split_at_junctions()` function does the same repair in a few seconds. It lists every vertex, marks vertices that are line ends or that appear in more than one line, and cuts each line at the marked vertices. `graph_checking()` from `spNetwork` found the same number of disconnected parts as my own check below, which confirms that the repair works. The chunk below shows that check. I set it not to run during rendering because it takes about two minutes.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimple <- simple_lines(roads_bmr)\ngc_res <- graph_checking(simple, digits = 2)\nlength(unique(gc_res$vertex_components$component))   # 24 in my run\n```\n:::\n\n\n### Connectivity\n\nA network distance between two events exists only if they sit on connected parts of the network. I build a graph from the segment end points with `igraph` and keep the largest connected part.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnode_key <- function(m) paste(round(m[, \"X\"], 2), round(m[, \"Y\"], 2))\n\ncc        <- st_coordinates(network_all)\nfirst_pt  <- cc[!duplicated(cc[, \"L1\"]), ]\nlast_pt   <- cc[!duplicated(cc[, \"L1\"], fromLast = TRUE), ]\ng_all     <- igraph::graph_from_data_frame(\n  data.frame(from = node_key(first_pt), to = node_key(last_pt)), directed = FALSE)\ncomp      <- igraph::components(g_all)\nmain_comp <- which.max(comp$csize)\n\nnetwork_all$component <- comp$membership[node_key(first_pt)]\nnetwork <- network_all %>% filter(component == main_comp)\nnetwork$length <- as.numeric(st_length(network))\n\nnet_summary <- tibble(\n  osm_lines_clipped = nrow(roads_bmr),\n  segments          = nrow(network_all),\n  components        = comp$no,\n  km_all            = round(sum(as.numeric(st_length(network_all))) / 1000),\n  km_main           = round(sum(network$length) / 1000),\n  pct_nodes_main    = round(100 * max(comp$csize) / sum(comp$csize), 1)\n)\nkable(net_summary)\n```\n\n::: {.cell-output-display}\n\n\n| osm_lines_clipped| segments| components| km_all| km_main| pct_nodes_main|\n|-----------------:|--------:|----------:|------:|-------:|--------------:|\n|             29409|    36760|         24|  10534|   10489|           99.7|\n\n\n:::\n:::\n\n\nThe repaired network has 36,760 segments in 24 disconnected parts. The largest part holds 99.7% of the nodes and 10,489 km of road, and the other parts are short pieces such as isolated ramps and roads cut off by the boundary.\n\n### Snapping events to the network\n\nI attach each event to its nearest network segment and keep events within 50 m. The tolerance covers geocoding error and the width of large roads with frontage lanes, which can put a crash 20 to 40 m from the OSM centre line. An event further away most likely happened on a smaller road, and forcing it onto a major road would place it on the wrong segment.\n\n\n::: {#tbl-snap .cell tbl-cap='Fatal crash events within 50 m of the major road network, by province'}\n\n```{.r .cell-code}\nnearest_edge <- st_nearest_feature(events, network)\nevents$snap_dist  <- as.numeric(st_distance(events, network[nearest_edge, ], by_element = TRUE))\nevents$road_class <- network$fclass[nearest_edge]\n\nev <- events %>% filter(snap_dist <= 50)\n\nsnap_tbl <- events %>%\n  st_drop_geometry() %>%\n  group_by(province) %>%\n  summarise(events          = n(),\n            on_network      = sum(snap_dist <= 50),\n            pct_on_network  = round(100 * mean(snap_dist <= 50), 1),\n            median_snap_m   = round(median(snap_dist), 1)) %>%\n  arrange(desc(events))\nkable(snap_tbl)\n```\n\n::: {.cell-output-display}\n\n\n|province      | events| on_network| pct_on_network| median_snap_m|\n|:-------------|------:|----------:|--------------:|-------------:|\n|Bangkok       |    227|        156|           68.7|           5.6|\n|Pathum Thani  |     77|         64|           83.1|           4.1|\n|Samut Prakan  |     69|         56|           81.2|           3.7|\n|Nonthaburi    |     53|         38|           71.7|           5.5|\n|Nakhon Pathom |     51|         34|           66.7|           4.7|\n|Samut Sakhon  |     38|         26|           68.4|           6.9|\n\n\n:::\n\n```{.r .cell-code}\npct_on <- function(prov) snap_tbl$pct_on_network[snap_tbl$province == prov]\n```\n:::\n\n\n374 of 515 events (72.6%) lie within 50 m of the network. The share is highest in Pathum Thani (83.1%) and Samut Prakan (81.2%) and lowest in Nakhon Pathom (66.7%), Samut Sakhon (68.4%) and Bangkok (68.7%). The median snapping distance of the kept events is only a few metres, so the kept events sit on the road they are attached to.\n\n## Data preparation summary\n\n\n::: {#tbl-flow .cell tbl-cap='Records retained at each preparation step'}\n\n```{.r .cell-code}\ntibble(\n  step = c(\"Raw records\",\n           \"After removing exact duplicates\",\n           \"With valid crash coordinates\",\n           \"Crash point inside the BMR\",\n           \"Fatal crash events (deaths collapsed)\",\n           \"Events within 50 m of the major road network\"),\n  n = c(nrow(acc_raw), nrow(acc), sum(acc$has_xy), nrow(acc_bmr),\n        nrow(events), nrow(ev))\n) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|step                                         |     n|\n|:--------------------------------------------|-----:|\n|Raw records                                  | 12762|\n|After removing exact duplicates              | 12738|\n|With valid crash coordinates                 |  3240|\n|Crash point inside the BMR                   |   530|\n|Fatal crash events (deaths collapsed)        |   515|\n|Events within 50 m of the major road network |   374|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevents_map <- events %>%\n  mutate(status = if_else(snap_dist <= 50, \"Within 50 m of network\",\n                          \"More than 50 m from network\"))\n\ntmap_mode(\"plot\")\ntm_shape(bmr) +\n  tm_polygons(fill = \"grey97\", col = \"grey60\") +\n  tm_shape(network) +\n  tm_lines(col = \"grey55\", lwd = 0.6) +\n  tm_shape(events_map) +\n  tm_dots(fill = \"status\",\n          fill.scale = tm_scale_categorical(values = c(\"#9AA58F\", \"#B5533C\")),\n          fill.legend = tm_legend(title = \"\"),\n          size = 0.15) +\n  tm_layout(frame = FALSE)\n```\n\n::: {.cell-output-display}\n![Major road network and geocoded fatal crash events in the Bangkok Metropolitan Region, January to September 2024](Take-home_Ex01_files/figure-html/fig-events-1.png){#fig-events width=672}\n:::\n:::\n\n\n::: {.callout-note}\n## Interpretation\n\nThe major road network forms a dense grid across Bangkok and a sparser set of corridors in Nakhon Pathom, Samut Sakhon and eastern Pathum Thani. Terracotta dots are the 374 events within 50 m of a major road, and sage dots are the 141 events further away. Between 31% and 33% of events in Bangkok, Nakhon Pathom and Samut Sakhon fall off the network, against 17% in Pathum Thani and 19% in Samut Prakan, so the analysed pattern under-represents events far from major roads in the first three provinces. The map shows geocoded events only, and the record-source gap from Section 2.5 applies on top of this.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"data/rds\", showWarnings = FALSE, recursive = TRUE)\nwrite_rds(acc,     \"data/rds/acc_clean.rds\")\nwrite_rds(bmr,     \"data/rds/bmr.rds\")\nwrite_rds(events,  \"data/rds/events.rds\")\nwrite_rds(network, \"data/rds/network.rds\")\nwrite_rds(ev,      \"data/rds/ev.rds\")\n```\n:::\n\n\n::: {.callout-tip}\n## My takeaway\n\nThe swapped coordinates, the 29 February dates and a row unit that counts deaths would each have broken the analysis without an error message. The road network added a fourth problem of the same kind, since OSM roads cross without ending at junctions and the network would have been mostly disconnected.\n:::\n\n# First-order Network Point Pattern Analysis\n\nFirst-order properties describe how the intensity of fatal crashes varies across the study area. On a network, intensity means the expected number of events per km of road. Planar kernel density spreads each crash over fields, canals and buildings, while network kernel density estimation (NKDE) spreads it only along the roads it could have happened on, so the result reads as crashes per km of road (Okabe & Sugihara, 2012).\n\n## Lixels and sample points\n\nNKDE estimates density at sample points along the network. I cut the network into lixels (linear pixels) of 200 m, merging any leftover piece shorter than 100 m into its neighbour, and use the centre of each lixel as its sample point.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlixels  <- lixelize_lines(network, 200, mindist = 100)\nsamples <- lines_center(lixels)\ntibble(n_lixels = nrow(lixels),\n       median_length_m = round(median(as.numeric(st_length(lixels))))) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n| n_lixels| median_length_m|\n|--------:|---------------:|\n|    67956|             200|\n\n\n:::\n:::\n\n\n## Kernel, method and bandwidth\n\nFour choices shape the estimate.\n\n-   **Events lie on the network.** Each kept event has been attached to its nearest major road segment. The estimate says nothing about crashes on smaller roads.\n-   **Quartic kernel.** The kernel weight falls smoothly to zero at the bandwidth, which matches the course material. The kernel shape matters much less than the bandwidth.\n-   **Simple method.** The simple method of Xie and Yan (2008) replaces straight-line distance with network distance and leaves the kernel unchanged. It does not divide the kernel mass at junctions, so density is inflated near busy junctions and lost at dead ends. The discontinuous and continuous methods of Okabe et al. (2009) correct this, and on a network with tens of thousands of junctions they were too slow to run here. I check the size of the mass problem below.\n-   **No edge correction.** The network is cut at the BMR boundary, so events near the edge lose the part of their kernel that would fall outside. Intensity near the boundary is therefore too low.\n\n### Bandwidth selection\n\nI tried likelihood cross-validation with `bw_cv_likelihood_calc()` over bandwidths from 250 m to 3 km.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_cands <- c(250, 500, 750, 1000, 1500, 2000, 3000)\nbw_cv <- bw_cv_likelihood_calc(bws = bw_cands, lines = network, events = ev,\n                               w = rep(1, nrow(ev)), kernel_name = \"quartic\",\n                               method = \"simple\", digits = 1, tol = 1,\n                               sparse = TRUE, grid_shape = c(1, 1),\n                               verbose = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nbw_cv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    bw cv_scores\n1  250 -641.3264\n2  500 -578.1718\n3  750 -539.1838\n4 1000 -494.6884\n5 1500 -427.9175\n6 2000 -362.9002\n7 3000 -230.9652\n```\n\n\n:::\n:::\n\n\nThe score rises at every step and peaks at the widest candidate, so the procedure gives no interior optimum. Many events have no other event within a few hundred metres of network distance, so their leave-one-out density is zero unless the bandwidth is very wide. By default `bw_cv_likelihood_calc()` replaces a zero density with the smallest positive number the computer can store (`zero_strat = \"min_double\"`), which gives a huge penalty to every narrow bandwidth and pushes the score towards the widest candidate. A 3 km kernel would smear each crash over whole districts, which hides the road-segment detail a planning agency needs. I set the bandwidth to 1 km, about the length of a typical block between major junctions, and test 500 m and 2 km for sensitivity.\n\n`nkde()` returns a density that integrates to one over the network. I multiply it by the number of events and by 1,000 to express intensity in events per km over the nine months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_nkde <- 1000\n\nrun_nkde <- function(bw) {\n  d <- nkde(network, events = ev, w = rep(1, nrow(ev)), samples = samples,\n            kernel_name = \"quartic\", bw = bw, div = \"bw\", method = \"simple\",\n            digits = 1, tol = 1, grid_shape = c(1, 1), max_depth = 8,\n            agg = 5, sparse = TRUE, verbose = FALSE)\n  d * nrow(ev) * 1000\n}\n\nlixels$len_km    <- as.numeric(st_length(lixels)) / 1000\nlixels$intensity <- run_nkde(bw_nkde)\n\ntibble(bandwidth_m      = bw_nkde,\n       max_per_km       = round(max(lixels$intensity), 3),\n       mass_on_network  = round(sum(lixels$intensity * lixels$len_km), 1),\n       events           = nrow(ev)) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n| bandwidth_m| max_per_km| mass_on_network| events|\n|-----------:|----------:|---------------:|------:|\n|        1000|      1.401|           272.5|    374|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsens_bws <- c(bw_nkde / 2, bw_nkde * 2)\nlixels$intensity_narrow <- run_nkde(sens_bws[1])\nlixels$intensity_wide   <- run_nkde(sens_bws[2])\n\ntop5 <- function(x) x >= quantile(x, 0.95)\nnkde_sens <- tibble(\n  bandwidth_m          = c(sens_bws[1], bw_nkde, sens_bws[2]),\n  max_per_km           = round(c(max(lixels$intensity_narrow), max(lixels$intensity),\n                                 max(lixels$intensity_wide)), 3),\n  cor_with_main        = round(c(cor(lixels$intensity_narrow, lixels$intensity), 1,\n                                 cor(lixels$intensity_wide, lixels$intensity)), 2),\n  top5_overlap_pct     = round(100 * c(mean(top5(lixels$intensity_narrow)[top5(lixels$intensity)]), 1,\n                                       mean(top5(lixels$intensity_wide)[top5(lixels$intensity)])), 1)\n)\nkable(nkde_sens)\n```\n\n::: {.cell-output-display}\n\n\n| bandwidth_m| max_per_km| cor_with_main| top5_overlap_pct|\n|-----------:|----------:|-------------:|----------------:|\n|         500|      5.581|          0.82|             89.8|\n|        1000|      1.401|          1.00|            100.0|\n|        2000|      0.358|          0.78|             50.5|\n\n\n:::\n:::\n\n\nHalving the bandwidth to 500 m keeps the hotspots in place. Its surface correlates at 0.82 with the 1 km surface, and 89.8% of the top 5% of lixels under 1 km are also in the top 5% under 500 m. Doubling it to 2 km spreads the hotspots out, and the overlap falls to 50.5%. The location of the main hotspots is stable at the fine end of the range and becomes more diffuse as the kernel widens.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmass_ratio <- function(v) round(sum(v * lixels$len_km) / nrow(ev), 2)\nmass_tbl <- tibble(\n  bandwidth_m = c(sens_bws[1], bw_nkde, sens_bws[2]),\n  mass_ratio  = c(mass_ratio(lixels$intensity_narrow),\n                  mass_ratio(lixels$intensity),\n                  mass_ratio(lixels$intensity_wide))\n)\nkable(mass_tbl)\n```\n\n::: {.cell-output-display}\n\n\n| bandwidth_m| mass_ratio|\n|-----------:|----------:|\n|         500|       1.12|\n|        1000|       0.73|\n|        2000|       0.55|\n\n\n:::\n\n```{.r .cell-code}\nloss_pct <- round(100 * (1 - mass_tbl$mass_ratio[2]))\n\nlx_sorted <- lixels %>%\n  st_drop_geometry() %>%\n  arrange(desc(intensity)) %>%\n  mutate(cum_len  = cumsum(len_km) / sum(len_km),\n         cum_mass = cumsum(intensity * len_km) / sum(intensity * len_km))\nlen_half <- lx_sorted$cum_len[which(lx_sorted$cum_mass >= 0.5)[1]]\nlen_zero <- mean(lixels$intensity == 0)\n\ntop_lx       <- lixels %>% filter(intensity >= quantile(intensity, 0.95))\ntop_prov     <- st_join(st_centroid(top_lx), bmr[\"province\"]) %>% st_drop_geometry()\ntop5_bkk     <- round(100 * mean(top_prov$province == \"Bangkok\"))\ntop5_primsec <- round(100 * mean(str_detect(top_lx$fclass, \"primary|secondary\")))\n```\n:::\n\n\nThe mass ratio compares the estimated intensity summed over the network with the number of events. Two effects pull in opposite directions under the simple method. The full kernel is copied onto every branch at a junction, which adds mass, and the kernel runs off the network at dead ends and at the BMR boundary, which removes it. The ratio falls from 1.12 at 500 m to 0.55 at 2000 m, since a wider kernel reaches the boundary and dead ends more often. At 1 km the loss outweighs the gain, so the intensities are about 27% too low overall, and segments near the boundary are pulled down more than central ones. I use the values to compare segments away from the boundary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnkde_breaks <- c(0, 0.05, 0.1, 0.25, 0.5, 1, ceiling(max(lixels$intensity) * 10) / 10)\n\ntm_shape(bmr) +\n  tm_polygons(fill = \"grey97\", col = \"grey60\") +\n  tm_text(\"province\", size = 0.6, col = \"grey40\") +\n  tm_shape(arrange(lixels, intensity)) +\n  tm_lines(col = \"intensity\",\n           col.scale = tm_scale_intervals(values = \"brewer.yl_or_rd\",\n                                          style = \"fixed\", breaks = nkde_breaks),\n           col.legend = tm_legend(title = \"Events per km\\n(Jan to Sep 2024)\"),\n           lwd = 1.3) +\n  tm_layout(frame = FALSE)\n```\n\n::: {.cell-output-display}\n![Network kernel density of fatal crash events on the major road network, events per km over nine months (quartic kernel, simple method)](Take-home_Ex01_files/figure-html/fig-nkde-map-1.png){#fig-nkde-map width=672}\n:::\n:::\n\n\n::: {.callout-note}\n## Interpretation\n\nFatal crash intensity is highest on a dense cluster of segments in central Bangkok and on shorter hotspots spread along major corridors, including a north-south corridor in Pathum Thani and several roads in Samut Prakan. At this bandwidth 83% of the network length has zero intensity. Among the top 5% of lixels, 49% lie in Bangkok and most of the rest in Samut Prakan, Pathum Thani and Nonthaburi, and 73% are on primary and secondary roads. The values are relative, since the simple method loses about 27% of the kernel mass and more near the boundary. The map also covers only crashes within 50 m of a major road, and Bangkok has the largest share of crashes on smaller roads.\n:::\n\n## How concentrated is the intensity\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(pct_length_holding_half_mass = round(100 * len_half, 1),\n       pct_length_zero_intensity    = round(100 * len_zero, 1)) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n| pct_length_holding_half_mass| pct_length_zero_intensity|\n|----------------------------:|-------------------------:|\n|                          3.1|                      83.1|\n\n\n:::\n:::\n\n\nHalf of the estimated intensity lies on 3.1% of the network length, and 83.1% of the network length has zero intensity at a 1 km bandwidth. Fatal crashes on major roads concentrate on a small share of the network.\n\n## Intensity by road class and province\n\nThe NKDE shows where crashes concentrate, while a simple rate per 100 km of road shows how intensity varies between road classes and provinces once network length is taken into account.\n\n\n::: {#tbl-road-class .cell tbl-cap='Fatal crash events per 100 km of major road, by road class and by province'}\n\n```{.r .cell-code}\nclass_group <- function(fc) case_when(\n  str_detect(fc, \"motorway|trunk\") ~ \"Motorway and trunk\",\n  str_detect(fc, \"primary\")        ~ \"Primary\",\n  str_detect(fc, \"secondary\")      ~ \"Secondary\",\n  TRUE                             ~ \"Tertiary\"\n)\n\nby_class <- network %>%\n  st_drop_geometry() %>%\n  group_by(group = class_group(fclass)) %>%\n  summarise(km        = sum(length) / 1000,\n            km_centre = sum(length * if_else(oneway %in% c(\"F\", \"T\"), 0.5, 1)) / 1000) %>%\n  left_join(ev %>% st_drop_geometry() %>% count(group = class_group(road_class), name = \"events\"),\n            by = \"group\") %>%\n  mutate(level = \"Road class\")\n\nnet_prov <- st_intersection(network, bmr) %>%\n  mutate(km = as.numeric(st_length(.)) / 1000) %>%\n  st_drop_geometry() %>%\n  group_by(group = province) %>%\n  summarise(km_centre = sum(km * if_else(oneway %in% c(\"F\", \"T\"), 0.5, 1)),\n            km        = sum(km))\n\nby_prov <- net_prov %>%\n  left_join(ev %>% st_drop_geometry() %>% count(group = province, name = \"events\"),\n            by = \"group\") %>%\n  mutate(level = \"Province\")\n\nrate_tbl <- bind_rows(by_class, by_prov) %>%\n  mutate(events            = replace_na(events, 0),\n         events_per_100km  = round(100 * events / km, 1),\n         per_100km_centre  = round(100 * events / km_centre, 1),\n         km                = round(km),\n         km_centre         = round(km_centre)) %>%\n  select(level, group, km, km_centre, events, events_per_100km, per_100km_centre)\nkable(rate_tbl)\n```\n\n::: {.cell-output-display}\n\n\n|level      |group              |   km| km_centre| events| events_per_100km| per_100km_centre|\n|:----------|:------------------|----:|---------:|------:|----------------:|----------------:|\n|Road class |Motorway and trunk | 2125|      1065|     54|              2.5|              5.1|\n|Road class |Primary            | 2357|      1220|    128|              5.4|             10.5|\n|Road class |Secondary          | 2856|      1894|    137|              4.8|              7.2|\n|Road class |Tertiary           | 3152|      2975|     55|              1.7|              1.8|\n|Province   |Bangkok            | 4099|      2581|    156|              3.8|              6.0|\n|Province   |Nakhon Pathom      | 1623|      1251|     34|              2.1|              2.7|\n|Province   |Nonthaburi         | 1164|       792|     38|              3.3|              4.8|\n|Province   |Pathum Thani       | 1666|      1210|     64|              3.8|              5.3|\n|Province   |Samut Prakan       | 1217|       794|     56|              4.6|              7.1|\n|Province   |Samut Sakhon       |  720|       528|     26|              3.6|              4.9|\n\n\n:::\n\n```{.r .cell-code}\nrate <- function(g, col = \"events_per_100km\") rate_tbl[[col]][rate_tbl$group == g]\nraw_geo <- function(p) prov_src$geocoded_all[prov_src$province == p]\n```\n:::\n\n\n::: {.callout-note}\n## Interpretation\n\nPrimary roads have the highest rate at 5.4 fatal crash events per 100 km of mapped line, followed by secondary roads at 4.8, and motorways, trunk and tertiary roads have lower rates. OSM draws most motorways, trunk roads and primary roads as two one-way lines, so the mapped length double counts divided roads. Counting one-way lines at half length raises every rate, most of all on divided roads, and the order of road classes stays the same. By province, Samut Prakan has the highest rate under both measures, at 4.6 and 7.1, against 3.8 and 6 for Bangkok. Samut Prakan's raw geocoding rate is lower than Bangkok's (35% against 45.5%), so geocoding bias works against it. These rates count crashes per km and do not measure risk per vehicle.\n:::\n\n## Temporal variation\n\nThe temporal charts use all 515 geocoded events in the BMR, since timing does not depend on the road network.\n\n### Monthly pattern\n\nI compare the monthly distribution of the geocoded events with that of all BMR deaths. Plotting each series as a share of its own nine-month total shows whether the analysed subset has the same seasonal shape as the full record, even though it holds only about a third of the deaths.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly <- bind_rows(\n  events %>% st_drop_geometry() %>% count(month) %>%\n    mutate(series = \"Geocoded crash events (analysed)\"),\n  acc %>% filter(!is.na(death_prov_en)) %>% count(month) %>%\n    mutate(series = \"All BMR deaths (by province of death)\")\n) %>%\n  group_by(series) %>%\n  mutate(share = 100 * n / sum(n)) %>%\n  ungroup()\n\nggplot(monthly, aes(month, share, colour = series, group = series)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  geom_hline(yintercept = 100 / 9, linetype = \"dashed\", colour = \"grey50\") +\n  scale_colour_manual(values = c(\"#7A8B6F\", \"#B5533C\")) +\n  labs(x = NULL, y = \"Share of Jan to Sep total (%)\", colour = NULL) +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"top\")\n\ngeo_m <- monthly %>% filter(str_detect(series, \"Geocoded\"))\npeak_month <- as.character(geo_m$month[which.max(geo_m$n)])\nlow_month  <- as.character(geo_m$month[which.min(geo_m$n)])\n```\n\n::: {.cell-output-display}\n![Monthly share of fatalities, geocoded crash events versus all BMR deaths, January to September 2024](Take-home_Ex01_files/figure-html/fig-monthly-1.png){#fig-monthly width=672}\n:::\n:::\n\n\n::: {.callout-note}\n## Interpretation\n\nBoth series peak in Jan and drift downward into the wet season, and the geocoded events reach their lowest count in Aug. The dashed line marks an even spread of one ninth per month. The two series follow a similar shape, so the geocoded subset does not seem to distort the seasonal pattern, and I trust this result more than the province comparison. With 43 to 77 events a month, a difference of a few events between neighbouring months is within ordinary Poisson variation, so I only read the broad downward drift. The data stop in September, so the last quarter of the year is unknown.\n:::\n\n### Day-of-week pattern\n\nThe nine-month window has 40 Mondays and 39 of every other weekday, so I compare events per day. The null model spreads events across weekdays in proportion to how many of each weekday the window contains. I number weekdays with `lubridate` starting from Monday, since `weekdays()` returns labels in the system language.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndow_labels <- c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")\nall_days   <- seq(as.Date(\"2024-01-01\"), as.Date(\"2024-09-30\"), by = \"day\")\ndays_avail <- tabulate(wday(all_days, week_start = 1), nbins = 7)\n\ndow <- events %>%\n  st_drop_geometry() %>%\n  mutate(dow = wday(death_date, week_start = 1)) %>%\n  count(dow) %>%\n  complete(dow = 1:7, fill = list(n = 0)) %>%\n  mutate(days    = days_avail,\n         per_day = n / days,\n         dow_lab = factor(dow_labels[dow], levels = dow_labels),\n         weekend = dow >= 6)\n\ndow_test <- chisq.test(dow$n, p = dow$days / sum(dow$days))\n\nggplot(dow, aes(dow_lab, per_day, fill = weekend)) +\n  geom_col(width = 0.7) +\n  geom_hline(yintercept = sum(dow$n) / sum(dow$days), linetype = \"dashed\", colour = \"grey40\") +\n  scale_fill_manual(values = c(`FALSE` = \"#C9C3B6\", `TRUE` = \"#B5533C\"), guide = \"none\") +\n  labs(x = NULL, y = \"Events per day\") +\n  theme_minimal(base_size = 11)\n\nweekend_ratio <- with(dow, (sum(n[weekend]) / sum(days[weekend])) /\n                           (sum(n[!weekend]) / sum(days[!weekend])))\n```\n\n::: {.cell-output-display}\n![Fatal crash events per day, by day of week](Take-home_Ex01_files/figure-html/fig-dow-1.png){#fig-dow width=672}\n:::\n:::\n\n\n::: {.callout-note}\n## Interpretation\n\nSaturdays and Sundays have the most fatal crash events per day, and the weekend daily rate is 1.42 times the weekday rate. A chi-square test against the proportional null gives p = 0.0029, so random fluctuation alone is an unlikely explanation. The date is the date of death, and deaths after a hospital stay are shifted later than the crash, which blurs the weekday signal and could move part of it.\n:::\n\n::: {.callout-tip}\n## My takeaway\n\nMeasuring intensity per km of road changed how I read the map. Bangkok has the most fatal crashes, but Samut Prakan has more per km of major road.\n:::\n\n# Second-order Network Point Pattern Analysis\n\nSecond-order analysis asks whether fatal crashes sit closer to each other along the network than a random pattern would produce.\n\n**Research question.** I test whether fatal crash events on the major road network are clustered, regular or random at network distances up to 3 km.\n\n## Method and null model\n\nI use `kfunctions()` from `spNetwork`, which computes the network K-function of Okabe and Yamada (2001) and a network G-function. The K-function counts, for each event, the other events within network distance r, and it grows as r grows. The G-function in `spNetwork` counts events in a ring between r and r plus the ring width, so it shows at which distances events are more common than expected.\n\nThe null model is complete spatial randomness on the network, where the same number of events is placed independently and uniformly along the road length. The comparison assumes that under the null every km of road is equally likely to receive a crash. Section 3 showed that this is far from true, so part of any clustering found here reflects uneven intensity and part may reflect interaction. OSM also draws divided roads as two lines, so the null model gives these roads about twice the weight of an undivided road. `spNetwork` has no inhomogeneous version of the network K-function. `spatstat.linnet` offers one through `linearKinhom()`, which I leave for further work, so I read the K-function mainly as a description and rely on the G-function for the scale of the excess.\n\n## Parameters\n\n-   **Distance range.** I evaluate distances from 0 to 3 km in 50 m steps, which covers the street scale and the corridor scale.\n-   **Ring width.** The G-function uses rings 100 m wide, twice the step, so neighbouring rings overlap and the curve is smoother.\n-   **Simulations.** I run 49 simulations, close to the 50 used in the course exercise, and the envelope spans the 2.5% to 97.5% range of the simulated values. The envelope is pointwise, so with 61 distances a few isolated crossings are expected by chance.\n-   **Resolution.** Random points are placed on vertices every 100 m along the network, which makes the simulations much faster. A 100 m grid is fine compared with the distances I interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\nkfun <- kfunctions(network, ev, start = 0, end = 3000, step = 50, width = 100,\n                   nsim = 49, resolution = 100, conf_int = 0.05, verbose = FALSE)\nk_vals <- kfun$values\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkfun$plotk +\n  labs(title = NULL, x = \"Network distance (m)\", y = \"K(r)\") +\n  theme_minimal(base_size = 11)\n\nk_above   <- k_vals$distances[k_vals$obs_k > k_vals$upper_k]\nk_ratio_1 <- with(k_vals, obs_k[distances == 1000] / upper_k[distances == 1000])\n```\n\n::: {.cell-output-display}\n![Network K-function of fatal crash events with a network CSR envelope (49 simulations)](Take-home_Ex01_files/figure-html/fig-kfun-1.png){#fig-kfun width=672}\n:::\n:::\n\n\n::: {.callout-note}\n## Interpretation\n\nThe observed K-function lies above the envelope at 61 of the 61 distances from 0 to 3 km. At 1 km the observed value is 2.0 times the upper edge of the envelope. Fatal crashes have more neighbours along the network than a uniform random pattern would give at all scales examined. This fits the uneven intensity found in Section 3, where half of the intensity sits on 3.1% of the road length, and on its own it does not show that crashes interact.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkfun$plotg +\n  labs(title = NULL, x = \"Network distance (m)\", y = \"g(r)\") +\n  theme_minimal(base_size = 11)\n\ng_above <- k_vals$distances[k_vals$obs_g > k_vals$upper_g]\ng_below <- k_vals$distances[k_vals$obs_g < k_vals$lower_g]\nshort   <- k_vals$distances <= 400\ng_short_above <- sum(k_vals$obs_g[short] > k_vals$upper_g[short])\ng_short_rings <- sum(short)\ng_far_above   <- sum(k_vals$obs_g[!short] > k_vals$upper_g[!short])\ng_far_below   <- sum(k_vals$obs_g[!short] < k_vals$lower_g[!short])\ng_far_rings   <- sum(!short)\n```\n\n::: {.cell-output-display}\n![Network G-function (ring width 100 m) of fatal crash events with a network CSR envelope (49 simulations)](Take-home_Ex01_files/figure-html/fig-gfun-1.png){#fig-gfun width=672}\n:::\n:::\n\n\n::: {.callout-note}\n## Interpretation\n\nThe G-function lies above the envelope in 8 of the 9 rings up to 400 m, so fatal crashes are much more common than expected within a few hundred metres of each other along the road. Beyond 400 m the curve crosses the upper edge at 10 and the lower edge at 2 of 52 distances, mostly in brief runs. A pointwise 95% envelope would give about 5% crossings by chance, so this points to a much weaker and less consistent excess at the corridor scale. The excess at 0 m also includes the co-located events at identical coordinates. Uneven intensity along roads could still produce part of this short-range excess, since crash-prone segments hold several crashes each.\n:::\n\n::: {.callout-tip}\n## My takeaway\n\nThe K-function stays above its envelope at every distance, which on its own says little, since network CSR ignores where roads carry traffic. The G-function was more useful, because it shows that the excess sits within about 400 m.\n:::\n\n# Value-added Analysis: Space-time Interaction on the Network\n\nThe G-function shows that fatal crashes sit close to each other along the road within about 400 m. That could come from fixed locations where crashes keep happening over the months, or from short bursts where one crash is followed by another nearby within days. Persistent locations point to engineering fixes at specific sites, and short bursts point to temporary enforcement after a crash. None of the methods above can tell these apart, since the K- and G-functions ignore time.\n\n## Network distances between events\n\nI compute the network distance between every pair of events. I cut the network into 50 m pieces with `lixelize_lines()`, build a weighted graph of their end points with `igraph` and attach each event to the nearer end of its nearest piece, which puts it within 25 m of its snapped position. `igraph::distances()` then gives the shortest-path distance between every pair.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlx50 <- lixelize_lines(network, 50, mindist = 25)\nc50  <- st_coordinates(lx50)\nf50  <- c50[!duplicated(c50[, \"L1\"]), ]\nl50  <- c50[!duplicated(c50[, \"L1\"], fromLast = TRUE), ]\ng50  <- igraph::graph_from_data_frame(\n  data.frame(from = node_key(f50), to = node_key(l50),\n             weight = as.numeric(st_length(lx50))), directed = FALSE)\n\nnear50  <- st_nearest_feature(ev, lx50)\nev_xy   <- st_coordinates(ev)\nd_first <- sqrt((ev_xy[, 1] - f50[near50, \"X\"])^2 + (ev_xy[, 2] - f50[near50, \"Y\"])^2)\nd_last  <- sqrt((ev_xy[, 1] - l50[near50, \"X\"])^2 + (ev_xy[, 2] - l50[near50, \"Y\"])^2)\nev_node <- if_else(d_first <= d_last,\n                   node_key(f50[near50, , drop = FALSE]),\n                   node_key(l50[near50, , drop = FALSE]))\n\nnodes_u <- unique(ev_node)\nD <- igraph::distances(g50, v = nodes_u, to = nodes_u)\nnet_d <- D[ev_node, ev_node] / 1000\n\nnd_ratio <- round(median((net_d / (as.matrix(dist(ev_xy)) / 1000))[upper.tri(net_d)], na.rm = TRUE), 2)\n\ntibble(pairs = nrow(ev) * (nrow(ev) - 1) / 2,\n       unreachable = sum(is.infinite(net_d[upper.tri(net_d)])),\n       median_network_km = round(median(net_d[upper.tri(net_d)]), 1),\n       median_ratio_to_straight = round(median((net_d / (as.matrix(dist(ev_xy)) / 1000))[upper.tri(net_d)], na.rm = TRUE), 2)) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| pairs| unreachable| median_network_km| median_ratio_to_straight|\n|-----:|-----------:|-----------------:|------------------------:|\n| 69751|           0|              37.9|                      1.2|\n\n\n:::\n:::\n\n\nAll pairs are connected, and the median ratio of network to straight-line distance is 1.2, so travel along the road adds about 20% to a typical straight-line gap between two crash sites.\n\n## Method and null model\n\nI use the Knox test (Knox, 1964), which counts pairs of events that are close in both network distance and time. The null model keeps every location and the full set of dates fixed and randomly shuffles the dates among the events. This controls for both the spatial pattern and the seasonal pattern, so an excess of close pairs can only come from space and time acting together.\n\nI set the thresholds in advance at 0.5, 1 and 2 km of network distance and 7, 14 and 30 days, which spans the 400 m scale of the G-function excess and gaps from one week to one month. Each cell uses 999 permutations, and the test is one-sided, since the question is whether close pairs are more common than expected. I wrote the Knox functions myself with base R and `purrr`. Nine cells mean nine tests, so a single cell below 0.05 would be weak evidence. Deaths at the same point on the same date were merged into one event, so the observed data contain no pair at zero distance and zero days, while shuffled dates could create one. With so few co-located events this adds well under one pair to each expected count.\n\n\n::: {.cell tbl-cap='Knox test on network distances (999 permutations)'}\n\n```{.r .cell-code}\ndoy     <- yday(ev$death_date)\nupper   <- upper.tri(net_d)\nspace_d <- net_d[upper]\n\nthresholds <- expand_grid(space_km = c(0.5, 1, 2), time_days = c(7, 14, 30))\n\nknox_counts <- function(days) {\n  time_d <- abs(outer(days, days, \"-\"))[upper]\n  map2_int(thresholds$space_km, thresholds$time_days,\n           ~ sum(space_d <= .x & time_d <= .y))\n}\n\nset.seed(2024)\nn_perm   <- 999\nknox_obs <- knox_counts(doy)\nknox_sim <- replicate(n_perm, knox_counts(sample(doy)))\n\nknox_res <- thresholds %>%\n  mutate(observed = knox_obs,\n         expected = round(rowMeans(knox_sim), 1),\n         ratio    = round(observed / expected, 2),\n         p_value  = (1 + rowSums(knox_sim >= knox_obs)) / (n_perm + 1),\n         p_lower  = (1 + rowSums(knox_sim <= knox_obs)) / (n_perm + 1))\nkable(knox_res)\n```\n\n::: {.cell-output-display}\n\n\n| space_km| time_days| observed| expected| ratio| p_value| p_lower|\n|--------:|---------:|--------:|--------:|-----:|-------:|-------:|\n|      0.5|         7|        1|      2.7|  0.37|   0.942|   0.237|\n|      0.5|        14|        2|      5.2|  0.38|   0.979|   0.087|\n|      0.5|        30|        8|     10.4|  0.77|   0.866|   0.244|\n|      1.0|         7|        2|      4.3|  0.47|   0.928|   0.188|\n|      1.0|        14|        3|      8.1|  0.37|   0.989|   0.029|\n|      1.0|        30|       15|     16.6|  0.90|   0.730|   0.382|\n|      2.0|         7|        8|      8.8|  0.91|   0.675|   0.484|\n|      2.0|        14|       13|     16.7|  0.78|   0.870|   0.207|\n|      2.0|        30|       30|     34.2|  0.88|   0.827|   0.247|\n\n\n:::\n\n```{.r .cell-code}\nknox_min <- which.min(knox_res$p_lower)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(knox_res, aes(factor(time_days), factor(space_km), fill = ratio)) +\n  geom_tile(colour = \"white\", linewidth = 1) +\n  geom_text(aes(label = sprintf(\"%.2f\\np = %.2f\", ratio, p_value)), size = 3.5) +\n  scale_fill_gradient2(low = \"#7A8B6F\", mid = \"#F4F1EA\", high = \"#B5533C\",\n                       midpoint = 1) +\n  labs(x = \"Time threshold (days)\", y = \"Space threshold (km)\",\n       fill = \"Observed /\\nexpected\") +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![Ratio of observed to expected close pairs in the network Knox test, with one-sided p-values](Take-home_Ex01_files/figure-html/fig-knox-1.png){#fig-knox width=672}\n:::\n:::\n\n\n\n\n::: {.callout-note}\n## Interpretation\n\nNo combination of thresholds shows more close pairs than expected. The observed-to-expected ratio ranges from 0.37 to 0.91, and the smallest one-sided p-value is 0.675. The cell with the smallest lower-tail p, at 1 km and 14 days, has fewer close pairs than expected (p = 0.029), but it rests on 3 pairs and is one cell out of nine, so I do not read it as avoidance. Fatal crashes that happen near each other on the network are spread across the nine months without bunching in time, which fits persistent crash locations. The death date can lag the crash by days, which blurs the 7-day threshold most.\n:::\n\n# Integrated Findings and Sensitivity Analysis\n\n## How the results fit together\n\nThe NKDE shows fatal crashes concentrated on a small share of the major road network, with half of the intensity on 3.1% of the road length. Per km of road, primary and secondary roads have the highest rates, and Samut Prakan has a higher rate than Bangkok whether divided roads are counted once or twice. The network K-function confirms that crashes have more neighbours along the road than a uniform pattern would give at every distance, and the G-function places the clearest excess within about 400 m. The Knox test adds that nearby crashes do not bunch within days or weeks of each other.\n\nThe three views agree on one picture. Fatal crashes on major roads cluster on particular stretches of road, and the lack of space-time interaction fits stretches that keep producing crashes over the months.\n\n## Sensitivity\n\nThe NKDE hotspots are stable between 500 m and 1 km and spread out at 2 km, so the hotspot locations depend on the bandwidth only at the wide end of the range tested. The likelihood cross-validation gave no interior optimum, so the 1 km choice rests on the planning scale and on this stability check.\n\nThe network K- and G-functions use 49 simulations and a pointwise envelope. The short-range G-function excess covers 8 of the 9 rings up to 400 m, far more than chance crossings would give. The crossings beyond 400 m are fewer and come in brief runs, and fewer simulations or a different seed could move them, so I read them as weak evidence of corridor-scale excess.\n\nThe 50 m snapping tolerance decides which events enter the analysis. A wider tolerance would pull more crashes from local roads onto major roads and place them on the wrong segments, and a narrower one would drop crashes on wide roads with frontage lanes.\n\n## Alternative explanations\n\nSeveral explanations other than crash interaction fit the short-range clustering.\n\n-   **Uneven intensity along roads.** Some segments carry far more traffic than others, and network CSR treats every km as equal. Crash-prone segments hold several crashes each, which produces short-range excess in the G-function without any interaction between crashes.\n-   **Geocoding practice.** Some coordinates may be placed at a hospital, a police station or a district reference point. That would produce tight groups of points unrelated to where the crashes happened. The 10 extra events at coordinates already used by another event are a warning sign.\n-   **Record source and road coverage.** The analysed pattern leaves out deaths from the record source without crash details and crashes more than 50 m from a major road. Nearly all analysed crashes involve motorcycles, so the results apply to fatal motorcycle crashes on major roads.\n\n# Geovisualisation and Geocommunication\n\nI kept the maps and charts in one colour scheme that matches the rest of my site, terracotta for observed values and sage for reference values. The NKDE map uses a sequential yellow-to-red palette with fixed class breaks, since most of the network has zero or near-zero intensity and quantile breaks would collapse. I draw the lixels in order of intensity, so the high-intensity segments sit on top of the low ones and stay visible.\n\nThe monthly chart shows shares of each series total, since the two series differ in size by a factor of three. The K- and G-function plots keep the layout from `spNetwork`, with the observed curve over the simulation envelope, and I relabelled the axes in metres of network distance.\n\nEach major figure has an interpretation box of no more than 150 words next to it. Each box states what the figure shows, the evidence from the figure or test behind it and the main caveat.\n\n# Public-safety Planning and Management Implications\n\n## What the analysis supports\n\nFatal crashes on the major road network concentrate on a small share of road length, with half of the estimated intensity on 3.1% of it. This supports targeting road audits, enforcement and ambulance coverage at a short list of road stretches, and the NKDE map gives a first version of that list. The hotspots stay in place between 500 m and 1 km bandwidths, so the list does not depend on a narrow technical choice.\n\nPer km of road, primary and secondary roads have the highest fatal crash rates, and Samut Prakan has a higher rate than Bangkok under both ways of counting divided roads. Planning that allocates resources by crash counts would favour Bangkok, while planning by crashes per km of road would give Samut Prakan and the arterial roads of Pathum Thani a larger share.\n\nWithin about 400 m, fatal crashes sit closer together along the road than a random pattern predicts, and nearby crashes are spread across the nine months without bunching in time. This fits persistent crash sites, which call for engineering measures at those sites, such as junction redesign, safer crossings, lighting and speed management. A temporary police presence after each fatal crash fits the evidence less well, since the Knox test found no sign that one crash is followed by another nearby within days.\n\nWeekends have about 42% more fatal crash events per day than weekdays, which supports stronger weekend enforcement and ambulance staffing. The exact crash time is not in the data, so the hours to target remain open.\n\nMotorcyclists make up 92.9% of BMR deaths with a recorded vehicle and 97.1% of the geocoded ones, so these results describe fatal motorcycle crashes and support focusing effort on motorcyclists in the identified stretches.\n\n## What needs more information\n\nCrashes per km of road do not measure risk. Turning the rates into risk needs traffic volumes by segment, and without them I cannot say whether a hotspot is dangerous per trip or simply busy.\n\nAbout a quarter of the geocoded crashes lie more than 50 m from a major road and are left out of this analysis. Deaths from the record source without crash details have no location at all, and linking them to the police records that hold the crash location would close that second gap.\n\nChoosing between measures such as helmet enforcement, speed control or junction redesign needs data on helmet use, speed, alcohol and road design at each site. The dataset records none of these, so I make no claims about why crashes happen where they do.\n\n# Limitations\n\n-   **Record source and geocoding.** Only 36% of BMR deaths have coordinates, and deaths from the source without crash details are almost never geocoded. All spatial results describe the geocoded subset, which consists almost entirely of motorcycle crashes.\n-   **Major roads only.** The network covers motorway to tertiary roads. Events more than 50 m from these roads, about a quarter of the total, are left out, and the share differs by province.\n-   **Death date used for crash date.** The date of death can lag the crash by days or weeks. This affects the weekday analysis and the 7-day Knox threshold most.\n-   **Nine-month window.** The data end on 30 September 2024, so the results say nothing about the last quarter of the year, which includes the New Year holiday.\n-   **NKDE method and bandwidth.** At 1 km the simple method loses about 27% of the kernel mass, more near the boundary, so intensities are relative. Cross-validation gave no interior optimum, and the 1 km bandwidth is a judgement checked by sensitivity analysis.\n-   **Homogeneous null model.** Network CSR assumes equal intensity per km of road. The network K- and G-functions therefore mix uneven intensity with any interaction between crashes.\n-   **Divided roads and direction.** Distances ignore one-way restrictions, and OSM draws most divided roads as two lines. This roughly halves the rate per km of mapped line on divided roads and gives them about double weight in the network null model. The rate table reports both counting methods.\n-   **No exposure data.** Rates are per km of road and do not reflect traffic volume or population at risk.\n\n# References\n\n-   Csardi, G., & Nepusz, T. (2006). The igraph software package for complex network research. *InterJournal, Complex Systems*, 1695.\n-   Gelb, J. (2021). spNetwork, a package for network kernel density estimation. *The R Journal*, 13(2).\n-   Grolemund, G., & Wickham, H. (2011). Dates and times made easy with lubridate. *Journal of Statistical Software*, 40(3), 1–25.\n-   Knox, E. G. (1964). The detection of space-time interactions. *Journal of the Royal Statistical Society, Series C (Applied Statistics)*, 13(1), 25–30.\n-   Okabe, A., Satoh, T., & Sugihara, K. (2009). A kernel density estimation method for networks, its computational method and a GIS-based tool. *International Journal of Geographical Information Science*, 23(1), 7–32.\n-   Okabe, A., & Sugihara, K. (2012). *Spatial Analysis Along Networks, Statistical and Computational Methods*. Wiley.\n-   Okabe, A., & Yamada, I. (2001). The K-function method on a network and its computational implementation. *Geographical Analysis*, 33(3), 271–290.\n-   OpenStreetMap contributors. (2026). *OpenStreetMap data extract for Thailand* [Data set]. Geofabrik. <https://download.geofabrik.de/asia/thailand.html>. Accessed 26 September 2026.\n-   Pebesma, E. (2018). Simple features for R, standardized support for spatial vector data. *The R Journal*, 10(1), 439–446.\n-   pornsakkamchan. (2025). *Thailand Road Accident Fatalities 2024* [Data set]. Kaggle. <https://www.kaggle.com/datasets/pornsakkamchan/thailand-road-accident-fatalities-2024>. Accessed 20 September 2026.\n-   Runfola, D., et al. (2020). geoBoundaries, a global database of political administrative boundaries. *PLoS ONE*, 15(4), e0231866.\n-   Tennekes, M. (2018). tmap, thematic maps in R. *Journal of Statistical Software*, 84(6), 1–39.\n-   Wickham, H., et al. (2019). Welcome to the tidyverse. *Journal of Open Source Software*, 4(43), 1686.\n-   Wikipedia contributors. (2026). Bangkok Metropolitan Region. *Wikipedia*. <https://en.wikipedia.org/wiki/Bangkok_Metropolitan_Region>. Accessed 26 September 2026.\n-   World Health Organization. (2019). *International Statistical Classification of Diseases and Related Health Problems, 10th Revision (ICD-10)*. WHO.\n-   Xie, Z., & Yan, J. (2008). Kernel density estimation of traffic accidents in a network space. *Computers, Environment and Urban Systems*, 32(5), 396–406.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}