{
  "hash": "2dda9d1c3971264725692cd7f23a4d5a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Where Fatal Crashes Concentrate on Bangkok's Major Roads\"\nsubtitle: \"Take-home Exercise 1 · Executive Summary\"\nauthor: \"Meng Tingyu\"\ndate: \"27 September 2026\"\nformat:\n  revealjs:\n    theme: [simple, slides.scss]\n    slide-number: true\n    toc: true\n    toc-depth: 2\n    toc-title: \"Contents\"\n    width: 1280\n    height: 720\n    footer: \"Geospatial Analytics · Take-home Exercise 1 · Road traffic fatalities in the BMR, 2024\"\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n## The question\n\n-   12,762 road deaths were recorded in Thailand between January and September 2024, 1,486 of them in the six provinces of the Bangkok Metropolitan Region (BMR).\n-   A crash can only happen on a road, so I measure intensity per km of road and distance along the road, using the network methods of `spNetwork`.\n\n::: {.takeaway}\n1.  Where on the major road network do fatal crashes concentrate?\n2.  Do they cluster along the road, and at what distance?\n3.  Do crashes close together on the road also happen close together in time?\n:::\n\n## Study area and data\n\n:::: {.columns}\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_slides_files/figure-revealjs/unnamed-chunk-1-1.png){width=624}\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Step                         |n      |\n|:----------------------------|:------|\n|Deaths recorded in Thailand  |12,762 |\n|After removing duplicates    |12,738 |\n|With crash coordinates       |3,240  |\n|Inside the BMR               |530    |\n|Crash events (deaths merged) |515    |\n|Within 50 m of a major road  |374    |\n\n\n:::\n:::\n\n\n::: {.small}\nFatalities from Kaggle (Department of Disease Control), province boundaries from geoBoundaries and 10,489 km of major roads from OpenStreetMap.\n:::\n:::\n::::\n\n## Data quality decides what the map can show\n\n:::: {.columns}\n::: {.column width=\"33%\"}\n::: {.big-number}\n36%\n:::\n::: {.big-label}\nof BMR deaths have crash coordinates\n:::\n\n::: {.big-number}\n16 of 586\n:::\n::: {.big-label}\ndeaths with no recorded vehicle are geocoded\n:::\n\n::: {.big-number}\n97.1%\n:::\n::: {.big-label}\nof geocoded deaths are motorcyclists\n:::\n:::\n\n::: {.column width=\"67%\"}\n-   Deaths with no recorded vehicle also lack the sub-district and home province, and 91.1% carry the ICD-10 code V89.2. They most likely come from a record source without crash details.\n-   The file needed four silent fixes, swapped latitude and longitude, Buddhist Era dates that fail on 29 February, deaths merged into crash events and OSM roads split at junctions.\n\n::: {.caveat}\nThe maps describe fatal motorcycle crashes with a recorded location on major roads, which is 374 of the 515 geocoded crash events.\n:::\n:::\n::::\n\n## Analytical approach\n\n| Question | Method | Key settings | Compared with |\n|---|---|---|---|\n| Where do crashes concentrate | Network kernel density (NKDE) | Quartic kernel, simple method, 1 km bandwidth, 200 m lixels, 500 m and 2 km for sensitivity | Other bandwidths |\n| How intensity varies by road | Crashes per 100 km of road | Road class and province, divided roads counted once and twice | Network length |\n| Do crashes cluster | Network K- and G-functions | 0 to 3 km, 100 m rings, 49 simulations | Random placement along the network |\n| Do nearby crashes bunch in time | Knox test on network distance | 0.5 to 2 km, 7 to 30 days, 999 permutations | Dates shuffled among events |\n\n## Half of the intensity sits on 3.1% of the road length\n\n:::: {.columns}\n::: {.column width=\"62%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_slides_files/figure-revealjs/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"38%\"}\n-   The densest cluster is in central Bangkok, with shorter hotspots along corridors in Pathum Thani and Samut Prakan.\n-   49% of the top 5% of road segments are in Bangkok, and 73% are primary or secondary roads.\n-   The hotspots stay in place at 500 m (overlap 89.8%) and spread out at 2 km.\n\n::: {.caveat}\nThe simple method loses about 27% of the kernel mass, more near the boundary, so values are relative.\n:::\n:::\n::::\n\n## Per km of road, primary roads and Samut Prakan stand out\n\n:::: {.columns}\n::: {.column width=\"62%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_slides_files/figure-revealjs/unnamed-chunk-4-1.png){width=720}\n:::\n:::\n\n:::\n\n::: {.column width=\"38%\"}\n-   Primary and secondary roads have the highest rates under both ways of counting divided roads.\n-   Bangkok has the most crashes, but Samut Prakan has more per km of major road.\n-   Samut Prakan is geocoded less often than Bangkok, so geocoding bias does not explain its higher rate.\n\n::: {.caveat}\nRates are per km of road. Without traffic volumes they do not measure risk per trip.\n:::\n:::\n::::\n\n## Weekends and the start of the year are worse\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_slides_files/figure-revealjs/unnamed-chunk-5-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_slides_files/figure-revealjs/unnamed-chunk-6-1.png){width=576}\n:::\n:::\n\n:::\n::::\n\n::: {.takeaway}\nThe weekend daily rate is 1.42 times the weekday rate (chi-square p = 0.0029). Crashes peak in Jan and drift down through the year, with the same shape in the geocoded subset and in all deaths.\n:::\n\n## Crashes cluster within about 400 m along the road\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_slides_files/figure-revealjs/unnamed-chunk-7-1.png){width=1152}\n:::\n:::\n\n\n-   The K-function is above the random-placement envelope at 61 of 61 distances, and the G-function is above it in 8 of the 9 rings up to 400 m.\n\n::: {.caveat}\nRandom placement treats every km of road as equal, so part of this excess reflects uneven intensity along roads.\n:::\n\n## Nearby crashes do not bunch in time\n\n:::: {.columns}\n::: {.column width=\"55%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01_slides_files/figure-revealjs/unnamed-chunk-8-1.png){width=595.2}\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n-   The Knox test shuffles dates among crash events and counts pairs close in both network distance and time.\n-   Every cell has fewer close pairs than expected (ratios 0.37 to 0.91), and the smallest one-sided p-value is 0.675.\n\n::: {.takeaway}\nCrashes near each other on the road are spread over the months, which fits persistent crash sites and argues against short bursts.\n:::\n:::\n::::\n\n## Implications and limits\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n**What the evidence supports**\n\n-   Target road audits, enforcement and ambulance coverage at a short list of stretches, since half of the intensity sits on 3.1% of the road length.\n-   Allocate by crashes per km of road as well as by counts, which shifts attention to Samut Prakan and arterial roads.\n-   Favour engineering at persistent sites over patrols after each crash.\n-   Strengthen weekend enforcement, and focus on motorcyclists.\n:::\n\n::: {.column width=\"50%\"}\n**Where the evidence stops**\n\n-   Only 36% of BMR deaths have a location, and a quarter of geocoded crashes lie away from major roads.\n-   Without traffic volumes, rates per km do not measure risk.\n-   Random placement on the network ignores uneven intensity, so clustering mixes both effects.\n-   Death dates stand in for crash dates.\n-   Linking death records to police records would close the largest data gap.\n:::\n::::\n",
    "supporting": [
      "Take-home_Ex01_slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}